### ISSUE TITLE
I cannot Upload a Folder Full of content ?

### ISSUE THREAD

**Issue by CryptoRootz** [ipfs-shipyard/ipfs-webui#1002]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fsdiogo** [comment]
You should be able to:

<img width="1021" alt="1" src="https://user-images.githubusercontent.com/33324750/55717681-c3e3fe00-59f1-11e9-9b61-30b55d7ad848.png">

<img width="1026" alt="2" src="https://user-images.githubusercontent.com/33324750/55717682-c3e3fe00-59f1-11e9-9156-72b23e1341ac.png">

**Comment by jessicaschilling** [comment]
Closing (stale). Please re-open if needed -- thank you!
