### ISSUE TITLE
Discussion fodder: IPFS Web UI / Desktop design review

### ISSUE THREAD

**Issue by ericronne** [ipfs-shipyard/ipfs-webui#1004]
_Notes from my design review of IPFS Desktop (which, of course, largely reflects the Web UI interface), for discussion …_

This interface is very well designed; I found no glaring issues in my review. It could be improved here and there, but nothing is terribly awry, imo. That said, below are some comments touching on visual design, heuristics, functionality, and accessibility.

Stepping back from these granular thoughts, I wonder if a fully new concept might be interesting and useful. The app is currently structured much like a website: divided into sections, with global navigation running down the side. It might prove more useful structured as a dashboard, with lots of information surfaced in a compact layout. I’ve wired up one way this could be laid out over in #1003. Doubtless it's too much work for us to take on right now, given our documented priorities, but it’s a conversation starter, at least.

Meanwhile, [here are some notes](https://docs.google.com/document/d/1jQn14u8CJm8fOjLPbo2lug4RG3Eb8ulHX1LVlu9jMck/edit#) on the current app.

**Comment by jessicaschilling** [comment]
Closing this issue and adding the design review notes to https://github.com/ipfs-shipyard/ipfs-webui/issues/1003 - thanks!
