### ISSUE TITLE
API shell text does not apply to Windows

### ISSUE THREAD

**Issue by djdv** [ipfs-shipyard/ipfs-webui#1008]
**Describe the bug**
When failing to connect to the daemon, the webui shows shell prompts that are invalid on Windows.
![shell](https://user-images.githubusercontent.com/13862850/55897834-51a92000-5b8f-11e9-9e2a-ac3c1e3c050a.png)
***
`ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://127.0.0.1:8080", "http://127.0.0.1:5001", "https://webui.ipfs.io"]'`
returns these messages in: 
 - PowerShell: `Error: failed to unmarshal json. invalid character 'h' looking for beginning of value`
 - CMD: `Error: Unknown Command "API.HTTPHeaders.Access-Control-Allow-Origin"`

Valid forms of this are:
 - PowerShell: `ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"http://127.0.0.1:8080\", \"http://127.0.0.1:5001\", \"https://webui.ipfs.io\"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"PUT\", \"GET\", \"POST\"]'`
 - CMD: `ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "["""http://127.0.0.1:8080""", """http://127.0.0.1:5001""", """https://webui.ipfs.io"""]"
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods "["""PUT""", """GET""", """POST"""]"`

It would be nice if the shell element had some way to select what command shell you're using, and formatted the string so the arguments matched the escape type.

**Comment by abdenoursouidi** [comment]
You are a hero ♥

**Comment by lidel** [comment]
cc @jessicaschilling @rafaelramalho19  see the snippets created by @djdv  :-) 

(context: we discussed this very thing today!)

**Comment by jessicaschilling** [comment]
Moving this to the "Quick Fixes" in Zenhub ...

@rafaelramalho19 -- is this something you're still able to take on at some point?

@lidel -- thank you!

**Comment by rafaelramalho19** [comment]
Thank you so much for looking into this in the past @djdv 🙏 

Will fix it ASAP 😄

**Comment by itm-platform** [comment]
Hi there,
I tried both (Windows 11)
- PowerShell: `ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '[\"true\"]'`
- CMD: `ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "["""true"""]"`
And I get in both cases
```
 failure to decode config: json: cannot unmarshal string into Go struct field API.API.HTTPHeaders of type []string
```
I also tried all forms of adding the config file
```json
  "API": {
    "HTTPHeaders": {
	"Access-Control-Allow-Origin": "['*']"
	}
  }
```
But I get the same error.
Any ideas?
