### ISSUE TITLE
Bug Report: WebUI through browser is not working

### ISSUE THREAD

**Issue by jasikpark** [ipfs-shipyard/ipfs-webui#1031]
**Describe the bug**
I cannot view the status of IPFS from my browser

**To Reproduce**
1. Install via `brew cask install ipfs`
2. Install the ipfs-companion Firefox extension
3. Open "IPFS Desktop.app" and view the successful peering from within the app
4. Select "Open WebUI" from the ipfs-companion menu and get an error that `ipfs daemon` needs to be run.

**Expected behavior**
I expect the WebUI to be accessible from any interface that can load localhost:5001/webui

**Screenshots**
View from IPFS Desktop:
<img width="690" alt="Screenshot 2019-05-07 17 45 24" src="https://user-images.githubusercontent.com/10626596/57337845-a7baa600-70f0-11e9-8598-f573c384b9fa.png">

View from localhost:8080:
<img width="690" alt="Screenshot 2019-05-07 17 45 06" src="https://user-images.githubusercontent.com/10626596/57337857-b2753b00-70f0-11e9-9570-4180085e4ef1.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Firefox
 - Version: go-ipfs v0.4.19

**Comment by olizilla** [comment]
Hi @jasikpark you should be able to visit the webui via http://localhost:5001/webui

http://localhost:8080 isn't expected to work out of the box as the API has CORS restrictions in place that only allow access from a site loaded from 127.0.0.1:5001.

If the api allowed access from content loaded via :8080 then any site that you visited via IPFS would be able to access your api, not just webui.

**Comment by olizilla** [comment]
You very much should be able to use the "Open Web UI" button from within companion tho, and it should be able to talk to the api provided by IPFS Desktop... that is odd.

**Comment by olizilla** [comment]
@jasikpark can you share the full url that you get redirected to when you hit "Open Web UI" in companion?

**Comment by jasikpark** [comment]
Full URL:
http://127.0.0.1:8080/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/

I also typed http://127.0.0.1:5001/webui/ into the bar and got redirected to http://127.0.0.1:5001/ipfs/QmXc9raDM1M5G5fpBnVyQ71vR4gbnskwnB9iMEzBuLgvoZ/

it also failed to connect to the API

**Comment by jasikpark** [comment]
I've tried uninstalling and reinstalling go-ipfs and IPFS Desktop multiples times, in addition to nuking `~/.ipfs` in concert with reinstallation. For some reason, the api only works when accessed through IPFS Desktop, rather than a web browser

**Comment by hazae41** [comment]
Does ipfs-companion work?

**Comment by jasikpark** [comment]
ipfs-companion works fine - though when i click the "Show WebU" button within ipfs-companion the page it loads fails to access the API.

but ipfs-companion is redirecting and loading and pinning perfectly.

**Comment by olizilla** [comment]
@jasikpark I've wiped my local set up and tried to recreate this, but it seems to be working. Can you share the `API` and `Adresses` sections of your config, to help diagnose this? Have you ever installed ipfs before via some other mechanism?

**Comment by jasikpark** [comment]
I think it might be that I have both go-ipfs and IPFS Desktop installed, and maybe that's a problem. Though I tried both of them installed by themselves and that did not fix the problem once it appeared.

**Comment by lidel** [comment]
@jasikpark assuming this is fixed in go-ipfs 0.6.0 / ipfs-desktop 0.12.2 – please upgrade and reopen if you still experience this problem.
