### ISSUE TITLE
Add indicators for bitswap status: which peers

### ISSUE THREAD

**Issue by Stebalien** [ipfs-shipyard/ipfs-webui#1037]
It would be nice to be able to see which peers we are exchanging data with. We can get this information with `ipfs bitswap stat` and `ipfs bitswap ledger`.

Context: https://github.com/ipfs/go-ipfs/issues/3330.

**Comment by jessicaschilling** [comment]
@Stebalien and @lidel: This is an old issue, but wanted to check in - maybe a good bounty candidate?

OTMH, I'd imagine this as being represented in the UI in the Peers screen table (sortable column), but would welcome any other approaches you'd have in mind. Thanks!

**Comment by Stebalien** [comment]
My main concern with making this a bounty is that it needs some design (ux) work first. But other than that, yes.

Showing this on the peers table sounds reasonable. I'd love to see _rates_ on the map as well, but that would require tracking this `ipfs bitswap ledger` over time.

**Comment by jessicaschilling** [comment]
> My main concern with making this a bounty is that it needs some design (ux) work first

@Stebalien too simplistic?
![image](https://user-images.githubusercontent.com/1507828/90823234-d8791b80-e2f2-11ea-8a21-26b87b03a039.png)

**Comment by lidel** [comment]
@jessicaschilling fysa we are able to tell how much data was sent / received per peer historically, and at the moment.

- Perhaps we could display `RateIn` / `RateOut` next to the green dot? (or on hover, like we do for _Connection_ column)
- Should we also display `TotalIn` / `TotalOut` for peers which don't have green dot, but have those values above zero?
- (loose thought) by comparing In/Out we are able to tell the dominant direction of the data flow, perhaps we could [reuse In/Out colors from bandwidth graph on Status page](https://user-images.githubusercontent.com/157609/91221042-5e46fd80-e71d-11ea-8703-4050535e931e.png)?


Some examples below, for your reference.
 
## Stat source examples

#### Realtime stats per peer

(we use `ipfs stats bw` for bandwidth graph on Status page, but we don't filter per peer, just get global stats)

```console
$ ipfs stats bw -p QmPeer1
Bandwidth
TotalIn: 207 kB
TotalOut: 940 kB
RateIn: 0 B/s
RateOut: 0 B/s
```

#### Historical stats 

`ipfs bitswap ledger` keeps track of past transfers, most numbers will overlap with totals from `ipfs stats bw`. 

Peer that did not exchange data with us yet (no icon):

```console
$ ipfs bitswap ledger QmPeer2
Ledger for QmPeer2
Debt ratio:	0.000000
Exchanges:	0
Bytes sent:	0
Bytes received:	0
```

Peer that fetched stuff from us (`sent` vs `received`, or just look at `ratio`)

```console
$ ipfs bitswap ledger QmPeer3
Ledger for QmPeer3
Debt ratio:	561.000000
Exchanges:	1
Bytes sent:	561
Bytes received:	0
```

**Comment by jessicaschilling** [comment]
Closing this one in favor of general Peers page table enhancement in https://github.com/ipfs-shipyard/ipfs-webui/issues/1602.
