### ISSUE TITLE
Dropping multiple files only adds one on Chrome

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#1045]
**Describe the bug**
Using go-ipfs 0.4.19 & Chrome stable 74 drop multiple individual files... only 1 file is added.

**To Reproduce**
1. Go to files
2. Drop two or more files on the page
3. Only one file appears added

Firefox is not affected. The files are all added as expected.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome (and electron)
 - Version: 74

**Comment by olizilla** [comment]
@hacdias we really need that test suite for adding files!

**Comment by hacdias** [comment]
@olizilla I'll start working on them as soon as I can. I'll use the #1034 PR because it's related.

**Comment by olizilla** [comment]
@hacdias let's keep the test suite seperate from work that changes how files get added. Please make a new branch off master for the suite, and then when we're happy with it, merge it in, and pull it into those branches. Step 1 is add file tests for webui.

**Comment by hacdias** [comment]
Only one files get detected. Here's the issue for that: https://github.com/grabantot/datatransfer-files-promise/issues/1

It seems that person found the fix, but the creator just closed the issue and didn't fix it.
