### ISSUE TITLE
Test suite for all the adding files permutations

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#1046]
Handling drag and drop of files and adding via a file input, on firefox, chrome and electron has introduced _a lot_ of edge-cases we have to handle. We've gotta capture this knowledge in a test suite that tells us if we do something that breaks it automatically.

- [ ] file-drop at root
  - 1 file
  - multiple files
  - multiple files and system files are filtered out
  - 1 directory
  - 1 directory and system files are filtered out
  - muliple directories (pretty sure dropping multiple dirs has never worked)
- [ ] file-drop on folder
  - 1 file
  - multiple files
  - multiple files and system files are filtered out
  - 1 directory
  - 1 directory and system files are filtered out
  - muliple directories (pretty sure dropping multiple dirs has never worked)
- [ ] file-input
   - 1 file
   - multiple files
   - multiple files and system files are filtered out
  - 1 directory
  - 1 directory and system files are filtered out

and have a way to check the edge-cases of

- [ ] firefox
- [ ] chrome
- [ ] ipfs-desktop

**Comment by olizilla** [comment]
Of note, puppeteer doesnt seem to support drag and drop of files https://github.com/GoogleChrome/puppeteer/issues/1376

So it might be simpler to start with tests that mock out the different file object shapes that we see in each browser, and at least test that our normalisation and "add to ipfs" logic is correct.

**Comment by hacdias** [comment]
Also found [`puppeteer-firefox`](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox) and [Is Pupeteer-firefox ready?](https://aslushnikov.github.io/ispuppeteerfirefoxready/) page. Despite being experimental it seems it'd support all the API we need. And it'd allow us to use the same API easily. Also, puppeteer seems to work with Electron apps too.

**Comment by hacdias** [comment]
Another _not so good_ issue https://github.com/GoogleChrome/puppeteer/issues/2946

**Comment by olizilla** [comment]
> So it might be simpler to start with tests that mock out the different file object shapes that we see in each browser, and at least test that our normalisation and "add to ipfs" logic is correct.

We can write mocha tests that check our code, rather than running it in a browser and actually drop a file. We can create tests that start with the sort of object shapes that we get from the different browsers. I can help with this later, but start with the simplest test you can think of.

**Comment by olizilla** [comment]
We need some reliable unit-ish tests around this. We dont want flakey browser tests.

**Comment by olizilla** [comment]
This is done... for now
