### ISSUE TITLE
Peers screen should be aware of Relays

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1058]
**Is your feature request related to a problem? Please describe.**

A lot of people enable [`EnableAutoRelay`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarm) which effectively prefixes PeerID with multiaddr of one of public relays.

This makes Peers screen pretty dull, and `/p2p-circuit` does not even fit  on the screen, so user has a lot of weird  entries like this:

![2019-06-07--14-41-19](https://user-images.githubusercontent.com/157609/59105479-47f42c80-8934-11e9-8b1b-db0de23c50ff.png)

Based on my anecdotal observations, each Relay has 10+ nodes connected to it, so Relay ID is duplicated multiple times as it is the first part of Peer multiaddr.

**Describe the solution you'd like**

Not sure, we need to do more UX/design work here.
Some quick ideas:

- Minimal: we should at least have different icon to distinguish relayed nodes
- Better: find out `/ip4` of relay, and use its location
- Ideal: be smarter about the way Relayed nodes are listed, group all relayed peers under "parent entry", do not duplicate relay prefix etc

cc @ericronne

**Comment by olizilla** [comment]
More generally I think the peers UI needs a complete rethink to be more useful.

- What info is useful about a peer?
- What info is secondary

We could just list out truncated peerIDs, along with a flag, and perhaps some ledger info on how much bandwidth in/out you have had with the peer

|   PeerID  | Location | Connection | Latency | Notes |  More
| ---------|----------|-------------|--------|--------|----
|  `QmS2...8Cbt` | 🇬🇧 UK | ip4 |  n/a | Your peer | ...
|  `QmaC...uvuJ` | 🇺🇸  USA | ip4 | 980 ms | IPFS bootstrap node | ...
| `QmQV...hc6o` | 🌐 Unknown | ip4 | n/a  | Relay node | ...
| `QmSN...mBym` | 🌐 Unknown | p2p-circuit | 538ms |  via `QmQV...hc6o`  | ...

This info is available from `ipfs swarm peers --verbose` we just need to do upgrade how we handle p2p-circuit addrs as @lidel suggests.

Behind the more info we could show things like your share ration which we can get gtom  from `ipfs bitswap ledger <peerId>` now. we'd want to lazy load that, as it's a seperate call to the API per peer Id.

**Comment by JustMaier** [comment]
During our review call today, A few ideas came to mind:
- Sort peers by latency by default
- Using an [identicon](http://identicon.net/), it will make it easier to recognize peers

**Comment by olizilla** [comment]
Done in #1062
