### ISSUE TITLE
localhost:5001/webui not responding

### ISSUE THREAD

**Issue by oceanzhang01** [ipfs-shipyard/ipfs-webui#1059]
ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.5
11:22:59.100 ERROR    p2pnode: mdns error:  could not determine host IP addresses for DWDdeMacBook-Pro.local. discovery.go:46
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.97.79/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.97.79/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

localhost:5001/webui not responding
![image](https://user-images.githubusercontent.com/17286950/59170726-91ca5600-8b72-11e9-96e2-151eb4ec9072.png)
what wrong with it ?

**Comment by olizilla** [comment]
What happens from the command line? Are you able to run

```console
$ ipfs dag get QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub
```

Does it return some data as JSON?

**Comment by YAOAORAN** [comment]
I also have this problem.

**Comment by olizilla** [comment]
I'm gonna close this out. Please re-open if the problem persists.

**Comment by zemelLeong** [comment]
Same problem, and `ipfs dag get Qm...`  command not finished.
![image](https://user-images.githubusercontent.com/26835087/115519798-1da78000-a2bc-11eb-9a76-1ecdfb776d11.png)
![image](https://user-images.githubusercontent.com/26835087/115519948-3dd73f00-a2bc-11eb-87a8-7b0a6e9c0c2e.png)

**Comment by zemelLeong** [comment]
![image](https://user-images.githubusercontent.com/26835087/115520153-6f500a80-a2bc-11eb-9812-f49a8a85d333.png)
