### ISSUE TITLE
Simple Website Hosting and Integration

### ISSUE THREAD

**Issue by Incredible-BB** [ipfs-shipyard/ipfs-webui#1080]
We all agree IPFS is the future! I am a businessman i understand money and how to make it... I dont understand coding or terminal ANYTHING. So your platform here is spectacular!!

I would really like to see a tab added where we can easily created, publish, and EASILY update the content on our website directly though the app... Similar to this site. https://ipfscloud.store/app/build/

To add to this, being able to take files from a website builder that we can just pack all the assets into one folder and do a simple upload would also be amazing to have!!

Last note maybe not all that important but still nice for a non coder like me... if we could have a timer or some kind of display that shows the status of our uploads dispersion through the nodes to know when the contents will be usable would be cool.

Thank you so much for what you do! This is the beginning of a new era of real internet FREEDOM!!

**Comment by swedneck** [comment]
the linked website doesn't appear to have the intended contents anymore
