### ISSUE TITLE
Files/Explore: unrecognized node type when DAG is not unixfs

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1095]
##  Problem

https://github.com/ipfs-shipyard/ipfs-webui/pull/1027 introduced a clickable "Pins" counter on the "Files" screen. 

It works fine with empty/new node, but I found a bug that manifests against my pretty old repo which has over 800 pins.

@hacdias let me know if the error is not something  obvious, I can look at this closer and provide  more info if needed.

## Screenshots

> ![2019-08-13--14-28-03](https://user-images.githubusercontent.com/157609/62941627-ce1a6c80-bdd6-11e9-9976-3f2f7425dbc3.png)

>  ![2019-08-13--14-28-47](https://user-images.githubusercontent.com/157609/62941640-d377b700-bdd6-11e9-90ca-b7a5153d400f.png)

> ![ss-2019-08-14--13-04-28](https://user-images.githubusercontent.com/157609/63017684-45afd080-be97-11e9-8912-28a45c925fa1.png)

**Additional context**

go-ipfs v0.4.22, ipfs-webui 2.5.0

**Comment by hacdias** [comment]
@lidel thanks for reporting that! Never seen that error in my life. Can objects be symlinks? Can you try calling `ipfs.pin.ls()` on that repo just to see if it throws?

**Comment by lidel** [comment]
I think the problem is webui assumes every pin is unixfs (`dag-pb`  or `raw`).
What is missing is support for other DAG types. Those could be displayed in read-only mode (without filesystem operations such as copy to MFS etc)


I was able to figure out steps to reproduce:

1. `ipfs pin add --recursive=false bafyreiddymapg5zcpma3iu4wingqvois6jirucn5776wdsyg5f3f65v75a` (any `dag-cbor` node will do)
2. Open `pins` in Web UI
3. you should  get error like this:
   ![ss-2019-08-14--13-04-28](https://user-images.githubusercontent.com/157609/63016988-5a8b6480-be95-11e9-9ff5-c6a6fffd49e9.png)

**Comment by hacdias** [comment]
What if all non `unixfs` CIDs link to the Inspector instead of the file viewer? The file viewer is meant for stuff that supports `ipfs.files` API.

**Comment by lidel** [comment]
Navigating to _Explore_ screen sounds good. 
Also, non-unixfs pins should have a different icon (avoid things that look like a file, maybe a plain cube?)
