### ISSUE TITLE
The Config section in Settings should have a link to the documentation

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-webui#1110]
**Is your feature request related to a problem? Please describe.**

The Config section in Settings is JSON in a textarea with no hints or cues about what's possible to put there.

**Describe the solution you'd like**

As an easy fix to make things better, we can add a link to the documentation of the config options.

**Describe alternatives you've considered**

More sophisticated configuration UIs are discussed in #879 and ipfs/ipfs-gui#15.

But I think we'd need to link out to the docs either way.

**Additional context**

My name is Dietrich, and I like chicken burritos.

**Comment by autonome** [comment]
@hacdias wdyt about something like this? Ideally there's an icon or visual indicator that the link opens in a new tab, but at least we'd have something now.

<img width="1184" alt="Screen Shot 2019-08-15 at 6 08 04 PM" src="https://user-images.githubusercontent.com/50103/63136614-b0d8d000-bf87-11e9-8f38-1f38d2a36427.png">

This seems to be the best page I could find to link to: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md

Do you know of a better reference to link to?

**Comment by hacdias** [comment]
@autonome I just wouldn't agree with that color (maybe a teal would be better). 

Yes, that links seems the best one to me. I couldn't find any configuration-related info in docs.ipfs.io...
