### ISSUE TITLE
Feature request: Show IPFS version and IPNS link in the peer list table

### ISSUE THREAD

**Issue by andrasfuchs** [ipfs-shipyard/ipfs-webui#1117]
I use ipfs-desktop 0.8.0.0 (and go-ipfs 0.4.21) on Windows 10.

Could you add a new column to the peer list (on the peers page) with the IPFS version of the node?

Also, it would be great to have a link (instead of the current plain text) in the Peer ID column if that node have a published IPNS -> IPFS hash record. That link could open the Explore page with that particular IPNS/IPFS hash.

**Comment by jessicaschilling** [comment]
@lidel, quick feasibility check on this? It might be a good bounty candidate ...

**Comment by lidel** [comment]
Both are doable with existing APIs:

1. `AgentVersion` can be read via `ipfs id <PeerId>`
2. Doable, but may be a bit expensive, as it requires executing `ipfs name resolve -r <PeerId>` which may take time or timeout. 
   -  I am not sure how useful this would be, people often create separate libp2p-key for publishing website to IPNS (one per website). 
   - Perhaps if we add this, then people would have an incentive to publish  "About his peer" pages under PeerID key?

**Comment by jessicaschilling** [comment]
Closing this one in favor of general Peers page table enhancement in https://github.com/ipfs-shipyard/ipfs-webui/issues/1602.
