### ISSUE TITLE
Add a UX review step to release process

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#1129]
We've added significant new features to the webui (and desktop) and cranked out multiple releases, but we've not kept up with our ux reviewing and user testing: https://github.com/ipfs-shipyard/ipfs-webui/tree/master/docs/usability

We'll make better releases if we seek user feedback as part of the dev cycle. If we can't commit to doing it for every new feature, we should at least commit to doing as part of a release schedule. We can cut a pre-release that has the features in we'd like to get feedback on, then get a first round of UX feedback on the relase from at least @ericronne @cwaring and that @olizilla. Once we've resolved any UX issues that come up from that, we should update the user testing script and invite users to try out the new release to validate our assumptions about it and get more perspectives on it.

@ericronne what are your thoughts? Can you help us define a release process that includes user-testing?

**Comment by jessicaschilling** [comment]
Closing this one in light of our Q2 2020 focus on app family standardization ... anything we do will by default include user testing. 😊 Also of note: the docs team's work overall to get procedures in place for testing and validation. Intending to continue carrying that torch!
