### ISSUE TITLE
Typos in French Translation.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ipfs-shipyard/ipfs-webui#1137]
![Screenshot_20190831_181756](https://user-images.githubusercontent.com/13170204/64066567-5c825100-cc13-11e9-99fc-d54f7cbee7b1.png)
As you can see, at the Header text, It's written ¨Bienvenu¨ without the e at then end.

I’ve requested to rejoin the IPFS Transifex translation French team, but i’ve didn’t knew which one was really linked to the webui and, Entries were limited.

**Comment by PoorPocketsMcNewHold** [comment]
Come to think of it. It´s isn´t the only typo i´ve found, in this text only.
Here´s the following text corrected by me :
```
Bienvenue sur l'interface Web d'IPFS
Vérifiez le statut de votre nœud, son ID de pair et infos de connexion, le trafic réseau et nombre de pairs connectés.

Gérez les fichiers de votre dépôt IPFS facilement. Vous pouvez glisser et déposer pour ajouter des fichiers, les déplacer et renommer, les effacer, partager ou les télécharger.

Vous pouvez explorer les données IPLD qui sont à la base du fonctionnement d’IPFS.

Visualisez touts vos pairs connectés, géolocalisés par leur adresse IP.

Vérifiez les paramètres de votre nœud IPFS, et mettez-les à jour pour mieux correspondre à vos besoins.

Si vous voulez aider à faire avancer l'interface Web, vérifiez son code ou signalez un bug !
```
Bienvenu = Bienvenue It differs from the usage of [Bienvenu](https://en.wiktionary.org/wiki/bienvenu#French) which is an adjective used to someone or something being welcomed. (In that case, by using the word ¨welcomed¨ like : A welcomed IPFS user -> Un utilisateur d´IPFS bienvenu)
Noeuf = nœud Pretty self-explanatory, Written correctly a bit later on with the phrase ¨Vérifiez les paramètres de votre nœud IPFS [...]¨
tout = touts Using correctly the plural of [tout](https://fr.wiktionary.org/wiki/touts) because they are several ¨pairs¨.
mettez les = mettez-les Following the usage suggest by the new french ortograph reform of 1990.
bug! = bug ! In french, [It´s required to use a certain type of space to separate exclamation points for example.](https://fr.wikipedia.org/wiki/Espace_fine_ins%C3%A9cable)

**Comment by PoorPocketsMcNewHold** [comment]
![image](https://user-images.githubusercontent.com/13170204/64080107-4a261700-cce8-11e9-80b2-94aea4fc6adb.png)
ou vous n´êtes pas autoriser -> ou vous n´êtes pas autorisé 
Like used in the main header error text.

**Comment by hacdias** [comment]
Hey @PoorPocketsMcNewHold! Thanks for finding those typos. The right place to fix them is on Transifex as our translations are directly pulled from there!

> I’ve requested to rejoin the IPFS Transifex translation French team, but i’ve didn’t knew which one was really linked to the webui and, Entries were limited.

All the entries you've mentioned can be found on Transifex. Everything you mentioned is on the Web UI project, except the last error message which is in IPFS Desktop.

Please let me know if you have any issues accessing Transifex! It would be awesome to have these typos merged in!

**Comment by PoorPocketsMcNewHold** [comment]
I’ve been accepted, Everything should be fine, I’ve been already used to using Transifex, so this wouldn’t be an issue at all. Thanks! I will commit those fixes, and probably, those that I can found in the whole other projects (As thankfully, It seems to have a sufficient amount of text, enough for me to check them pretty easily.) surely in the next day, following this post as UTC+1 (Paris), so I’ll close this issue in advance, as neither it will be accepted or not, it as already been acknowledged, and that was mainly why I’ve reported it in the first place.

**Comment by hacdias** [comment]
Thanks!! :D
