### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by wolfired** [ipfs-shipyard/ipfs-webui#1194]
i use nginx reverse proxy with ssl for the ipfs webui, and bind a domain for it,

the ipfs conf:
"API": "/ip4/127.0.0.1/tcp/6501"
"Gateway": "/ip4/127.0.0.1/tcp/6502"

on the Files tab, i can not download any file, the download url like:
http://127.0.0.1:6502/ipfs/QmRtUpjjJh3WavoYTBPXS2r7hUZuwvYYc5VvFc96k79Q6x

how can i change the url to my domain form

**Comment by BunkerMelon** [comment]
Did you ever find out how to apply this @wolfired

**Comment by wolfired** [comment]
> Did you ever find out how to apply this @wolfired

no

**Comment by jessicaschilling** [comment]
Hi - suggest moving this discussion to the official forums at discuss.ipfs.io to improve community visibility? Thanks!
