### ISSUE TITLE
IPFS Desktop UI: Rename weird broken behavior

### ISSUE THREAD

**Issue by rslnx** [ipfs-shipyard/ipfs-webui#1215]
**Describe the bug**
When try to rename a file in Files UI after doing it with another file, the UI acts like you are trying to rename the file that you have renamed just before this. The file name field holds the old name of the previous file. And if user acts like not noticing this, something breaks in MFS and later attempts to rename this file fail. If you rename file A to C and then try to rename file B to D, the file name field will be showing name A, if now you cancel and close the dialog, and try renaming again, the name field will show the correct name B and the operation will succeed.

**To Reproduce**
1. Go to Files UI tab
2. Click on "..." menu button and choose rename for any file
3. Type a new name for the file and click Save
4. Click on "..." menu button and choose Rename for any other file or even for the same file
5. See the old name of the file just been renamed

**Expected behavior**
A name of the file being renamed to be shown. Rename to be successful.

**Screenshots**
![IPFS Desktop WebUI Rename Bug](https://user-images.githubusercontent.com/261885/65973083-61435a80-e488-11e9-9e54-6b93e0ea222e.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - IPFSDesktop: 0.9.4
 - WebUI: v2.5.4 Revision 5ece7e2

**Comment by hacdias** [comment]
Hey @rslnx! Thanks for reporting this. Will fix ASAP.
