### ISSUE TITLE
is webui upload  different with cli add?

### ISSUE THREAD

**Issue by irocnX** [ipfs-shipyard/ipfs-webui#1290]
hello,
I can list file (use : ipfs files ls -l ) that upload with webui to ipfs, but I use this command:
$>ipfs add upload_file
after upload complete, I can list this file use the same way, that is , ipfs files ls -l .
Why is that? anybody could explain it? Thanks!

**Comment by hacdias** [comment]
Hello @irocnX!

Yes, they are different commands and scopes. `ipfs files` API uses the underlying MFS (Mutable File System) technology where we have a "traditional" kind of filesystem with mutable data on the top of IPFS.

When you run `ipfs add` you're saying: add this file to the repository. With that command, it is _not_ added to the MFS. To add files to the MFS you should use `ipfs files write` or `ipfs files cp` for example.

I will leave here some links for information that might be useful for you:

- [Mutable File System Concept](https://docs.ipfs.io/guides/concepts/mfs/)
- [MFS ProtoSchool Tutorial](https://proto.school/#/mutable-file-system)
- [Regular Files API ProtoSchool Tutorial](https://proto.school/#/regular-files-api)
- [An issue about how `ipfs files write` might differ from `ipfs add`](https://github.com/ipfs-shipyard/ipfs-webui/issues/676)

I am closing this issue as it is not directly related to Web UI. However, feel free to ping me here for further clarifications!
