### ISSUE TITLE
Peers in v2.7.1  no longer get rendered on the map

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1313]
WebUI on the left: v2.6.0, right: v2.7.1
(tested in empty profile)

![2019-11-14--20-36-59](https://user-images.githubusercontent.com/157609/68890151-9e089f80-071e-11ea-88b7-9b6929b4cde1.png)

I see the same issue in Firefox 70 and Brave 0.70.104
Difference between versions is small ([diff](https://github.com/ipfs-shipyard/ipfs-webui/compare/v2.6.0..v2.7.1)), not sure what could cause this, looks like some async code failing silently.

No bandwidth to look into this, but some ideas:
- perhaps bumping `chart.js` to [v2.9.3](https://github.com/chartjs/Chart.js/releases/tag/v2.9.3) would help?
- code using `p-queue`?

**Comment by lidel** [comment]
@hacdias before digging into this, are you able to reproduce?

**Comment by hacdias** [comment]
It seems `ipfs-geoip` is failing with the newer `js-http-client` :'( I didn't dig much (will look tomorrow), but upgrading the version of the http client on the redux bundle seems to have broken this.

**Comment by hacdias** [comment]
@lidel just confirmed and there was a breaking change on v31.0 related to the output of `ipfs.object.get` and that's what's making this fail. On other news, I can't `npm install ipfs-geoip`. It just keeps failing and even [CI is failing](https://travis-ci.com/ipfs/ipfs-geoip/builds/131848582). I will try to get those dependencies updated.

**Comment by lidel** [comment]
@hacdias i see #69 is merged, what is the next step on the path to fixing this bug?

**Comment by hacdias** [comment]
@lidel a new release of `ipfs-geoip` with this change https://github.com/ipfs/ipfs-geoip/commit/37c69135be15ff9d6e31fb4b6cf3a68feccdb01d

**Comment by lidel** [comment]
@hacdias https://github.com/ipfs/ipfs-geoip/pull/69 seems to be merged, do you have permissions to publish new version of ipfs-geoip, or do we need to ping someone?

**Comment by hacdias** [comment]
@lidel we definitely need to ping someone: https://www.npmjs.com/package/ipfs-geoip

**Comment by daviddias** [comment]
Just gave you access, @hacdias & @lidel 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/1211152/69816217-dc5a9000-11ef-11ea-9c5e-30d9667d038b.png">

**Comment by hacdias** [comment]
Thank you!
