### ISSUE TITLE
Connection to local machine node

### ISSUE THREAD

**Issue by bouharb** [ipfs-shipyard/ipfs-webui#1318]
how you connect to the local node (local machine) of a user client ?
I need the exact location of the source code.

thank you in advance

**Comment by hacdias** [comment]
@bouharb curious about why you need to set the API address on the code itself?

> how you connect to the local node (local machine) of a user client ?

On the welcome screen (`/#/welcome`), you have the option to set the API address to connect to.

> I need the exact location of the source code.

You can set the `defaultApiAddress` to connect to here:

https://github.com/ipfs-shipyard/ipfs-webui/blob/0b5a73244faaa508de7a5a29c687cf69a9b56040/src/bundles/index.js#L31-L46
