### ISSUE TITLE
Feature: Accessible breadcrumbs

### ISSUE THREAD

**Issue by jaller94** [ipfs-shipyard/ipfs-webui#1350]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't click Breadcrumbs in Files with the middle mouse to open the link in a new tab.
The links are also missing right click, long touch options and keyboard accessibility, because the node only gets an `onclick` handler.

**Describe the solution you'd like**
The `href` attribute applied to both link tags in `Breadcrumbs.jsx`.
https://github.com/ipfs-shipyard/ipfs-webui/blob/216e574b92711b168953dd0ed566c48424d9320e/src/files/breadcrumbs/Breadcrumbs.js#L68-L70
https://github.com/ipfs-shipyard/ipfs-webui/blob/216e574b92711b168953dd0ed566c48424d9320e/src/files/breadcrumbs/Breadcrumbs.js#L88-L93

**Describe alternatives you've considered**
Technically there are no alternatives to provide full accessibility of links.
The best solution for a single-side webapp is to not have click listeners on links, but to listen for [`window.onhashchange`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange), then call `event.preventDefault` to stop the browser from navigating and process the new route with the internal router.

**Additional context**
There are more accessibility issues like this in most parts of the app.

**Comment by jessicaschilling** [comment]
Hi @jaller94 -- apologies for the delay in response, and thank you for your detailed and specific feedback. We have a larger accessibility meta-issue in https://github.com/ipfs/ipfs-gui/issues/28 in which we're gathering specifics for a more involved accessibility review, hopefully soon, so I've linked to your issue there as a point of reference.

For the sake of grouping similar topical issues in one place, I'll close this issue for now -- however, if you are at all inclined to make a PR on the suggestions you note above, that would be more than welcome! Thanks again.
