### ISSUE TITLE
Typo on Desktop UI

### ISSUE THREAD

**Issue by zakerytclarke** [ipfs-shipyard/ipfs-webui#1357]
I found a Typo on the windows version of the IPFS Desktop UI. Says "iles" when it should say "Files"
![typo](https://user-images.githubusercontent.com/30702789/70872371-e6f18500-1f64-11ea-911d-68df3b613c41.png)

I tried looking at transifex, but couldn't find an option to correct the English text.

Version: Revision c0cf2b8

**Comment by lidel** [comment]
Seems to be fixed in [v2.7.2](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.2)

For future reference: English is the source language, so you just submit a PR changing the string in this repo. Transifex is only used for translations.
