### ISSUE TITLE
drag and drop of files is broken on Mac 

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-webui#1367]
**Describe the bug**
Dropping a file on the Files page of webui when opened in IPFS Desktop fails with an error.

**To Reproduce**
1. Open the Files screen from the IPFS Desktop menubar application
2. Drag a file from Finder and drop it on the screen
3. See error in screenshot

**Expected behavior**
The file is added to IPFS and shows up in the Files list

**Screenshots**

<img width="477" alt="Screen Shot 2019-12-20 at 7 08 52 AM" src="https://user-images.githubusercontent.com/50103/71254113-f28fd380-22f7-11ea-96d7-8f85f032d25e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6 (18G1012)
 - Browser: Chrome (Electron)
 - IPFS Desktop: 0.10.2

**Additional context**

Console log:

TypeError: Cannot read property 'startsWith' of undefined
    at D (main.4e777785.chunk.js:1)
    at main.4e777785.chunk.js:1
    at l (5.efc4ede5.chunk.js:1)
    at Generator._invoke (5.efc4ede5.chunk.js:1)
    at Generator.S.forEach.e.<computed> [as next] (5.efc4ede5.chunk.js:1)
    at n (5.efc4ede5.chunk.js:1)
    at u (5.efc4ede5.chunk.js:1)

**Comment by lidel** [comment]
@autonome just to confirm it is limited to Electron runtime on Mac: do you get the same error when opening Web UI via IPFS Companion's browser action menu in regular Chromium-based browser? (Google Chrome or Brave)

**Comment by autonome** [comment]
Aha, reproduced on Chrome Canary.
