### ISSUE TITLE
Change save button contrast as global color edit

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1379]
(this may be subjective), but the "Save" button on "Settings" screen  in "active" state  (when config was changed but not saved yet) feels pretty "inactive":

![Screenshot_2020-01-27 Settings - IPFS](https://user-images.githubusercontent.com/157609/73174176-64cdb200-4107-11ea-8890-87c10f59fa33.png)

Ref. how similar problem was fixed in  https://github.com/ProtoSchool/protoschool.github.io/issues/317

**Comment by ericronne** [comment]
It's not your imagination @lidel. At about 1.9:1, the contrast ratio for the teal button label is way below the 4.5:1 standard. (Whereas the text on the gray button clocks in at an impressive 8.8:1)

**#378085** is one color that works

![x](https://user-images.githubusercontent.com/9259185/73184691-7c467400-40e2-11ea-8ebe-2dc8e5e98adf.png)

**Comment by lidel** [comment]
Thank you @ericronne! Do you think this color is generic enough to be added to [ipfs-css](https://github.com/ipfs-shipyard/ipfs-css) and used across our apps in cases like this, or should we punt this until we have time to refresh https://github.com/ipfs/ipfs-gui/blob/master/img/ipfs-ui-kit.png and see how the bigger picture looks like?

**Comment by ericronne** [comment]
I think it would be safe to globally swap in `#378085` for the `#3e9096` on the webui palette. Without actually trying it, it's tricky to know if there's a color combo in some distant corner of the UI will look a little off because of this. Seems like a pretty safe bet, tho.

![x](https://user-images.githubusercontent.com/9259185/73854721-8eb66100-47f8-11ea-904c-57ff51488ebf.png)

**Comment by jessicaschilling** [comment]
I'm going to change the color value in https://github.com/ipfs-shipyard/ipfs-css/pull/40 -- once that's merged, OK to update the button itself from `aqua` to `teal`.

**Comment by jessicaschilling** [comment]
ipfs-css has been updated to 1.0.0! Ready to integrate this change.
