### ISSUE TITLE
Support for custom API path

### ISSUE THREAD

**Issue by calikevuche** [ipfs-shipyard/ipfs-webui#1389]
Hi,

I have changed the location of the go-ipfs daemon. For example, this is what I get in the networks tab in browser when launching webui.

POST http://localhost:3000/api/v0/stats/bw?stream-channels=true net::ERR_CONNECTION_REFUSED

I would like to have the webui access a similar location, but with /v1/ instead of /v0/. Is there a away to change this to /v1/ in the ipfs-webui code, or otherwise, so that the webui can access the endpoint ?

**Comment by lidel** [comment]
FYSA when #1613 ships with v2.11, it will be possible to pass custom `apiPath` by defining API on Settings screen:

> ![](https://user-images.githubusercontent.com/157609/92586065-11733300-f296-11ea-8cb0-e217a676d633.png)
