### ISSUE TITLE
Gateway missing translations.json

### ISSUE THREAD

**Issue by ggarri** [ipfs-shipyard/ipfs-webui#1395]
- **Version**: 
js-ipfs version: 0.40.0-
Repo version: 7
System version: x64/linux
Node.js version: v11.15.0
- **Platform**: Linux  4.15.0-72-generic #81-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: webui

#### Description:

Gateway dashboard UI cannot be translated to other than English. Translation snippets appear to be requested but missing.

#### Steps to reproduce the error:

- Run ipfs daemon service
- Open in the browser the Gateway->settings
http://127.0.0.1:9090/ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip/#/settings
- In Language section click on "Change" and select for example "Spanish"
- Dashboard is partially translation (probably due to missing i18n snippets)
- On browser network tab you can see a 500 http error fetching 
http://127.0.0.1:9090/ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip/locales/es/translation.json
- The fact that `translation.json` is missing does not affect the actual partial internationalization of the UI

## Screenshot
![image](https://user-images.githubusercontent.com/2728080/71626188-33d38d80-2bec-11ea-8096-7b8f93fd4a5b.png)

**Comment by lidel** [comment]
Note to self: we don't use that file, but:
> i18next per default loads it translations from one file named `translation.json`
> https://www.i18next.com/principles/fallback

Changing the default namespace to `app` (`defaultNS: 'app'` in `init`) might remove unnecessary request.
