### ISSUE TITLE
cannot open IPFS DESKTOP on MAC

### ISSUE THREAD

**Issue by kidcdf** [ipfs-shipyard/ipfs-webui#1396]
![截屏2020-02-07下午6 50 57](https://user-images.githubusercontent.com/57767063/74023682-2ffd0d00-49db-11ea-8803-1ebcea30db66.png)

**Comment by kidcdf** [comment]
repo.lock: someone else has the lock,  can not run ipfs desktop.... help

*******************************************
OS: [macOS]
Version of IPFS Desktop [0.12.2]

2020-07-21T03:50:50.137Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.5.1
Repo version: 9
System version: amd64/darwin
Golang version: go1.13.10

Error: lock /Users/chendifeng/IPFS001/.ipfs/repo.lock: someone else has the lock

Command failed with exit code 1: /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --migrate --enable-gc --routing dhtclient
Error: lock /Users/chendifeng/IPFS001/.ipfs/repo.lock: someone else has the lock
Initializing daemon...
go-ipfs version: 0.5.1
Repo version: 9
System version: amd64/darwin
Golang version: go1.13.10

[config.txt](https://github.com/ipfs-shipyard/ipfs-webui/files/4951320/config.txt)
[error.log](https://github.com/ipfs-shipyard/ipfs-webui/files/4951324/error.log)

**Comment by rafaelramalho19** [comment]
Sorry for the late response, but this it not related with ipfs-webui. If this is still a problem please open the issue in ipfs-desktop.
