### ISSUE TITLE
Adding a folder to upload in files tab does not work

### ISSUE THREAD

**Issue by jonnybravocoder** [ipfs-shipyard/ipfs-webui#1398]
**Describe the bug**
In the ipfs desktop application, when attempting to add multiple files to ipfs by adding a directory, no files are added.  In fact, it looks like nothing is happening at all..

**To Reproduce**
I did you one better and recorded my screen and uploaded the video reproducing the error.  Take a look:
https://showmore.com/u/zq5yluv

**Expected behavior**
The files in the folder to be added to ipfs

**Screenshots**
Please watch video linked above.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro x64
 - Browser NA
 - Version 0.10.3

**Smartphone (please complete the following information):**
Using a Windows 10 computer

**Comment by ZhBoKn** [comment]
i have the same sitution but i have an idea about this issue. i use the webui to add the folder ,it isuccesses and i also can see it in my IPFS Desktop,i don't know how it works .

**Comment by lidel** [comment]
This should be fixed in [v2.11.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.0) and on https://webui.ipfs.io
