### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by MatthiasLohr** [ipfs-shipyard/ipfs-webui#1420]
Hey folks,

thanks for providing this software!

However, **the problem:** I think to spread IPFS, not only a GUI is helpful but also easy access to this GUI. Right now, I'm struggling with getting ipfs-webui installed - I'm not very experienced with node, so - even strictly following your (short) build instructions, I can't get it work. This might be a problem as its own, hower, for "just users" I think there is an easier solution:

**A possible solution** might be a Docker image. Lot of applications are available on Dockerhub, and for people just using software it is ways simpler to download a Docker image instead of getting into the application dependent runtime environment - as it is node in this project. Having a ready-to-use Docker image would help a lot, in my opinion. Clearly, we (I can support creating the image, if you like, but still, I'm not experienced with node applications) have to invest the work to write the Dockerfile, however, when it's done - it's done. Just create a automatic build job on Dockerhub for tags, and the image creation/uploading is running without further intervention.

What do you think about that?

Best regards
Matthias

**Comment by mnp** [comment]
@MatthiasLohr I was able to run the web UI and IPFS client both from docker container. Here's the short version for a Mac/Linux terminal:  
```
docker pull ipfs/go-ipfs
docker run -p 8080:8080 -p 5001:5001 -it ipfs/go-ipfs
```

That will run in the foreground in your terminal.  Then you can browse to http://localhost:5001/webui and have at it.  Press Ctrl-C to end the session.

Full details [here](https://hub.docker.com/r/ipfs/go-ipfs), see section **Running IPFS inside Docker** where they talk about running in the background and mounting volumes to persist changes.

**Comment by rafaelramalho19** [comment]
@jessicaschilling @lidel should we add a note somewhere in the readme for this?

**Comment by jessicaschilling** [comment]
Sure, want to add it? I can copy edit.

**Comment by rafaelramalho19** [comment]
Thank you @MatthiasLohr for rising the question and @mnp for answering.

Will add this to the readme section for help future folk 🙏
