### ISSUE TITLE
Files page displays 404 while ipfs files exist in console

### ISSUE THREAD

**Issue by nlko** [ipfs-shipyard/ipfs-webui#1422]
Hello, 

After some days and for no particular reason the "Files" page in ipfs-desktop (as well as the ipfs conpanion) displays a "/ 404" as breadcrumb and the file list remains empty.

It doesn't seem to be a problem with my ipfs repo since I'm able to properly perform files commands from the console:
- ipfs files ls
- ipfs files cat /some_file

I'm using the Revision 1eef40c version.

**To Reproduce**
No idea

**Expected behavior**
It should display files

**Screenshots**
![Captura de pantalla de 2020-03-30 11-01-21](https://user-images.githubusercontent.com/5183366/77895166-abaa6600-7276-11ea-82c1-53789ab69b42.png)

**Desktop (please complete the following information):**
 - Ubuntu 16.04
 - Chrome
 - Version 80.0.3987.149 (Build oficial) (64 bits)

**Comment by nlko** [comment]
Apparently I was wrong when I said that the repo ipfs was correct.

While `ipfs files ls` works fine `ipfs files ls -l` hangs.

For one particular file I'm unable to retrieve its cid.

This is rather an IPFS problem and it has nothing to do with the webui. 

For information, I was able to recover all my files except the bad one and recreate a clean repo.

Still, in the webui, I was left with no clue about what was going on.

I think this issue could be closed if it's not possible to display a better information on the error than the 404 message.

Anyway, thank you for the webui (ipfs-desktop), I use it everyday.

**Comment by jessicaschilling** [comment]
@nlko Thanks for the kind words!

@hacdias @olizilla If it's possible to provide more granular guidance than just a generic 404 message, let's circle; I'd be happy to iterate on some possible message text.

**Comment by lidel** [comment]
:+1: for improving the 404 "Not found" state

It should be more prominent, and also more explicit: 
- should show what resource was not found (with full content path)

As a data point, user report copied from https://github.com/ipfs/go-ipfs/issues/7604: 

> Hello, at first my ipfs can import, but after some uploads it turns to /404 and no import button anymore, anyone experiencing the problem?
> ![ScreenShot_20200818210837](https://user-images.githubusercontent.com/19401967/90523414-0ba69800-e197-11ea-8669-b3df5a052165.png)

Right now user is unable to tell what went wrong and why "404" is displayed. 
If a full content path (either MFS, `/ipfs/` or `/ipns` that was not found was displayed, then it would be much easier to  self-service.
