### ISSUE TITLE
PDF viewer doesn't scale to page

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/ipfs-webui#1434]
**Describe the bug**
PDF Viewer doesn't scale to page.

**Screenshots**

![image](https://user-images.githubusercontent.com/138401/78977381-e610d000-7acc-11ea-830d-f9d8286e159d.png)

**Desktop (please complete the following information):**
 - OS: osx 
 - Browser: chrome
 - Version:  Version 80.0.3987.149 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by jessicaschilling** [comment]
Possibly related: https://github.com/ipfs-shipyard/ipld-explorer/issues/53
