### ISSUE TITLE
"+ Add > Folder" button doesn't do anything after selection

### ISSUE THREAD

**Issue by samuela** [ipfs-shipyard/ipfs-webui#1437]
**Describe the bug**
Just downloaded and installed the desktop client for macOS via brew. I tried adding a folder with the add button. It opens up the system selector dialog, I select a folder but then nothing happens...

**To Reproduce**
1. Go to Files view.
2. Click on "+ Add"
3. Select folder. 
4. Nothing happens.

**Expected behavior**
Something to happen... 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser n/a
 - Version https://github.com/ipfs-shipyard/ipfs-webui/commit/1eef40c

**Additional context**
n/a

**Comment by lidel** [comment]
I believe this was fixed in 2.11.x and is available at https://webui.ipfs.io and will be released with ipfs-desktop 0.13. 
Feel free to reopen if it still occurs after update to mentioned versions.
