### ISSUE TITLE
A 'Publish Website' option in the webui control panel

### ISSUE THREAD

**Issue by danrobi11** [ipfs-shipyard/ipfs-webui#1441]
Hello
Im suggesting same sort of 'Publish Website' feature like OnionShare.
In the GO-IPFS webui control panel drag/drop/add dir/file in the 'Publish Website' section. That creates automatically a persistent address. Done.
Note: enable/disable DHT option would be useful as well
Thanks!

**Comment by danrobi11** [comment]
https://github.com/ipfs/go-ipfs/issues/7175

**Comment by jessicaschilling** [comment]
Hi @danrobi11 -- thank you for the feedback! We're actually already discussing best strategies for incorporating the ability to publish static websites from WebUI and Desktop in https://github.com/ipfs/ipfs-gui/issues/77, so I'll close this issue in favor of that one.

That said, in the meantime you might be interested in this:
https://github.com/ipfs-shipyard/ipfs-deploy

Thanks again!
