### ISSUE TITLE
IPFessay in the webui 

### ISSUE THREAD

**Issue by danrobi11** [ipfs-shipyard/ipfs-webui#1453]
I discovered IPFessay from: https://github.com/pinnaculum/galacteek
Related to this: https://github.com/ipfs-shipyard/ipfs-webui/issues/1441
I havent found IPFessay in the IPFS-GO desktop webui :(
Implementing the IPFessay in a 'Publish Website' section would be a very useful and user-friendly way for the new comers non-technical IPFS users to create and publish their website.
I really hope this will be considered. Thanks!

**Comment by jessicaschilling** [comment]
Thanks, @danrobi11! As we mentioned in #1441, we're discussing best strategies for incorporating the ability to publish static websites from WebUI and Desktop in ipfs/ipfs-gui#77, so I'll close this issue in favor of that one. Appreciate the contextual info as we continue to discuss!
