### ISSUE TITLE
Connection Status Help text Highlighted area is overlapping with a second Icon

### ISSUE THREAD

**Issue by davenes8148** [ipfs-shipyard/ipfs-webui#1459]
**Describe the bug**
On the Connection Status help text the highlighted area partially displays a second Icon 

**To Reproduce**
1. Go to the Status page
2. Click on the Help Text icon
3. Click Next to page 2 
4. View the highlighted area

**Expected behavior**
The highlighted area could be a little smaller so it's only showing the Connection Status Icon and not partially showing the Help Text Icon 

**Screenshots**
![image](https://user-images.githubusercontent.com/64146127/80100466-e9459a80-8567-11ea-944f-585d27ddf009.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Laptop)

**Comment by jessicaschilling** [comment]
Hi @davenes8148 -- I spent some time digging into this today. We use [React Joyride](https://docs.react-joyride.com/) to manage the tours, and while it's extremely flexible in terms of creating tours that work well for all lengths of languages (for example), it does include some preset parameters, like the margin/padding on the "spotlights" like the one you're pointing out here.

It's possible to manually override the spotlight margin/padding for a single object, like the status icon here, but it's kind of a hacky and brittle way to address something that has a fairly small benefit for the user. Here's a blog post talking about another platform's attempts to thoroughly customize React Joyride along similar lines, but ultimately deciding "perfection is brittle": https://blog.talla.com/why-talla-hacked-our-own-oonboarding-joyride-framework-to-be-less-precise-then-gave-it-up-entirely

I've also got perfectionist tendencies 😊, but am suggesting that in this instance, it isn't worth the amount of manual overriding necessary in the face of long-term code robustness. I'm going to close this issue, but if anyone would like to discuss further, please comment or re-open as necessary. Thank you!
