### ISSUE TITLE
Repurpose "no files" Files screen content as first-launch or help material

### ISSUE THREAD

**Issue by davenes8148** [ipfs-shipyard/ipfs-webui#1463]
**Describe the bug**
**Enhancement recommendation***
From a user experience aspect, the below image (welcome information) would be good as a landing page for the app rather than seeing it after clicking onto a menu option. 

**To Reproduce**
1. Go to the Files page
2. View the Information that's displayed on the initial page

**Expected behavior**
This information is really useful and is lost once you upload a file. If this information was the landing page for the app then it wouldn't be lost and would be in a more useful position 

**Screenshots**
![image](https://user-images.githubusercontent.com/64146127/80216639-4871e080-8636-11ea-81fc-af5e0019308e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Laptop)

**Comment by jessicaschilling** [comment]
Hi @davenes8148 -- this is great feedback. Thanks!

Right now that material appears if the user doesn't have any files uploaded (as you noticed), but you're right: It's more general information than files-specific info, and would be a lot more useful as welcome/introductory content, either at first launch or as help tour content. 

Slotting this into our queue of UX examples for further prioritization and concept work. If anyone's reading who would be interested in contributing, this is more than welcome!

**Comment by jessicaschilling** [comment]
Let's also roll the suggestion from https://github.com/ipfs-shipyard/ipfs-webui/issues/1406 into this effort: incorporating some kind of prominent link to Awesome IPFS as an example of cool things new users can be inspired by.

**Comment by jessicaschilling** [comment]
Update: I'll chip away at this one -- would be great to get some starter explanatory content into the version of Web UI/Desktop that ships with pinning service integration.
