### ISSUE TITLE
Line-wrap hover text on extremely long file/folder names

### ISSUE THREAD

**Issue by davenes8148** [ipfs-shipyard/ipfs-webui#1464]
**Describe the bug**
Within the Files Section, The New folder naming field doesn’t seem to have a character limit, I was able to add in a huge number and it didn’t display well after saving (I assume the blue highlight should display it in its entirety if its too big if so it should be wrapped)

**To Reproduce**
1. Go to Files
2. Click on +Add
3. Select Create a new folder
4. Enter a very large string of numbers and letters 

**Expected behavior**
Navy blue hover should line-wrap in order to display the full file/folder name.

**Screenshots**
![image](https://user-images.githubusercontent.com/64146127/80220100-43fbf680-863b-11ea-8378-c84c0ed58a96.png)
![image](https://user-images.githubusercontent.com/64146127/80220116-49f1d780-863b-11ea-96d3-8c5399e49f53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Laptop)

**Comment by jessicaschilling** [comment]
Hi @davenes8148 - thanks for finding this one! We don't really want to place an arbitrary limit on the lengths of the names of files or folders, but what that DOES mean (as you found) is that we're not doing a great job of exposing the full name of a thing once it gets into the files list screen.

Let's use this issue to make the dark-blue hover text line-wrap so we know it displays the entire contents of the file name. I'll amend your original bug report accordingly.

Thanks again!

**Comment by jessicaschilling** [comment]
Confirmation that this displays the same way on Mac (Catalina). FWIW, the end of the name displays; it's the front that falls off.
<img width="1544" alt="Screen Shot 2020-04-24 at 2 01 18 p" src="https://user-images.githubusercontent.com/1507828/80252204-1a8b9c80-8634-11ea-86a7-6ff32763d7b2.png">

**Comment by kartezjusz** [comment]
CZYTAJ OPIS ZANIM BĘDZIE ZA PÓŹNO-
porównaj numery z tego opisu z numerami z ogłoszeń
Piotra Piasty Wrocław PIOTR WALDEMAR PIASTA „DIGITAL SYSTEMS” Wrocław al. Poprzeczna 66/6 ul / al Manganowa 27/7 (7/27 na przemiennie) dane z CEIDG NIP-8951647389 kryptokoparki24.pl Telefony: 600465412, 796745805, 574517679, 796051081, 574143177, 576904953, ksywy= Kartezjusz Kowalski, Peter Kowalski, Piotr Kowalski, Piotr Nowak. meile jakich urzywa walt666 kartysim1 kartysim2 mbtpozew  loginy: walt666, WUPE Właściciel stron sprawdz-numerek.pl, czyjnumerek.pl i wszyscy ci na których są opinie na temat jego tematu.
Odradzam jak w celach zleceniobiorców i sprzedawców, chyba ze chce się wzbogacić o stalking internetowy.


Pan gotów jest sam zrujnować osobę, instytucję oraz wykonana prace, nie przestrzegać żadnych zasad etycznych, handlowych  czy zaleceń eksploatacyjnych jako klient a potem nie da wam żyć i wykorzystując KONTAKTY u administratorów stron internetowych (allegro,oferia,youtube) i znajomości w branży IT i mając parę stron internetowych w tym sprawdz-numerek.pl i czyjnumerek.pl na fałszywe pozytywne opinie pisane przez siebie, fałszywe dane oraz zagraniczne serwery będzie uporczywie nękał i szkalował w internecie Was, Wasze firmy, rodziny i dzieci, dzwonił nocami z prywatnego, latał dornem pod domem robiąc zdjęcia, wstawiał przez boty setki negatywnych opinii, kręcił filmy z ukrycia i publikował je w internecie, wstawianie numerów telefonu w anonse erotyczne, rejestrowanie waszych adresów meilowych na portalach zagranicznych śmieciowych, wysyłanie na meila wirusów,linków z wtyczkami aby się dostać do danych z komputerów jak i telefonów, wysyłanie listów,kurierów, sms stosował szantaż i wszelkie krętackie metody by zmęczyć was psychicznie, bo na rozstrzyganie spraw w sadzie lub inny cywilizowany sposób jest za cienki. Gość to materiał i dla prokuratora i dla dziennikarza i psychiatry (ale od tego ostatniego to ma klinikę zony Moniki)


A tak Wygląda, to jego aktualne zdjęcie z lokalnego przewodnika google(należny skopiować link i wkleić do przeglądarki): images.app.goo.gl/xDnHHR3AfKHcDosE7
Poszukuje osób które w ten sam sposób są nękane lub poszkodowane (temat pobierania pieniedzy za rejestracje kart i nie wysylanie towaru) prosze o kontakt: pozew_na_kartezjusza@o2.pl
Pomoc prawna bezpłatna.
