### ISSUE TITLE
Invalid language labels in Language picker 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1471]
For some reason `Settings` → Language → Change  has English multiple times:

> ![](https://user-images.githubusercontent.com/157609/80379455-693c6f00-889e-11ea-8e59-819777ff5dff.png)

Looks like a bug.

**Comment by jessicaschilling** [comment]
If you choose the second instance of "English", it actually switches to Italian.

**Comment by jessicaschilling** [comment]
Please see https://github.com/ipfs-shipyard/ipfs-webui/pull/1483.
