### ISSUE TITLE
Inspect view: "View on IPFS Gateway" still points to the ip-address, not to .localhost

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-shipyard/ipfs-webui#1490]
**Describe the bug**
On the inspect view there's a button labled with "View on IPFS Gateway", which still points (in my case) to `127.0.0.1/ipfs/<CID>` instead of `<CID>.ipfs.localhost`.

**Screenshots**
![Screenshot_20200510_162131-1](https://user-images.githubusercontent.com/614929/81501899-0229ac00-92db-11ea-9e5d-493da11cb7c3.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave

**Comment by jessicaschilling** [comment]
@lidel and/or @rafaelramalho19 -- can you please have a look? Thank you!

**Comment by rafaelramalho19** [comment]
I was able to replicate it 👍 

Thank you for reporting this Ruben, I will check it out.

**Comment by lidel** [comment]
@rafaelramalho19 After additional analysis I am afraid we need to revert #1559 – it won't work in offline contexts and private swarms.

We also can't assume localhost subdomains are enabled and work everywhere, so additional heuristic should be added in the place where `gatewayUrl` is read from node's config:

- If gateway is `127.0.0.1:port` 
   - send HEAD request for `bafybeiczsscdsbs7ffqz55asqdf3smv6klcw3gofszvwlyarci47bgf354.ipfs.localhost:port` (empty unixfs dir)
     - If response in HTTP 200, then subdomains work in current browser
       - replace `127.0.0.1:port` with `localhost:port` in "View on IPFS Gateway" 

How does that sound?
