### ISSUE TITLE
Files screen content only semi-functional with a screen reader

### ISSUE THREAD

**Issue by marrie** [ipfs-shipyard/ipfs-webui#1498]
**Describe the bug**

I'm visually impaired, so need to access the destkop app with  a screenreader called voiceover  in the case of mac os. You will need to hit command plus f5 to access voiceover from anywhere.
**To Reproduce**
1. launch voiceover
2. launch the ipfs app
3. click the status menu, or what they I think call the extras menu, the thign where all the icons for dropbox and yoru time are.
4. click files
5. try and use voiceover only to access the files area. . do not use a moniter.
**Expected behavior**
I should be able to navigate all controls using the curser and arrow keys.
**Screenshots**

**Desktop (please complete the following information):**

mac os 10.15  ips Revision 1b58b62
**Smartphone (please complete the following information):**

**Additional context**
 If you need a demo  of how voiceover works, please let me know.

**Comment by autonome** [comment]
Thanks for reporting @marrie! @rafaelramalho19 and @jessicaschilling will look at this, but Monday is a holiday in US so possibly not until Tues.

**Comment by marrie** [comment]
Lol. Take your time. I'm in the US but I work on Monday, If you have any 
questions, please ask. I also found out that I cannot delete files. I 
can arrow up and down kind of and see the selected status, but the 
buttons for rename and delete get skipped over if I tab and if I curser  
over them with control open left and right, I can get to them but 
pressing control, option, space does not a thing.

Thanks, and hope all of this can be looked into.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 — can you please take a look at this when you are back! I’m afraid that this is outside my area of expertise. Thank you!

**Comment by rafaelramalho19** [comment]
Yes, I love fixing accessibility issues 😄 

Thanks for reporting this @marrie, I will look at this soon.

**Comment by rafaelramalho19** [comment]
@marrie Thank you once again for reporting this.

I've gone ahead and created a pull request to fix this. I would very much appreciate your input in this if that's possible!

**Comment by marrie** [comment]
I can't code.  What would you like me to test? Or how would you like me 
to go about this. I'll do my 100 percent best. I have some blind friends 
on windows. Would you like me to try and link them to you guys for 
testing purposes?

**Comment by rafaelramalho19** [comment]
@marrie this should be in the next release of ipfs-desktop, so if you could wait for that and then provide feedback to us, it would be awesome!

You're always welcome to open issues with problems you may encounter with ipfs-desktop and webui, as it's really valuable for us the input of someone who uses screen readers daily. 

If you're really eager to test this out, we can also create a demo instance of webui with these changes 😄

**Comment by marrie** [comment]
Thanks. I'm not new to testing, but I cannot compile either. I'll let my 
VI people know on my discord what's up and hopefully you should get some 
to test, maybe some to code if they know what they are doing.

Thanks again.

**Comment by rafaelramalho19** [comment]
That's awesome! Thank you so much @marrie!
