### ISSUE TITLE
Pinning integration: Solve for "pins" item in File screen info bar

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-webui#1505]
_Note: This issue is part of a larger [pinning service integration epic](https://github.com/ipfs/ipfs-gui/issues/91) undertaken spring/summer 2020._

### In brief
Once pinning services are better integrated into Web UI, the "pins" item in the File screen info bar will benefit considerably from refining — either adding additional explanatory context, or repurposing altogether.

![image](https://user-images.githubusercontent.com/1507828/83183890-db92b000-a0e5-11ea-8cc8-94e666f11809.png)

- [x] Discuss best-case UX for this info bar once pinning services have been added
- [x] Determine functional requirements
- [x] Draw up, discuss and agree upon UI instantiation
- [ ] Implement as a PR to close this issue, or if it's a substantial enough effort, open and resolve a new issue for implementation

This isn't critical work for MVP release, but is high on a nice-to-have list.

**Comment by jessicaschilling** [comment]
@lidel -- I assume there isn't any reasonably efficient way to actually display the file/folder _names_ in the Pins screen that appears when someone clicks that "pins" link?

If there isn't, I wonder if as first step we actually just remove that link entirely (still displaying the number of pins, just removing the link). If Web UI/Desktop is effectively acting as a file browser in the Files screen (and the similar Pins screen), withholding the name of the files removes what's really the primary use case.

**Comment by lidel** [comment]
>  I assume there isn't any reasonably efficient way to actually display the file/folder names in the Pins screen that appears when someone clicks that "pins" link?

No way atm. We dont store any labels/names within current pinning API in go-ipfs. 
(The "new pinning service API" _may_ include additional metadata, including filenames, but it does not exist in go-ipfs yet) 

- I'd vote for removing "pins" item from info bar (we can reconsider when/if a better API for managing pins lands in go-ipfs)
- (optional/nice to haves) tweak the info bar to show stats about current directory, making it more useful 
  - make it clear stats are about current directory (size, file/dir count)
  - when I am in root, it shows size of all files
   - if i open a subdir, it shows how big current dir is (+perhaps what party of total storage it takes?)

**Comment by jessicaschilling** [comment]
Like so? (Current is on top, idea for viewing a subdirectory is on bottom.)
![image](https://user-images.githubusercontent.com/1507828/83463990-d35fab00-a42c-11ea-9d76-be27594e1d56.png)
Note two things:
- "Files" here isn't clickable; user can get there from breadcrumbs that already live directly to the left, and there doesn't seem to be much point in just offering a link to top-level directory anyway
- We'd have to decide if we wanted to keep the "XGB/YGB" visual dichotomy for the top level, or just get rid of everything after the slash for that highest level directory. (Pros to keeping it: consistency; cons: repetition.)

**Comment by jessicaschilling** [comment]
Per conversation with @rafaelramalho19 and @lidel:
- Remove middle "blocks" area
- Rename "repo" to "all blocks"
- For top-level directory, keep the smaller gray text "/xxxMB"

Like so:
![image](https://user-images.githubusercontent.com/1507828/83540988-46f9ca80-a4b6-11ea-9cf0-32633d8c465a.png)

@rafaelramalho19, please let me know if you need anything else from me -- note that the subtitles ("files", "all files") are slightly smaller in this version than existing (2px smaller) and the same size text as the gray "/xxxMB" text.
