### ISSUE TITLE
Test failure after updating the webui in go-ipfs

### ISSUE THREAD

**Issue by Stebalien** [ipfs-shipyard/ipfs-webui#1507]
https://app.circleci.com/pipelines/github/ipfs/go-ipfs/2904/workflows/5d0350b1-c52d-4cb2-acc0-12e4139a17f6/jobs/34235

**Comment by lidel** [comment]
Seems CircleCI got slower than the usual.
Re-running made the build green again. To avoid problems in the futuree I increased timeout in  #1518
