### ISSUE TITLE
Improve file add so it can handle gigs of data

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/ipfs-webui#1529]
This is related to https://github.com/ipfs/js-ipfs/issues/3029, however changes on the webui end would also be required. So this is the placeholder issue for that piece of work.

**Comment by Gozala** [comment]
I don't seem to have right privileges to assign it to myself. But I do intend to drive this.

**Comment by jessicaschilling** [comment]
@Gozala I assigned you! Do you mind adding labels as appropriate?

**Comment by Gozala** [comment]
Some notes (mostly for myself). Here's where dropped files are handled

https://github.com/ipfs-shipyard/ipfs-webui/blob/be316e50353d378778a610958af6643ff835946a/src/App.js#L109-L116

Which invokes `addFiles`

https://github.com/ipfs-shipyard/ipfs-webui/blob/be316e50353d378778a610958af6643ff835946a/src/App.js#L42-L53

Where array of web [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File)s is converted to array of entries with `content` feilds are turned into streams of file contents. (This where we fall of optimal path and will end up having to buffer). 

https://github.com/ipfs-shipyard/ipfs-webui/blob/be316e50353d378778a610958af6643ff835946a/src/lib/files.js#L4-L18

And then `doFilesWrite` uses `ipfs.add` to get those into IPFS via `ipfs-http-client`

https://github.com/ipfs-shipyard/ipfs-webui/blob/be316e50353d378778a610958af6643ff835946a/src/bundles/files/actions.js#L170-L207

**Comment by Gozala** [comment]
> @Gozala I assigned you! Do you mind adding labels as appropriate?

@jessicaschilling I'm afraid I don't have access right to do that either. Also I'd need some guidance on appropriate labeling.
