### ISSUE TITLE
Files: bogus link in onboarding materials

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1530]
## Bug

When user opens Files screen and there are no files, onboarding materials are displayed.

Clicking on the link to "manage files"  does nothing, because user is already on "Files" screen.

![useless-self-link-2020-06-25--22-38-11](https://user-images.githubusercontent.com/157609/85793108-cafd4600-b734-11ea-9ba3-30dee849d50b.png)

## Ways to fix?

Quick fix is to remove the link, and update text to highlight that user is on the Files screen already.

It could be a good opportunity to audit/update these onboarding materials too (right now visible only when user has no files).

**Comment by jessicaschilling** [comment]
@lidel Can we just remove the link for now? We've got a handful of other open issues revolving around reworking the "no files here yet" page and moving some of its content into a proper welcome page.

**Comment by jessicaschilling** [comment]
We could also replace "you can drag and drop" with "Drag and drop here ..." to make it clear that this is where you can put the files. (If that is indeed true when there aren't any files?)

**Comment by lidel** [comment]
I agree with both comments :+1:  (Yes, user can drag&drop anywhere and it will work)

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1531 fixes this.
