### ISSUE TITLE
Can't add direct connection with QUIC

### ISSUE THREAD

**Issue by AuHau** [ipfs-shipyard/ipfs-webui#1533]
**Describe the bug**
When I want to add new direct connection I am not allowed as the validation of the multiaddr most probably fails for the addresses like:
`/ip4/127.0.0.1/udp/4002/quic/p2p/QmcfHY1GP8vsEjj9ahYD3e6K57SdHHkCqw1PP1fgL8CF7G`

**To Reproduce**
1. Go to 'Peers'
2. Click on 'Add connection'
3. Enter address '/ip4/127.0.0.1/udp/4002/quic/p2p/QmcfHY1GP8vsEjj9ahYD3e6K57SdHHkCqw1PP1fgL8CF7G'
4. Add button is not active even though it is valid address.

**Expected behavior**
Enabled "Add" button for addresses like `/ip4/127.0.0.1/udp/4002/quic/p2p/QmcfHY1GP8vsEjj9ahYD3e6K57SdHHkCqw1PP1fgL8CF7G`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version

**Additional context**

**Comment by jessicaschilling** [comment]
Closing this in favor of the newer #1674, but referencing it there.
