### ISSUE TITLE
chrome: NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-webui#1542]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.webui.ipfs.io/

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/167966/87032028-8d111f00-c216-11ea-9bfa-409126541043.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 1909

![image](https://user-images.githubusercontent.com/167966/87032069-9ac6a480-c216-11ea-8ae9-2db0b8bc6b1d.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rafaelramalho19** [comment]
Thank you for reporting this. We're already finding the causes of the issue and will update this soon.

**Comment by rafaelramalho19** [comment]
This has been fixed, sorry for the delayed response 😄
