### ISSUE TITLE
Map view takes up too much vertical space - pushes peer list too far down on smaller screens

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-webui#1561]
**Describe the bug**

Map view takes up too much vertical space - pushes peer list too far down on smaller screens, see attached screenshot.

**To Reproduce**

Open webui on smaller laptop screen, go to Peers page.

**Expected behavior**

The map view should only take % of screen vertical size so that peer list is visible.

**Screenshots**

<img width="1042" alt="Screen Shot 2020-07-25 at 1 08 28 PM" src="https://user-images.githubusercontent.com/50103/88464445-bec9ed00-ce88-11ea-8c67-d57652b4810c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: webui from IPFS Desktop
 - Version: IPFS Desktop 0.12.2

**Comment by jessicaschilling** [comment]
@rafaelramalho19, do you have the bandwidth to troubleshoot this? If not I can have a go, but you'll be quicker 😊

**Comment by rafaelramalho19** [comment]
@jessicaschilling I think you can go for it, it's actually faster if you implement it rather than me bothering you for feedback 😄

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1566 addresses this, with some caveats.
