### ISSUE TITLE
Publish a IPNS for Lastest Version

### ISSUE THREAD

**Issue by akimoto72738** [ipfs-shipyard/ipfs-webui#1562]
Hi Teams,

May be you can Publish a IPNS for lastest version every time so that users always received lastest webui as soon as your update

In my environment, I publish a IPNS for [bafybeihpetclqvwb4qnmumvcn7nh4pxrtugrlpw4jgjpqicdxsv7opdm6e](Webui 2.10.2) after your released

Now I just use IPNS to keep up with your latest version, and I don't need to change the address(ipfs hash) in the browser

![捕获](https://user-images.githubusercontent.com/67720156/88500717-1046b900-cffc-11ea-8067-e5eaf04a2de5.JPG)

**Comment by rafaelramalho19** [comment]
Thank you for the suggestion @akimoto72738, it's a really nice idea!

I believe this can be problematic because ipfs-desktop needs to always have a certain ipfs-webui version that is compatible with it due to API requirements (available though window.ipfsDesktop)

But this could be a possibility for go-ipfs, right @lidel ?

**Comment by lidel** [comment]
We already provide DNSLink for the latest release: 
- Users who want to use the latest Web UI can load `https://webui.ipfs.io`  or `http://webui.ipfs.io.ipns.localhost:8080`
- You can also opt-in for that via IPFS companion browser extension UI: https://github.com/ipfs-shipyard/ipfs-companion/pull/893
  > ![2020-06-13--17-30-34](https://user-images.githubusercontent.com/157609/84572626-a51e8b80-ad9b-11ea-888a-55e4e5fb1e7b.png)


----

@akimoto72738 I understand you prefer IPNS to remove reliance on DNS, increase security, or is proper DNSLink resolution blocked in your country?


IPNS could be added to [ipfs-github-action](https://github.com/ipfs-shipyard/ipfs-github-action) – filled https://github.com/ipfs-shipyard/ipfs-github-action/issues/4 to track that.

**Comment by olizilla** [comment]
The webui.ipfs.io dnslink is for exactly that purpose! go-ipfs and js-ipfs redirect /webui to a specific ipfs CID to ensure that you always get a webui that has been tested with the version of the ipfs daemon you are running. But if you want to always use the latest, then webui.ipfs.io is there _for experts only_

**Comment by akimoto72738** [comment]
Hi Teams,

Thank you for reply.

https://webui.ipfs.io is not be blocked in my country but its high latency,so I prefer ipns or cid to access webui in the local lan（faster、security、anti-blocked、personalized and probably anonymity）

Maybe it's a personal opinion，your make the decision.

**Comment by lidel** [comment]
@akimoto72738  Is the latency problem coming from public gateway? Are you using IPFS Companion?
http://webui.ipfs.io.ipns.localhost:8080/ should instantly load from local gateway, unsure where your latency comes from.

**Comment by akimoto72738** [comment]
@lidel 
Yes, The latency comes from public gateway.

Here is the ping result:

> 正在 Ping webui.ipfs.io [209.94.78.1] 具有 32 字节的数据:
> 来自 209.94.78.1 的回复: 字节=32 时间=276ms TTL=50
> 来自 209.94.78.1 的回复: 字节=32 时间=276ms TTL=50
> 来自 209.94.78.1 的回复: 字节=32 时间=276ms TTL=50
> 来自 209.94.78.1 的回复: 字节=32 时间=276ms TTL=50
> 209.94.78.1 的 Ping 统计信息:
>     数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
> 往返行程的估计时间(以毫秒为单位):
>     最短 = 276ms，最长 = 276ms，平均 = 276ms

I'm not using IPFS Companion and (webui.ipfs.io.ipns.localhost）is not worked in my environment，maybe i need create a dns record but this is not problem because I can load webui from local gateway by ipns or cid with my custom domain name

Different from the others, topology is below
 
> ![ipfs](https://user-images.githubusercontent.com/67720156/89488938-dfc10500-d7db-11ea-905b-f4b30f198166.jpg)
 
Then I can access ipfs webui in browser from my desktop、laptop、phone、pad...etc

The only problem is that I must publish ipns or change cid manually to keep up with you latest version after your update everytime.

if your publish a ipns,that will be look like more automatic and Silently (update).

Thanks, hope my English can express accurately

**Comment by lidel** [comment]
@akimoto72738 thank you for elaborating on your setup, it is pretty custom, but I can understand some of the choices you made.

I understand that the main pain point for you is the need for manual updating of `TXT` record for `mycustomdomain` that you use for opening webui in your local network. While IPNS is one way to solve it, I think there is an easier way that you can try today.

I believe `TXT` record for `mycustomdomain`  is `dnslink=/ipfs/bafybeihpetclqvwb4qnmumvcn7nh4pxrtugrlpw4jgjpqicdxsv7opdm6e`
Try changing it to `dnslink=/ipns/webui.ipfs.io` – this way your local domain will automatically follow any future upstream updates, removing the need for you to update DNS.

Let me know if this helps.

**Comment by akimoto72738** [comment]
@lidel 
Thanks,It's worked

> ![捕获](https://user-images.githubusercontent.com/67720156/89602108-9682bb00-d898-11ea-9f5e-b7cdd14b9641.JPG)

Now, The world returns to peace. XD
