### ISSUE TITLE
Improve messaging/continuity when node shut down but UI still open

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-webui#1575]
Originally reported as https://github.com/ipfs-shipyard/ipfs-webui/pull/1571#pullrequestreview-461965298 by @lidel but breaking it out into its own issue.

Original follows:

I've found some UX nits when transitioning "online" → "offline" (eg. when I shut down my go-ipfs node):

1. Connection error is displayed, and the graphs get faded out, but they keep showing the last bandwidth values:
   > ![2020-08-05--20-48-30](https://user-images.githubusercontent.com/157609/89451804-0a1fad80-d75d-11ea-86b3-b9528250120b.png)
   
   I'd expect "offline" state to set them to zeroes.
2. _Files_, _Explore_, _Peers_ in navbar are not being correctly disabled. I can go to each and there is either error or an outdated cached data that does not update. If I refresh page (F5) then those screens are replaced with  connection error on status page. 

3. The flow that starts with clicking on ![2020-08-05--21-29-44](https://user-images.githubusercontent.com/157609/89455618-e5c6cf80-d762-11ea-8f9a-902038a7aa7a.png) → Expanded Status → API multiaddr <kbd>Edit</kbd> →  _Settings_  → API multiaddr input is really nice. It encourages user to intuitively discover things.
  
   The problem: when in offline status, clicking on the ![2020-08-05--21-26-39](https://user-images.githubusercontent.com/157609/89455293-61744c80-d762-11ea-85d4-83d3a0615461.png) does nothing. It can't expand node info, because API is down and that block is hidden. Perhaps the fix is to skip expand step and immediately open the  _Settings_ and scroll to API address input?

**Comment by jessicaschilling** [comment]
@lidel - a few thoughts/questions on your original issue:
1. Good catch!
2. True; @rafaelramalho19 and I had noticed this when working through the earlier welcome screen work. At minimum, we need better detection of node offline status in order to automatically replace outdated data with the "could not connect" variant of Welcome page (current behavior, but only happens if you reload). Even better, we would replace it with a "could not connect" message that didn't have the informational boxes from the Welcome page.
     - Side note on this: I *think* that in current state, *eventually* any page does get replaced by the "could not connect" variant of the Welcome page. However there's an interval where what you're describing definitely happens.
3. For this scenario (Status screen immediately after disconnect) what if we ...
    - Disabled the clickability of the red "connection status" icon in top right, since you're already on that page (actually maybe we should disable clickability when in Status screen regardless of connection status)
   - In the troubleshooting guidance, add the API input box from the "could not connect" variant of Welcome page

**Comment by lidel** [comment]
2.  Ack, :+1 for hiding the informational boxes ("in this app", "what is IPFS") when in  "cound not connect" state
3.  Adding input box would be enough imo

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1577 should address everything except improving the detection/refresh logic.
