### ISSUE TITLE
loading webui via http://127.0.0.1:5001/ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4/#/ does not work

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-webui#1587]
**Describe the bug**
When using firefox 79 on my fedora 32 install, visiting http://127.0.0.1:5001/ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4/#/ only partially loads the page, with requests like GET http://127.0.0.1:5001/ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4/locales/en-US/settings.json resulting in a 404 according to the browser console.
The webui loads fine from other URLs, and on this URL in chromium.

**To Reproduce**
1. Go to http://127.0.0.1:5001/ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4/#/
4. All you see is a white screen

**Expected behavior**
The URL should load the webui like normal.

**Screenshots**
![](https://ipfs.io/ipfs/QmZpJF31U8iofV7654qwapcsStce25YPFg2pbnhnxdAKwE/2020-08-12_20-24-32.png)

**Desktop:**
 - OS: fedora 32
 - Browser firefox
 - Version 79

**Comment by jessicaschilling** [comment]
@lidel and/or @rafaelramalho19 - do you mind having a look as you're able? Thank you!

**Comment by lidel** [comment]
@swedneck this is an error returned by Firefox when SQLite database responsible for `window.localStorage` is corrupted.
Closing this as there is nothing we can do about it – this is a problem with your browser :( 


AFAIK you could try:

* While you are on that broken webui tab, open console and try executing `window.localStorage.clear()` + reload page. 
*  If that does not fix the problem, you may need to remove 
`webappsstore.sqlite` from `~/.mozilla/**` and let Firefox recreate it.

Let us know if this helped.

**Comment by swedneck** [comment]
@lidel `window.localStorage.clear()` worked!
