### ISSUE TITLE
Showing pins loads all pins into memory, even for super-large repos

### ISSUE THREAD

**Issue by JRoper18** [ipfs-shipyard/ipfs-webui#1592]
**Describe the bug**
When opening the pins view in the WebUI, I think the pins **and all their content** are loaded into memory. For large repos, this tends to overflow memory usage on the ipfs daemon. 

**To Reproduce**
1. Pin a large repo into your IPFS daemon. ~2GB is enough to cause the memory usage to crash my daemon. 
2. Go to 'files'
3. Click on 'pins'
4. Watch the daemon's memory usage until it explodes. Shouldn't take more than a minute. 

**Expected behavior**
When looking at the pins view, I don't want the daemon to crash. It's loading something massive into memory when performing this operation. 

**Screenshots**
![Screenshot from 2020-08-18 10-02-38](https://user-images.githubusercontent.com/8838052/90530767-e126f180-e13a-11ea-8057-57b55753a43b.png)

Memory usage stars increasing from a few MB in the performance monitor the instant I click on "pins". 

**Desktop (please complete the following information):**
 - OS: Daemon and Browser are running on Ubuntu 18.04
 - Browser Firefox
 - Version 79.0, 64 bit

**Additional context**
If this is a problem with the daemon I can repost the issue in their repo, but the daemon runs fine until the pins are fetched from the WebUI.

**Comment by jessicaschilling** [comment]
Thank you for bringing this to our attention! It's been flagged for review at the next weekly triage meeting.

**Comment by jessicaschilling** [comment]
Hi @JRoper18 -- Thanks for bringing this up. We're releasing a new version of Web UI (and therefore Desktop) soon that will add support for third-party pinning services and mitigate this issue in the process. Closing this issue in the interim - see https://github.com/ipfs/ipfs-gui/issues/91 for details on the pinning service epic.
