### ISSUE TITLE
Adding peer of type "/dnsaddr/foo" not supported in "Add Connection" modal

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-webui#1593]
I can do this from my command line:

> $ ipfs swarm connect /dnsaddr/ipfs-nodes.cluster.ipfs.io

But not from Web UI. Let's fix this.

![image](https://user-images.githubusercontent.com/1507828/90561727-6243b000-e15e-11ea-883c-2d4672c55ec1.png)

**Comment by jessicaschilling** [comment]
@lidel -- per our conversation 😊  We can discuss in next triage meeting.

**Comment by lidel** [comment]
We need to see if updating to latest `is-ipfs` is enough.
If not, we need to pic up https://github.com/multiformats/js-multiaddr/issues/94 and finish adding full support for `/dnsaddr.

**Comment by rafaelramalho19** [comment]
Updating is-ipfs didn't work @lidel 
Guess we need to add full support for `/dnsaddr`

**Comment by lidel** [comment]
Kicked-off discussion in https://github.com/multiformats/js-multiaddr/issues/94#issuecomment-682497762

**Comment by lidel** [comment]
Fixed in https://github.com/multiformats/js-multiaddr/pull/149, we need to switch to the latest version and see if it "just works"
