### ISSUE TITLE
CLI tutor mode: Support subdirectories for "import" commands

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-webui#1601]
Per @lidel in https://github.com/ipfs-shipyard/ipfs-webui/pull/1572#pullrequestreview-475583140:

> CLI tutor for Import commands ignores the fact we may be in a subdirectory.
> Ideally `/<dest-name>` in import commands would be replaced with `"${path}/<dest-name>"` where `path` is the current dir in MFS. I started doing that in [`3a337de`](https://github.com/ipfs-shipyard/ipfs-webui/commit/3a337de195cdecf9a9e41e4a3486e511b736897b) but had no bandwidth to wire it up.
> If anyone has time to ensure `path` is set for [these actions](https://github.com/jay-dee7/ipfs-webui/blob/jay-dee7/cli-tutor-mode/src/files/modals/Modals.js#L157-L160) that would be even better for user experience.

To do: Complete the work referenced above, and if appropriate add/rework any CLI tutor mode functionality as discovered post-2.11 launch.

**Comment by melegiul** [comment]
Hey @jessicaschilling can I please take over this one? I could soon provide a PR, where you can check it out and make any suggestions/refactors.

**Comment by jessicaschilling** [comment]
Thanks, @melegiul! We'll take a closer look in the next few days 😊
