### ISSUE TITLE
Update Taiwan's listing in peers table

### ISSUE THREAD

**Issue by hansen033** [ipfs-shipyard/ipfs-webui#1603]

**Comment by jessicaschilling** [comment]
The data that feeds this table actually lives in https://github.com/ipfs-shipyard/ipfs-geoip - will reference any changes to that repo back to this issue, though.

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-geoip/pull/76 addresses and will close this issue. Thanks @hansen033 for bringing this up!

**Comment by lidel** [comment]
@jessicaschilling I've released [ipfs-geoip v5.0.0](https://github.com/ipfs-shipyard/ipfs-geoip/releases/tag/v5.0.0). You should be able to open a PR which switches webui to the latest version. 

ps. I believe the lookup results are cached, so we may have situation where `Unites States` and `USA` are mixed for a while (use incognito or clear browser session for testing).

If you feel it's a problem, I can do a patch release which uses a new cache.

**Comment by jessicaschilling** [comment]
Updated and merged for inclusion in the upcoming Web UI release: 
![Screen Shot 2020-09-01 at 4 48 37 p](https://user-images.githubusercontent.com/1507828/91913510-0bb49680-ec73-11ea-88d9-1c197dc27945.png)
