### ISSUE TITLE
Connect to the API using HTTPS

### ISSUE THREAD

**Issue by hazae41** [ipfs-shipyard/ipfs-webui#1627]
**Describe the bug**
We can't connect to the API using HTTPS

**To Reproduce**
My IPFS daemon is running on an external server
My computer and my server are both on a VPN
My server hostname (only accessible through VPN) is `vpn.sunship.tk`

While I can successfully connect to `http://vpn.sunship.tk:5001/webui`,  this is over HTTP, so it's not secure

So I made an HTTPS reverse proxy on port 1234
But `https://vpn.sunship.tk:1234/webui` won't load (maybe another issue? or a misconfigured proxy?)

So now I'm using the public webui https://webui.ipfs.io/
But I'm stuck when entering the following address `/dns4/vpn.sunship.tk/tcp/1234`
It seems the website only wants to connect to the API through HTTP, which fails

**Expected behavior**
Something to allow us to connect using HTTPS instead of HTTP
Maybe a toggle in the options?

**Comment by jessicaschilling** [comment]
Thank you - we will bring this up in our next weekly triage.

**Comment by lidel** [comment]
@hazae41 I am closing this, as this should be fixed since ipfs-webui v2.11 (including https://webui.ipfs.io)

You need to explicitly state that the protocol is HTTPS.  Use  `/dns4/vpn.sunship.tk/tcp/1234/https` or `https://vpn.sunship.tk:1234` 

Both will work.

**Comment by hazae41** [comment]
Thanks! It works
