### ISSUE TITLE
Provide visual feedback if entered API address is up/down/invalid

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#1635]
This should be a quick win:

Reuse animation from  ["Add connection" on Peers screen](https://github.com/ipfs-shipyard/ipfs-webui/pull/1596#issuecomment-688807918) for newly added "API address" section on _Settings_ screen

Namely:

- red border on text entry field when value is not a valid JSON/Multiaddr/URL
- green border on text entry field when value is valid
- Display cube animation while connecting:
     - Same size and position (large, over whole screen) as is displayed when loading the Peers page
     - Same subtle "white-out" over screen content as what is displayed when using the cube as a loading indicator over the top of the "Add connection" modal
- Display feedback:
     - Red border + orange snackbar error message if failed to connect: "Could not connect to the provided API address."
     - Switch to Status page if connection is successful

**Comment by jessicaschilling** [comment]
Yes please 😊

**Comment by lidel** [comment]
User will be entering API address either on _Status_ or _Settings_ screen, so cube animation on entire screen should be enough (_Settings_ screen already hides config when connection is down).

**Comment by jessicaschilling** [comment]
Displaying the cube just inside the component is a little inconsistent visually - let's use the entire screen, with a white screen behind the cube in the same manner as how it slightly whites out the "add peer" modal. 

I'm going to put this in the 2.12 milestone and the "Quick Fixes" column for now.
