### ISSUE TITLE
Possible translation regression since last published version v2.10.2

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipfs-webui#1636]
**Describe the bug**
Some buttons were correctly translated in IPFS webui v2.10.2, but are not translated in the current version displayed at dev.webui.ipfs.io, whose CID corresponds to v2.11.1 (according to https://github.com/ipfs-shipyard/ipfs-webui/releases).

(Also, ipfs.io/ipfs/bafyV2.11.0 and ipfs.io/ipfs/bafyV2.11.1 leads to 404. Same for ipfs add bafyV2.11.x...)

It may be that the missing button translations are missing on dev.webui.ipfs.io, but will be there when V2.11.1 is out (couldn't check because I couldn't fetch bafyV2.11.1 displayed in the GitHub releases). But it could also be a regression you're unaware of.

**To Reproduce**
Go to dev.webui.ipfs.io (with or without a running deamon).
Change settings to a fully translated language such as French. 
See missing translations (see screenshots below).
Fetch V2.10.2 and see translations.

Also: the strings are now missing from Transifex, so we can't traduce them again.

**Expected behavior**
All buttons are available to translate on Transifex, and translated buttons are translated in-app.

**Screenshots**
See button "Close" below:
![image](https://user-images.githubusercontent.com/8818223/93345538-3c7bfa80-f833-11ea-91e3-e320f8ef163b.png)

"API adress", "Change", Submit, Reset, Save,etc. 
![image](https://user-images.githubusercontent.com/8818223/93347770-c0cf7d00-f835-11ea-89f3-1768c00c5d2f.png)

Browse, Inspect (on all pages, at the top) , peers (several places), latency, etc.:
![image](https://user-images.githubusercontent.com/8818223/93347969-f4aaa280-f835-11ea-9db2-4f6ffce30d38.png)µ

On all pages, in the help: Next, Close, Finish:
![image](https://user-images.githubusercontent.com/8818223/93348224-3b989800-f836-11ea-8366-e8c244567cde.png)

On disconnected node: Could not connect to API and submit:
![image](https://user-images.githubusercontent.com/8818223/93348918-1ce6d100-f837-11ea-8cd5-372ae8f0fbe4.png)
(Same for "Connected to the API" when connected)

On Files: Inspect, pin, files (breadcrumbs and volume, numbers of pins, blocks, "repo" size, button import, "name" and "size" in the tab. 
![image](https://user-images.githubusercontent.com/8818223/93350165-a0ed8880-f838-11ea-9323-aa3156139c77.png)

On Status: 
API Adress, Gateway, etc. 
the new "Edit" link next to the API adress
Advanced
More info/No/Thanks,
![image](https://user-images.githubusercontent.com/8818223/93350606-1ce7d080-f839-11ea-8d28-cce6acbbb428.png)

On Status:
In/Out
Incoming/Outgoing
![image](https://user-images.githubusercontent.com/8818223/93350676-2ec97380-f839-11ea-9f78-94b685f371eb.png)

*Bonus:*
In the search bar on top "Qmhash" should be switched to "bafyHash" or "IPFS CID" or "CID"?

The 2 last version are 404 on ipfs.io and local daemon:
![image](https://user-images.githubusercontent.com/8818223/93348482-8c0ff580-f836-11ea-8485-88be7e53c6b0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser : Chrome, Firefox, Brave
 - Version : latest for Ubuntu

**Additional context**
None

**Comment by jessicaschilling** [comment]
Hi @bertrandfalguiere -- https://github.com/ipfs-shipyard/ipfs-webui/pull/1604 consolidated a number of repeat-use internationalization keys that had been duplicated and in a number of cases led to inconsistencies in the UI. Unfortunately, this does mean that some of these reverted back to English in translated settings.

You're correct that the common-keys file `app.json` isn't showing up in Transifex, so it's telling you that (for example) French is completely translated when it's not. @lidel, I seem to be missing permissions to add it - is this something you're able to do when you have the chance?

**Comment by bertrandfalguiere** [comment]
Oh, I see, ok.
Let me know when app.json is on transifex.

(PS: About the bafys of two last versions not being accessible, is it expected behavior?)

**Comment by lidel** [comment]
@jessicaschilling indeed, I forgot we need to manually add new resources – I'm sorry :(  added `app-json` resource 

@bertrandfalguiere It should be fixed, you can translate strings from `app.json` at https://www.transifex.com/ipfs/ipfs-webui/app-json/ 
Thank you for reporting this, really appreciate your help with keeping translations on track :heart:

**Comment by jessicaschilling** [comment]
@bertrandfalguiere -- I'm not having any trouble retrieving the last two CIDs for releases ... ping if you're still having problems?

**Comment by bertrandfalguiere** [comment]
All right, French translation is back on tracks. 

> ping if you're still having problems?

Now it's working.... 🤷‍♂️ Maybe my crappy connection? 

Anyway, apart from the "QmHash" that should probably be renamed soon, we can close the issue. 
![image](https://user-images.githubusercontent.com/8818223/93366642-bc15c380-f84b-11ea-8677-1ac7d2742a73.png)

Thanks for the swift resolution! 🚀

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1638 will take care of the browse bar hint.

**Comment by akimoto72738** [comment]
@jessicaschilling 

Hi team, I have translated all text to zh-cn.
I noted there is no reviewer in zh-cn translation team.
Is anyone can review? or may I apply a reviewer position?

**Comment by lidel** [comment]
@akimoto72738 we ususally give this permission to people who contributed before. 
You submitted a lot of translations this year, so you fit the criteria :+1: 
Assigned you the Reviewer role (log-out and log-in again if you don't see it).

Thank you for your contributions! :heart:
