### ISSUE TITLE
"Failed to add file", "Failed to rename" error messages... but it actually worked

### ISSUE THREAD

**Issue by Sovxx** [ipfs-shipyard/ipfs-webui#1645]
**Describe the bug**
A "failed..." message pops up when
Add new folder
or Add new file
or Rename file

**To Reproduce**
See screenshots below

**Expected behavior**
No error messages because adding and renaming seem to have worked! :)

**Screenshots**
New folder:
![new folder](https://user-images.githubusercontent.com/12556923/93569287-9db9e000-f991-11ea-9712-0c1db49bf323.gif)
Adding file:
![import](https://user-images.githubusercontent.com/12556923/93569303-a27e9400-f991-11ea-963c-e6c143a0ff55.gif)
Renaming file:
![rename](https://user-images.githubusercontent.com/12556923/93569310-a6121b00-f991-11ea-9487-05f65b297c4a.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64 bit
 - Browser Chrome 85
 - Version http://127.0.0.1:5001/ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4   revision 637e0f1

**Comment by jessicaschilling** [comment]
Thanks, @sovxx -- we will review in our next weekly triage!

**Comment by lidel** [comment]
@Sovxx I believe this is fixed in v2.11 which shipped recently  and is available at https://webui.ipfs.io
It  will ship with go-ipfs 0.7 and the next version of ipfs-desktop.
