### ISSUE TITLE
Failed to view TXT file via WebUI

### ISSUE THREAD

**Issue by akimoto72738** [ipfs-shipyard/ipfs-webui#1647]
**Describe the bug**
Failed to view TXT file via WebUI

**To Reproduce**
1.click txt file to view content

**Screenshots**
![屏幕截图 2020-09-19 104603](https://user-images.githubusercontent.com/67720156/93657429-77657480-fa65-11ea-81df-458934fb63ce.png)
![屏幕截图 2020-09-19 104633](https://user-images.githubusercontent.com/67720156/93657431-7cc2bf00-fa65-11ea-8c1b-0fd00a213d28.png)

**Desktop (please complete the following information):**
 - Browser [Opera Lastest version]
 - Version [2.11.1]

**Comment by jessicaschilling** [comment]
@akimoto72738 - thank you. We'll bring this up in our next triage.

**Comment by lidel** [comment]
I believe this will be fixed by https://github.com/ipfs-shipyard/ipfs-webui/pull/1646
