### ISSUE TITLE
The webUI should display the webui version

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipfs-webui#1649]
**Is your feature request related to a problem? Please describe.**
I had problems with concurrent installations of IPFS Desktop and one on them was out of date. It took me some time to realize that depending on how I opened it, a different version was displayed. 

**Describe the solution you'd like**
Having the webUI version displayed (for example in the Status page, under the AGENT) would help debug such issues and probably more. It could also make explicit to users why they see different webUIs when they access it through IPFS Desktop, webui.ipfs.io, or dev.webui.ipfs.io.

The perfect place for this information is debatable, as the "Status" page is dedicated to the information about the node, not the interface itself. Maybe between the IPFS logo and the "Status" page, on the left-side menu? I feel that it would be an important piece of information for newcomers.  
Also, having explicit, visible webui version could entice some users to try out the lastest version available, not the version shipped with the current version of IPFS Desktop.

**Comment by jessicaschilling** [comment]
@bertrandfalguiere Great idea! Might you be willing to make a quick PR for it?

**Comment by bertrandfalguiere** [comment]
I've never really JavaScripted but I'll try. 

I thought about the "Revision" too, but I don't see it displayed when I access the WebUI via browser (as opposed to inside IPFS Desktop)

**Comment by jessicaschilling** [comment]
Thanks for giving it a try!

> I thought about the "Revision" too, but I don't see it displayed when I access the WebUI via browser (as opposed to inside IPFS Desktop)
Curious - how small is your browser window? It's there, but goes away at smaller vertical heights.

**Comment by bertrandfalguiere** [comment]
My resolution is 1366x768. Height might be cropped up by the browser's bar, etc. 
![image](https://user-images.githubusercontent.com/8818223/94297637-1eb24200-ff65-11ea-9604-0e48d087fa90.png)

**Comment by jessicaschilling** [comment]
@bertrandfalguiere That looks like a close-but-not-quite fit. Opened https://github.com/ipfs-shipyard/ipfs-webui/issues/1650 to remedy.
