### ISSUE TITLE
Unpinning item creates error/warning dialogs

### ISSUE THREAD

**Issue by MidnightLightning** [ipfs-shipyard/ipfs-webui#1656]
**Describe the bug**
When navigating the Web UI of a node running on a separate server, when using the "Pins" navigator and the user unpins an item, the item is successfully unpinned, but the browser stays on that (now unpinned CID), and two error notices popup.

**To Reproduce**
Go to "Pins"
Click on a pinned item to preview
Use "..." menu in top-right to "unpin" item
Double error notices pop up.

**Expected behavior**
Item is unpinned, user is directed up one level in the file hierarchy, and no errors appear.

**Screenshots**
![unpin](https://user-images.githubusercontent.com/250250/94691678-35ef8780-02f7-11eb-8ebd-f87f8951c903.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.14

**Additional context**
Browsing on remote node (other server in same LAN), running `go-ipfs` 0.7.0

**Comment by jessicaschilling** [comment]
Hi @MidnightLightning - this has been resolved in https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.2. Will close this issue, but please comment if you continue to have problems - thanks!
