### ISSUE TITLE
Status page: Improve bandwidth graph display

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-webui#1672]
I’ve been taking the time to use IPFS Desktop more and more to monitor my IPFS node and it just dawned on me that probably we don’t want a bandwidth graph since the dawn of time, otherwise it makes it look very spiky

![image](https://user-images.githubusercontent.com/1211152/96262991-c817b100-0fc2-11eb-850d-6601906e287e.png)

Note that this window of time is just a span for 2:30h hours, which is not that large.

**Comment by jessicaschilling** [comment]
Quick thoughts:
- There's probably a compelling case for a redesign of this screen in general, but would be nice to mitigate this in the meantime
- Could potentially go a long way by including zoom controls as a stopgap

@lidel @rafaelramalho19 - your thoughts?

**Comment by jessicaschilling** [comment]
From triage discussion: Including this in requirements definition under https://github.com/ipfs/ipfs-gui/issues/33 and https://github.com/ipfs-shipyard/ipfs-webui/issues/1003 and closing this individual issue for simplicity.

Rethinking Files and Status screens (probably in that order) are high-priority large deliverables, but will be back-burnered until we integrate pinning services in Q4.
