### ISSUE TITLE
Repo statistics are converted to lower case

### ISSUE THREAD

**Issue by Luflosi** [ipfs-shipyard/ipfs-webui#1677]
**Describe the bug**
The four words "files", "pins", "blocks" and "repo" at the top of the "FILES" tab are always lower case, even in languages where that's not appropriate because nouns begin with an upper case letter, like in German.

**Expected behavior**
The case of the four words should not be altered when rendered. If lower case text is desired for English, this should instead be done in the translation files (public/locales/en/app.json I think).

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/15217907/97080023-b3599f80-15f8-11eb-99f4-679bb9245ec4.png)

**Desktop:**
 - OS: macOS 10.15.7
 - Browser Safari
 - Version 14.0

**Additional context**
The text is lower case because it has the `ttl` className: https://github.com/ipfs-shipyard/ipfs-webui/blob/03113a68908bc67bb2e499c8bdf3c02cdb361e14/src/files/header/Header.js#L21

**Comment by jessicaschilling** [comment]
Good observation. Will address in a future release - or a PR would be welcome if you are so inclined. (There's no reason in terms of house style this needs to be lowercase; would be simplest just to use title case for all locales.)

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1679 takes care of this.

**Comment by Luflosi** [comment]
Awesome 🎉
Btw, what's the reason for making it upper case instead of preserving the case?

**Comment by jessicaschilling** [comment]
In this instance, it's for visual consistency with the labels in the left nav. 

We are planning to do a more thorough visual rework in the medium term, but there is some functional work in progress that needs to land first.
