### ISSUE TITLE
pin selected and recursively

### ISSUE THREAD

**Issue by Tcll** [ipfs-shipyard/ipfs-webui#1681]
currently when you select multiple items, there's no option to pin them:
![Screenshot_2020-10-28_10-23-03](https://user-images.githubusercontent.com/773959/97449065-a9d97b80-1907-11eb-81c4-5215555cc20b.png)
this can be a headache to manage when importing large folder structures you want to pin

a checkbox could be added if you want to pin selected folders recursively

**Comment by jessicaschilling** [comment]
Hi @Tcll -- thank you for highlighting this!

We are currently mid-stream on adding support for third-party pinning services (see https://github.com/ipfs/ipfs-gui/issues/91 for MVP breakdown) and adding pinning support to that multi-select bottom drawer will be part of that effort; please see https://github.com/ipfs-shipyard/ipfs-webui/issues/1682 for the issue where this is being tracked. (Closing this issue in the meantime as a duplicate).
