### ISSUE TITLE
Question about using 

### ISSUE THREAD

**Issue by Michellezqy** [ipfs-shipyard/ipfs-webui#1690]
My software has interacted with IPFS,and then get a hash.I can get the original file by searching the hash.
Here is my question: what if I forgot to store the hash,how can I find the original file on IPFS ?
By the way "file"section on the web UI didn't show the information,since I upload a file with program.
If anyone knows anything about the situation,you are welcomed to contact with me.

**Comment by jessicaschilling** [comment]
Hi @Michellezqy, please use our forums for support and discussion questions like this one:
https://discuss.ipfs.io/
Thanks!
