### ISSUE TITLE
Make it more intuitive to manage multiple peers

### ISSUE THREAD

**Issue by Tcll** [ipfs-shipyard/ipfs-webui#1696]
Whenever you generate a new key with `ipfs key gen --type=rsa --size=2048 peername`, it seems messy to set up a folder in the self peer to assign to the new peer.

My idea to manage this is to have a dropdown selection on the PEER ID entry in the STATUS table.
The contents of the dropdown selection would be the keys from `ipfs key list`

What I expect here is selecting an alternate key and then clicking the FILES tab will allow you to manage the files of the selected peer.

EDIT: Since the current setup relies on folders, integrating this could provide an alternate option to automatically create a static root folder under the new peer name within the self peer.
(the folder could be highlighted red to denote it as a sub-peer)
Being an option, this could be disabled for the current behavior.

**Comment by jessicaschilling** [comment]
Cool idea! @lidel - your thoughts on this? Ideally we'd also be able to generate a new key from the UI, but in the meantime could be a nice perk for folks who have done it from the command line.

**Comment by jessicaschilling** [comment]
Rolling this into the larger discussion at https://github.com/ipfs/ipfs-gui/issues/77 and closing this sub-issue.
