### ISSUE TITLE
Upgraded to repo version 10 and lost webui

### ISSUE THREAD

**Issue by TitaniumCoder477** [ipfs-shipyard/ipfs-webui#1705]
I upgraded to repo version 10 but lost the ability to reach the webui page.

1. Upgrade from 9 to 10 using: fs-repo-migrations -to 10
2. Upgrade go-ipfs to 0.7.0
2. Start the ipfs daemon
3. Attempt to browse: http://192.168.1.43:5001/webui
4. Get redirected to http://192.168.1.43:5001/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/ with an error: ipfs cat /ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/: merkledag: not found

I expect to see the IPFS Web UI.

Figure 1: My service details w/ version info; systemctl status ipfs:
> ● ipfs.service - IPFS Daemon
>    Loaded: loaded (/lib/systemd/system/ipfs.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2021-01-05 20:43:33 EST; 1s ago
>  Main PID: 1222 (ipfs)
>     Tasks: 8 (limit: 2358)
>    Memory: 45.2M
>    CGroup: /system.slice/ipfs.service
>            └─1222 /usr/local/bin/ipfs --config=/media/data/.ipfs daemon
> 
> Jan 05 20:43:33 WIL-IPFS-SRV systemd[1]: Started IPFS Daemon.
> Jan 05 20:43:33 WIL-IPFS-SRV ipfs[1222]: Initializing daemon...
> Jan 05 20:43:33 WIL-IPFS-SRV ipfs[1222]: go-ipfs version: 0.7.0
> Jan 05 20:43:33 WIL-IPFS-SRV ipfs[1222]: Repo version: 10
> Jan 05 20:43:33 WIL-IPFS-SRV ipfs[1222]: System version: amd64/linux
> Jan 05 20:43:33 WIL-IPFS-SRV ipfs[1222]: Golang version: go1.14.4

Figure 2: ipfs responds fine; ipfs files ls gives me:
> ipfs-companion-imports
> nextcloud
> screenshots

Figure 3: However, can't get the webui to pull up
![IPFS_pic1](https://user-images.githubusercontent.com/26101661/103720638-cd6d1200-4f99-11eb-8bbe-c6e3bcde928c.png)
![IPFS_pic2](https://user-images.githubusercontent.com/26101661/103720642-d1009900-4f99-11eb-816d-d9d8cf79b318.png)

Using Chrome and Firefox on multiple computers and in incognito produces same result. I also cleared all cookies and cache and even F12 > right-click reload > Empty Cache and Hard Reload.

FYI, I permit API access on my LAN only. This was all working prior to the upgrade as recently as this past weekend when I was using the web UI.

**Comment by jessicaschilling** [comment]
Thanks for this detailed info - we will look more closely in the next scheduled triage session. You may also want to check in with the forums at discuss.ipfs.io to see if folks in the wider community might have guidance as well.

**Comment by TitaniumCoder477** [comment]
Thank you @jessicaschilling. After work this evening, I was contemplating how to spend the evening and the random thought popped into my head that I should check the webui again. I completely expected it to be exactly, precisely, the same as last night since I had literally not touched it since creating the issue here. But to my complete surprise, the webui appeared like a genie from a lamp and smiled coyly as if to imply I should question my sanity before documenting such an outrageous claim.

Dramatic personifications aside, I have no earthly idea why it is working now. The server has been up 22 hours and 8 minutes since I gave it my last try, documented the issue here, and lived to fight another day. I'm totally feeling happy, mystified, and suspicious at the moment. :)

**Comment by jessicaschilling** [comment]
😊 
Will chalk up to gremlins, but it's still on our triage list. Leaving this issue open for now.

**Comment by lidel** [comment]
@TitaniumCoder477 go-ipfs v0.7.0 uses a new version of webui, that was not present in your repo.

The error:
```
merkledag: not found
```

suggests that your node was offline, so it could not find the new webui in local repo nor it was able to fetch it.

Between that error and now you most likely started your node (`ipfs daemon`) and when you opened webui it was fetched and cached (so in the future its fetched from local repo).

I'm closing as your issue is solved, but we should take a mental note that `merkledag: not found` error should be improved – we track that in https://github.com/ipfs/go-ipfs/issues/2009
