### ISSUE TITLE
Regarding bandwidth api response

### ISSUE THREAD

**Issue by cpp-keshav** [ipfs-shipyard/ipfs-webui#1710]
Hello Team, 

can you please  let me know about the response which we get through bandwidth api that in which unit the following response displayed -

{
  "TotalIn": 8942335374,
  "TotalOut": 825541362,
  "RateIn": 10725.438180925377,
  "RateOut": 1100.0009583824885
}

please specify the unit of each data

**Comment by SELENITACOUSTICS** [comment]
This business account of my small firm which I use trough gmail for
corespod with some clients and that is all...although I did make long time
now a github account with this adress mail but I do not use that lack of
time and understanding...So obviously..this is hacked account...and some
one with knoledge in correspondenting with you and your help ...I recently
saw bunch of mails from your part but did not think much. But. .couse I do
not know wtf is all about I think now tgat it is some third partie
included..and I do not have clue at all.
Deep apologiez and please I am so so sorry
 for every bit inconvenience

Love and light

Ana Burazer Siriscevic - Selenit j.d.o.o.

sri, 13. sij 2021. 10:35 cpp-keshav <notifications@github.com> je napisao:

**Comment by jessicaschilling** [comment]
@cpp-keshav I'm not sure where you're making this query from -- this repo is for the IPFS Web UI -- but you can get bandwidth stats, units included, from the command line by `ipfs stats bw`.

Full CLI docs are here: https://docs.ipfs.io/reference/cli/

Please, however, for future discussions or support topics, use the forums at https://discuss.ipfs.io. The GitHub issue queue is for bug reports and features work.

**Comment by SELENITACOUSTICS** [comment]
ok thank you
blessings

sri, 13. sij 2021. u 16:58 Jessica Schilling <notifications@github.com>
napisao je:
