### ISSUE TITLE
When selecting the node information, then Advanced Panel automatically close.

### ISSUE THREAD

**Issue by FledgeXu** [ipfs-shipyard/ipfs-webui#1711]
**Describe the bug**
The advanced information in the status panel has a wrong click box and this bug makes copying node information hard.

**To Reproduce**
1. Go to 'Status Panel'
2. Click on 'Advanced'
3. Try to select information.

**Expected behavior**
When I selected node information, the Advance panel shouldn't close.

**Screenshots**

https://user-images.githubusercontent.com/16664654/104807271-bee3ed80-5818-11eb-8a20-ac91d34cf858.mov

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version 87.0.4280.141

**Comment by jessicaschilling** [comment]
- Thank you, @FledgeXu! This is a known issue under #1693, so will close this as a duplicate, but thank you for the prioritization - we have been occupied on a large project and will push this up n the queue for when that's done.
