### ISSUE TITLE
Webui interface cannot open files after IPFS upgrade in private cluster

### ISSUE THREAD

**Issue by gsp-hub** [ipfs-shipyard/ipfs-webui#1712]
![image](https://user-images.githubusercontent.com/71632608/105114079-204dda00-5b01-11eb-9b92-bf1041f7e0c0.png)

**Comment by gsp-hub** [comment]
Webui display yellow alarm：Failed to get those files. Please check the path and try again.

**Comment by jessicaschilling** [comment]
Can you describe in more detail what you mean by "after upgrade in private cluster"? Do you mean that you updated your local node, and that node is part of a private cluster?

If you also use the command line, are you able to retrieve those files via the command line?

**Comment by gsp-hub** [comment]
I configured the private network of IPFs and did not join the public network node. Then I used the version 0.4.23 of IPFs. Now I download a version 0.6.0 of IPFs and upgrade it to 0.6.0. I use FS repo migrations to migrate to ensure that the data is not lost. The migration is successful and the upgrade of IPFs is completed.

But on the webui page, there's a warning: you can't get those files. Please check the path and try again. Local file exists

**Comment by gsp-hub** [comment]
Hello, I use the command line to view the file display can see, and is fixed

**Comment by jessicaschilling** [comment]
Glad you were able to resolve!
