### ISSUE TITLE
Brakuje polskiego tłumaczenia

### ISSUE THREAD

**Issue by ojej** [ipfs-shipyard/ipfs-webui#1714]
Wszystko jest po angielsku
może warto użyć jakiegoś darmowego systemu do tłumaczenia przez www. Wtedy dużo osób będzie mogło tłumaczyć.

**Comment by jessicaschilling** [comment]
@lidel proszę odpowiedz?

**Comment by lidel** [comment]
@ojej możesz pomóc w tłumaczeniu zakładając konto na Transitex: https://www.transifex.com/ipfs/public/ 
👍🌝👍

**Comment by ojej** [comment]
nie znam angielskiego
ale tłumaczenia nie ma
