### ISSUE TITLE
jak założyć stronę www

### ISSUE THREAD

**Issue by ojej** [ipfs-shipyard/ipfs-webui#1716]
Może ktoś napisze po prostu przewodnik , jakiś opis jak założyć własną stronę www.
na początek prosta statyczną a potem jakieś forum

**Comment by jessicaschilling** [comment]
You can view the current documentation for IPFS at https://docs.ipfs.io/. This includes tutorials on publishing static websites, and more.
Forums also are a helpful resource at https://discuss.ipfs.io.
Please direct any requests for documentation content _that does not already exist_ in the docs repo, _not_ this one: https://github.com/ipfs/ipfs-docs.
