### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by ojej** [ipfs-shipyard/ipfs-webui#1722]
Why Polish language not add to translate?

**Comment by jessicaschilling** [comment]
Hi @ojej — Just to confirm, we do have Polish as a language option in the Settings page:

![image](https://user-images.githubusercontent.com/1507828/108389670-20f39200-71cd-11eb-8fdc-4850ba5a958f.png)

However, you're right that if you choose that option not very many of the text strings are translated! Would you like to help translate? It's simple and actually rather fun. 😊 

If you're interested in contributing a translation, [go to our page on Transifex](https://www.transifex.com/ipfs/ipfs-webui/translate/), create an account, pick a language and start translating. Be sure to change your notification settings to be notified when translation sources change.

Thanks!

**Comment by ojej** [comment]
1. I cant add translate to polish in transifex
2. in program is many text in english not in polish (when polish is seting)

**Comment by lidel** [comment]
@ojej please request joining polish translation team via https://www.transifex.com/ipfs/ipfs-webui/, I'll approve you when you do.
