### ISSUE TITLE
Why bafkqaaa is hardcoded inside the config.js

### ISSUE THREAD

**Issue by woss** [ipfs-shipyard/ipfs-webui#1732]
Hi, 

Can someone explain why the `bafkqaaa` is hardcoded

```js
const checkIfGatewayUrlIsAccessible = memoize(async (url) => {
  try {
    const { status } = await fetch(
    `${url}/ipfs/bafkqaaa`
    )
    return status === 200
  } catch (e) {
    console.error(`Unable to use the gateway at ${url}. The public gateway will be used as a fallback`, e)
    return false
  }
})

// Separate test is necessary to see if subdomain mode is possible,
// because some browser+OS combinations won't resolve them:
// https://github.com/ipfs/go-ipfs/issues/7527
const checkIfSubdomainGatewayUrlIsAccessible = memoize(async (url) => {
  try {
    url = new URL(url)
    url.hostname = `bafkqaaa.ipfs.${url.hostname}`
    const { status } = await fetch(url.toString())
    return status === 200
  } catch (e) {
    console.error(`Unable to use the subdomain gateway at ${url}. Regular gateway will be used as a fallback`, e)
    return false
  }
})
```

Code is https://github.com/ipfs-shipyard/ipfs-webui/blob/master/src/bundles/config.js#L110 and https://github.com/ipfs-shipyard/ipfs-webui/blob/master/src/bundles/config.js#L125

This is the Network tab, failing. 
![image](https://user-images.githubusercontent.com/80440/111763383-607fcd80-88a2-11eb-8c66-3c6f89ee1962.png)

Any specific reason why this is there? 

IPFS Node is running in Private mode on the remote server and the UI is accessed via the external IP, not localhost

When I run the IPFS node and UI in localhost everything works

**Comment by woss** [comment]
it seems that chaning the default `0.0.0.0` in the `Addresses` to the correct IP starts working correctly

**Comment by lidel** [comment]
This a CID we use for testing if local  gateway works correctly. 
If it does not, a public gateway is used for some features instead. 
(Empty identity CID like `bafkqaaa` does not require DHT lookup, so is perfect for such a simple test)
