### ISSUE TITLE
There is no way to recursively add a folder using the webui

### ISSUE THREAD

**Issue by caioalonso** [ipfs-shipyard/ipfs-webui#19]
The file input wants one or more files. And dragging and dropping the folder doesn't work.

**Comment by jbenet** [comment]
i think that the browser doesn't let us drag + drop folders, but i'm not sure. @CaioAlonso do you have an example of an application that does?

**Comment by CaioAlonso** [comment]
@jbenet I think this shows how it can be done: http://updates.html5rocks.com/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available

**Comment by travisperson** [comment]
First thing that needs to happen in the following:
https://github.com/mappum/node-ipfs-api/issues/3
https://github.com/mappum/node-ipfs-api/issues/4

After that we can do directory uploading with the `directory mozdirectory webkitdirectory` attributes.

http://html5-demos.appspot.com/static/html5storage/demos/upload_directory/index.html

**Comment by jbenet** [comment]
This would be very nice to have soon

**Comment by Dignifiedquire** [comment]
@travisperson are you working on this?

**Comment by whyrusleeping** [comment]
i do this in https://github.com/ipfs/file-browser

**Comment by luigiplr** [comment]
Anyone working on this?

**Comment by jbenet** [comment]
no one actively, i think. Would you like to take a shot?
>
>

**Comment by luigiplr** [comment]
@jbenet Potentially.

**Comment by tadeaspetak** [comment]
@jbenet @luigiplr Anyone actively working on this? Should I give it a shot?

**Comment by hacdias** [comment]
The coming version (2.0.0) has this 😄
