### ISSUE TITLE
Pinning should work

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/ipfs-webui#21]
- currently doesnt
- https://github.com/jbenet/go-ipfs/issues/850

**Comment by travisperson** [comment]
Can we get some more info about this? Just based off the references issue and the title I can get to different things.

```
Files that are pinned using "ipfs pin add -r hash" can not be removed from the webui. Files pinned without -r work fine in the webui.

Agent Version: go-ipfs/0.2.3
Protocol Version: ipfs/0.1.0
```

Unpinning files from the webui will work after we allow the recursive option to be sent (see #31).
Dropping localStorage is pretty straight forward, though doing so will make it so you can't see any files added via the local daemon (even though the webui only tracked webui files).

Until we have a way to find locally added files the `file` tab will be blank.

**Comment by whyrusleeping** [comment]
I think files added locally should be noted in the data store somehow

**Comment by jbenet** [comment]
bringing back from a long time ago: 

![](https://www.evernote.com/shard/s198/sh/532ba53e-df87-4e71-bc8d-a9b441a67b17/cd658629bee7c8c3f2b4483125f4a73e/deep/0/Cursor-and-Dribbble---ipfs-files.jpg-by-Benoît-Philibert.png)

i'd like to have a button like that.

**Comment by hacdias** [comment]
WebUI 2.0.0 is coming soon and it was completely rewritten. Please see #749. We replaced this system with MFS, which allows you to easily delete and add your files.
