### ISSUE TITLE
Should there be content links into IPFS from the UI?

### ISSUE THREAD

**Issue by windemut** [ipfs-shipyard/ipfs-webui#212]
I have recently learned if IPFS, and the idea sounds great. The WebUI looks great, too. However, for something that wants to be the new Web, there is remarkable little to browse on it. I have not been able to find a single published web page that's hosted on IPFS. The WebUI appears to be all local or http: links. No ipns: links I could find. Why is this so? Am I missing something?

**Comment by jbenet** [comment]
see https://github.com/ipfs/faq/issues/30#issuecomment-172756566

**Comment by hacdias** [comment]
As version 2.0.0 approaches its release, this issue doesn't seem relevant. You'll now be able to navigate through the Merkel Forest and your MFS files.
