### ISSUE TITLE
Move the globe to it's own page and repo

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-webui#213]
As the globe is nice, but impacts battery life on laptops very badly on laptops I suggest extracting it into it's own repo and publishing it on it's own. This way it's still usable but not everybody is forced to use it when they open the webui.

@jbenet we talked about this on the apps hangout so please let us know if you are okay with this.

**Comment by RichardLitt** [comment]
Agreed. cc @whyrusleeping

**Comment by whyrusleeping** [comment]
:+1:

**Comment by jhamfler** [comment]
Thank you.

**Comment by jbenet** [comment]
Yep :+1: on this thanks

Could we make sure to publish it as an app and maybe link to it from webui
map? (It has a great wow-factor that helps in first impressions)

**Comment by Dignifiedquire** [comment]
> Could we make sure to publish it as an app and maybe link to it from webui

Sure will add a link that opens it in a new window, so people can go and play with it if they want to

**Comment by jbenet** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
Working on this: https://github.com/ipfs/connections-globe
