### ISSUE TITLE
Webui doesn't load in QtWebkit-based browsers

### ISSUE THREAD

**Issue by lamarpavel** [ipfs-shipyard/ipfs-webui#235]
Using a browser based on QtWebkit the webui does not fully load. Visiting http://localhost:5001/webui results in a blank page with the following source:

`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"><link rel="stylesheet" href="ipfs-webui.0.3.0.css"></head><body><div id="root"></div><script src="ipfs-webui.0.3.0.js"></script></body></html>`

I have tested this with [qutebrowser](https://github.com/The-Compiler/qutebrowser) (git master) and [otter-browser](https://github.com/OtterBrowser/otter-browser) (0.9.09) to the same result. With Firefox 44.0 the webui works fine.

**Comment by dignifiedquire** [comment]
Thanks for the report. Are there any errors in the developer console? What webkitversion are these browsers using? I'm guessing that it's either an issue with JavaScript being disabled or the webkit version being simply too old in these as Safar which is webkit based works fine.

**Comment by lamarpavel** [comment]
For qutebrowser:
```
qutebrowser v0.5.1
Git commit: v0.4.0-1569-g921e8b5 (2016-02-03 08:16:59 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
```

Locally installed version of qt5-webkit is 5.5.1 and javascript is enabled in qutebrowser and otter-browser.
Note that there is a difference between webkit and qt-webkit and it is not unheard of that some sites work in the former but not the latter.

I'll do some more tests and report back when I have relevant information.

**Comment by lamarpavel** [comment]
Using the `inspector` of qutebrowser, I get one error report:

```
ipfs-webui.0.3.0.js:17  SyntaxError: Cannot declare a parameter named 't' in strict mode
```

**Comment by lamarpavel** [comment]
Just a heads-up, with the last update to `go-ipfs 0.4.0-1` (Archlinux package) the webui is now being displayed in qutebrowser and except for the "connections" tab everything seems to be working. On "Connections" I simply see `connected to 0 peers` even though `ipfs swarm peers` lists more then 10 peers and in Firefox those are also displayed in the webui.

I don't really have time to do any further analysis right now, just wanted to let you know that there was some progress.

**Comment by WindProphet** [comment]
I has a same problem in Safari on macOS. (Version 11.0 (13604.1.38.1.6))
I clone this repo with `npm start` and it can work well.

<img width="1401" alt="2017-10-26 20 39 14" src="https://user-images.githubusercontent.com/13548240/32053389-ca38bf02-ba8d-11e7-8754-2a6fb2f83fed.png">

**Comment by jeffbr13** [comment]
I'm also getting the same as @WindProphet on MacOS with both IPFS 0.4.10 and 0.4.11 installed via Homebrew:

![screenshot 2017-10-27 02 17 01](https://user-images.githubusercontent.com/558400/32083775-275cea58-babd-11e7-8d02-a7ad6da282a1.png)

I'm also getting an error with Firefox, although I'm not sure whether it's related or not:

<img width="1388" alt="screenshot 2017-10-27 02 15 22" src="https://user-images.githubusercontent.com/558400/32083787-41a1391e-babd-11e7-8066-95d05c0b8f8c.png">

**Comment by rnkn** [comment]
Given that Safari isn't based on QtWebkit, but IPFS web UI currently fails to display in Safari, should this opened as another issue?

**Comment by Stebalien** [comment]
@jeffbr13 Your Firefox issue is that you're trying to load the webui from the gateway, not the API (it's trying to parse the 404 error as JSON).

@rnkn I agree. The issues also look different. Could you open one here and close https://github.com/ipfs/go-ipfs/issues/4582?

**Comment by olizilla** [comment]
Great news! Web UI v2 works in the latest stable release of [qutebrowser](https://www.qutebrowser.org/) (tested on macOS)

**Status page**
<img width="1552" alt="screenshot 2018-09-27 16 24 23" src="https://user-images.githubusercontent.com/58871/46156727-0920b980-c272-11e8-83a6-a0bb59486bd4.png">

**Peers map**
<img width="1552" alt="screenshot 2018-09-27 16 24 16" src="https://user-images.githubusercontent.com/58871/46156731-0cb44080-c272-11e8-9d27-8baf968469df.png">
