### ISSUE TITLE
DAG Tree Data Viz

### ISSUE THREAD

**Issue by harlantwood** [ipfs-shipyard/ipfs-webui#254]
I'd be open to converting the [D3 DAG tree viz](https://github.com/ipfs/dataviz#d3-tree) into a react component for either default or optional usage in the new webui.

My bandwidth is unfortunately limited; perhaps @dignifiedquire you'd like to collaborate on this with me?  Seems like together we could each being our strengths and make something awesome.

Thinking:
- ES6+ 
- webpack
- react, redux
- the usual related suspects
- ~~maybe jsdom for testing -- experimenting with that on another project, will report back on this~~

cc @diasdavid -- thanks for mentioning in a recent hangout :+1:

**Comment by hacdias** [comment]
IPLD Explorer! #701
