### ISSUE TITLE
Improve Bundle Size

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-webui#255]
Webpack@2 adds tree shaking so we should be able to reduce our overall bundle size with it. In addition we should switch to using [lodash-es](https://www.npmjs.com/package/lodash-es) as we are using es 2015 modules and webpack@2 can then take advantage of this.

**Comment by mcmunder** [comment]
[Preact](https://github.com/developit/preact/) might be worth considering?!

**Comment by dignifiedquire** [comment]
Definitely

**Comment by mcmunder** [comment]
I could give it a try next week!? Let's see if I get it to run so I can measure the effects on bundle size etc...  What would be the official procedure?

**Comment by dignifiedquire** [comment]
try it out, post your findings and make a pr :)

**Comment by dignifiedquire** [comment]
hey @mcmunder did you get to try it out? I have been using preact in a new project and it is really nice

**Comment by mcmunder** [comment]
@dignifiedquire unfortunately I didn't find the time so far ;-( Too much work! But it's high up on my want to do list!

**Comment by tadeaspetak** [comment]
Regarding the initial comment: As far as I can see, webpack@3 is now used in the master and so is `lodash-es`. Are there any other library updates that should be done right now?

I would like to start contributing to the project. @mcmunder @dignifiedquire Should I look into using (preact)[https://github.com/developit/preact]? Does anyone have any experience with [inferno](https://github.com/infernojs/inferno)? It claims to be 1,5x faster than Preact even (about 5x faster than React).

**Comment by mcmunder** [comment]
@tadeaspetak unfortunately I did not find any time to look into this - despite my enthusiastic earlier comments... So from my side: go ahead! I don't have any experience with inferno but it looks very promising indeed!

**Comment by olizilla** [comment]
Web UI v2 is uses the `create-react-app` tooling which includes webpack with all the tree-shaking and bundle splitting fancies. We've enabled https://github.com/siddharthkp/bundlesize checks on CI so we get warnings when we bloat up, and we check new deps on https://bundlephobia.com/ beforehand.

I'm not a massive CRA fan but it has worked well for us and we wanted to make sure that we run into any issues building an IPFS app on it before we get dozens more i issues about it when it doesn't.
