### ISSUE TITLE
Captain.log

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-webui#259]
# Log - February 24th

> “Commitment is an act, not a word”
>  -- Jean-Paul Sartre

All the work is being done on the [`redux`](https://github.com/ipfs/webui/tree/redux) branch at the moment. Generally work is divised by the different
pages of the webui which are
- Home
- Peers
- Files
- DAG Browser
- Config
- Logs

The main work for the **Home**, **Logs** and **Peers** page are done. They are only missing more tests for the visual components found in `app/scripts/components` and the containers found in `app/scripts/containers`.

My next step will be to implement the **Files** page, which will be functionaly
based very different than the previous files browser. The new version will be
based entirely on the new files api in `0.4.0` and bring features similar to
what you are used to on Dropbox, including
- a files previewer (Markdown, images, videos, code files),
- drag 'n drop file upload,
- inline folder creation,
- inline renaming,
- copying files and
- moving files.

This work will supersede #212
## Shout out
- To @suisha for writing tests for the visual components.
## Where can I help?
- **Write tests**: Seriously this is super important, I'm trying to write as
  many tests as I can going along but I'm not covering everything and
  there is a good amount to be covered.
- **Test it out**: Clone it, run it and report issues that you find.
- **Implement features**: I will be working on the `Files` page next, but if
  you feel adventurous leave comment on the PR saying that you want to work
  on page **X** so everybody knows what's happening.

**Comment by harlantwood** [comment]
Brief update from @Dignifiedquire here: https://github.com/ipfs/webui/pull/362#issuecomment-217116845

**Comment by diasdavid** [comment]
@hacdias you should share a new update in the Captain.log :)  //cc @lidel

**Comment by olizilla** [comment]
Farewell Captain.log. I will write up The New Adventures of Web UI as release notes. Hopefully that'll get some eyes on it and set up a good tradition for future maintainers to follow.
