### ISSUE TITLE
file add result/ipfs path disappears after a few seconds

### ISSUE THREAD

**Issue by chpio** [ipfs-shipyard/ipfs-webui#360]
hi,

i just added (or tried to add) a large file (1.4GB) this took a lot of time so i switched to another browser tab after switching back the path was obviously gone... so please add a button to dismiss the message but not let it disappear without user interaction.

a progress feedback would be nice to have too (or at least a "processing icon").

**Comment by dignifiedquire** [comment]
Thanks for the report, we are working on improving the user experience of the whole file adding process. I will keep this in mind.

**Comment by hacdias** [comment]
The coming version (2.0.0) does have a brand new file manager with feedback during upload/adding. 😄
