### ISSUE TITLE
add a 'local' tab

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/ipfs-webui#41]
I would love to have a tab on the webui that gives you a file browser type thing into `/ipns/local` and allows you to do a lot of the same things you'd be able to do in a normal file browser. 

features i want:
- view files and folders
- drag files into the browser to put them at that location
- delete files
- edit files
- move files around
- right click files to add metadata, rename, etc

**Comment by jbenet** [comment]
Yeah, this SGTM.

**Comment by dignifiedquire** [comment]
@whyrusleeping what would be the difference between the files api and `/ipns/local`

**Comment by Kuurusch** [comment]
Yea, that would be a great feature!!
Want it too :)

**Comment by hacdias** [comment]
The coming version (2.0.0) has this 😄
