### ISSUE TITLE
Path resolve error for translations

### ISSUE THREAD

**Issue by RichardLitt** [ipfs-shipyard/ipfs-webui#483]
This is a copied issue from https://github.com/ipfs/go-ipfs/issues/2609. . 

From @leochan007:

> when access via 5001/webui got this output:
> ERROR core/serve: Path Resolve error: no link named "webui-zh.json" under QmcnV8mXz9B4kuNEUymZ2mhqDLy2e76iMMk8SnmPDnxp6H gateway_handler.go:510

@dignifiedquire:

> sounds like the shipped version doesn't serve/contain webui-zh.json

@thenain38:

> @dignifiedquire Same for french (e.g. webui-fr.json)

@dignifiedquire:

> You can see the list of supported locales here: https://github.com/ipfs/webui/tree/master/dist/locale if it's not in there it will fail (it will try for every locale and if it does not find it use the default english one)

**Comment by hamasugu** [comment]
Same for japanese (e.g. webui-ja.json)

**Comment by hacdias** [comment]
Closing language related issues in favor of #675.
