### ISSUE TITLE
Progress feedback, loading animation

### ISSUE THREAD

**Issue by krl** [ipfs-shipyard/ipfs-webui#49]
We should have some kind of loading animation, when objects are being resolved etc.

Also, a way to set context timeout to something much lower would be great for ux.

**Comment by olizilla** [comment]
We have some loading spinners now, but we need to do much more to show the user that their request is "going out to a network of peers that are trying to help answer your question, so, like just wait a little longer... I mean, look at all this amazing p2p work going on!" rather "loading plz wait. you are in a queue. your call is important to us"

I'm closing this out in favour of creating some more specific issues on the subject as we get time.
