### ISSUE TITLE
Error uploading XML file

### ISSUE THREAD

**Issue by vensa-emonzon** [ipfs-shipyard/ipfs-webui#569]
I am trying to upload an XML using the webui with the content of the PDF file attached (funny enough this page didn't allow me to update the XML file, so, I ended up printing it as a PDF for you to have a look at the content). Before it finishes uploading it throws this error:

Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.24/tcp/4001
Swarm listening on /ip4/192.168.50.1/tcp/4001
Swarm listening on /ip4/192.168.56.1/tcp/4001
Swarm listening on /ip4/192.168.99.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/fd6a:f97c:3cf6:1:49e:333c:903c:871d/tcp/4001
Swarm listening on /ip6/fd6a:f97c:3cf6:1:5d70:a134:c2e9:bfc4/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
[0;37m15:57:38.981 [31mERROR [0;34mcore/serve: [0mPath Resolve error: not a key [0;37mgateway_handler.go:509[0m

[sample.pdf](https://github.com/ipfs/webui/files/584932/sample.pdf)

**Comment by olizilla** [comment]
Hi @vensa-emonzon! Sorry you didn't get any feedback on this error. A lot has changed in IPFS and the Web UI since you reported this issue, so I'm going to close this out, but if it happens again, please feel free to open another issue with steps to recreate it.
