### ISSUE TITLE
Update check mechanism

### ISSUE THREAD

**Issue by Kubuxu** [ipfs-shipyard/ipfs-webui#580]
As WebUI is mostly under go-ipfs `/webui` redirect it would be awesome if it queried the `/webui` and check if it is different than current page so updates are detected and user is notified that new version is available.

**Comment by olizilla** [comment]
We want an update mechanism for Web UI. There is some previous discussion on this https://github.com/ipfs-shipyard/ipfs-webui/issues/167

**Comment by olizilla** [comment]
Closing in favour of #167
