### ISSUE TITLE
Multiple links to the same multihash are listed only once

### ISSUE THREAD

**Issue by l3kn** [ipfs-shipyard/ipfs-webui#587]
When viewing an object with multiple links (w/ different names) to the same multihash,
only one of the links is shown:

![webui](https://cloud.githubusercontent.com/assets/2060269/24841456/9947b4f2-1d85-11e7-86a2-83cd17a910a4.jpg)

while the command line tool shows all the links:

![console](https://cloud.githubusercontent.com/assets/2060269/24841462/b0aa29c2-1d85-11e7-9684-115a644bd63b.jpg)

From a quick look, it seems like the problem is in
[object-links.js](https://github.com/ipfs/webui/blob/master/app/scripts/views/object/object-links.js#L23).

``` javascript
{links.map((link) => <ObjectLink key={link.multihash} path={path} link={link} />)}
```

I think because there are multiple `ObjectLink`s with the same key,
react throws away all but one.

A simple fix would be to use `link.multihash` + `link.name` as a key.

Is this an intended feature? If not, I'd be happy to create a pull request that fixes this.

**Comment by diasdavid** [comment]
@l3kn I believe I fixed this with https://github.com/ipfs/webui/pull/595

Minding testing again and or even better, adding a test?

Thank you!

**Comment by hacdias** [comment]
This is working here @diasdavid, I think this could be closed.
