### ISSUE TITLE
Show alternative connections mapping that doesn't require WebGL

### ISSUE THREAD

**Issue by JayBrown** [ipfs-shipyard/ipfs-webui#589]
I'm connected to lots of peers—

```
ipfs swarm peers | wc -l | xargs
353
```

—many hundreds more over time, but the WebUI shows zero. Some error on my end? (ipfs 0.4.8, proto 0.1.0, Safari 10.1, OS X 10.11.6, Adguard Desktop enabled)

<img src="http://i.imgur.com/Qn0IuLJ.png"/>

EDIT: I'm on an old mid-2010 MBP, running on integrated GPU only, so some graphical stuff might not be supported, but the WebUI should at least print out the number of peers I'm connected to, right?

**Comment by leerspace** [comment]
How long are you waiting on that page before giving up? There seems to be a performance issue with that page that makes it take a while to load.

**Comment by JayBrown** [comment]
I checked it again, and it seems that WebGL is the problem. I had disabled it, and when I reenabled WebGL, the IPFS UI started to load the globe, but that resulted in an immediate kernel panic. (It's the usual GUI-catastrophe courtesy of Apple on some older MacBook Pro models.) I'm not sure who the bad guy is here: either Apple is to blame, in that their implementation of WebGL activates the discrete graphics card (which can result in a GPU-induced kernel panic), or the IPFS WebUI code itself is too "modern" regarding the code, and it doesn't take older Mac hardware into account.

I guess you can program your way around it, i.e. IPFS will deted WebGL enabled or disabled, and if it's the latter, it loads a simple text page, not those poser animated graphics. :)

**Comment by diasdavid** [comment]
I've updated the title of this issue to `Show alternative connections mapping that doesn't require WebGL`. We definitely should support a way to render the peers without requiring too many resources from the user machine.

**Comment by hacdias** [comment]
The coming version doesn't use WebGL so I'm closing this.
