### ISSUE TITLE
Reconsider silly "security" practicies

### ISSUE THREAD

**Issue by dsvi** [ipfs-shipyard/ipfs-webui#594]
According to the issue:
https://github.com/ipfs/webui/issues/591
The WebUI has weird "security protection mechanism" in the form of hardcoded 'localhost' strings in it's javascript. 
This really is a weak security feature (to put it mildly) and causes more problems than it solves. In fact, it solves none.
I do believe this should be reconsidered.

**Comment by diasdavid** [comment]
Hi @dsvi, there is, in fact, a conversation happening about API tokens for apps like the WebUI and others, see: https://github.com/ipfs/go-ipfs/issues/1532

Consider joining the conversation. The current mechanism is not the best, but it is not creating issues other than the one that it is there for, limiting access to the webui from an outside node.

Remember, Webui is just a webpage, you can always change that value, add it to IPFS and use it in your node.

**Comment by dsvi** [comment]
Hi!
"it is there for, limiting access to the webui from an outside node."
You don't seem to get the point. The web UI is accessible from an outside node anyways. Even now with the hardcoded localhost in it. (if you have configured the go-ipfs appropriately) The problem is, the Web UI is useless this way. Which renders ipfs browser extensions useless, if you don't run ipfs on the same computer, on which you are browsing.
The API tokens are unrelated issue. API is already accessible outside. No reason to make the WebUI ubusable.

**Comment by myfingerhurt** [comment]
1.  Change your API address has your wish like this, 
`10.9.8.9` is my VPN remote address which hosts the IPFS.
``` 
 "Addresses": {
    "API": "/ip4/10.9.8.9/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
```
2. Then run this in your console:
```
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]"

# The following two lines are not necessary, but you know in case you need it.
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "[\"true\"]"
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods "[\"PUT\", \"POST\", \"GET\"]"
```

3. Open a browser you will be finally able to access your IFPS
```
http://10.9.8.9:5001/webui
```

**Comment by olizilla** [comment]
Closing in favour of https://github.com/ipfs-shipyard/ipfs-webui/issues/836
