### ISSUE TITLE
Change the display of Connections page

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#606]
Connections page can cause a small or big amount of lag depending on how many peers are connected. Errors were already reported on #76, #320 and #589. What about doing something like what we can see on #229?

![image](https://user-images.githubusercontent.com/5447088/32981913-4b6d9ae2-cc73-11e7-9d80-5afae8760dde.png)

I could make some changes and open a PR. 

/cc @diasdavid

**Comment by Stebalien** [comment]
This would be really nice. The globe is cool but eats CPU like nothing else. Actually, have you seen the later visual on that PR (https://github.com/ipfs/webui/pull/229#issuecomment-285348083)? It shows a map instead of a globe.

/cc @dignifiedquire

**Comment by hacdias** [comment]
Yup! I really enjoy the screenshots on that PR. It's a shame it didn't go forward. 😞 But we could do something like that!!

**Comment by Stebalien** [comment]
You could probably steal a lot of code from it (although it has diverged significantly at this point).

**Comment by diasdavid** [comment]
We went into great length about this in the past so I believe I can save you some bikeshedding time:

- Yes, it is ok to default to the map (less CPU hungry), however, do not throw the globle away, put it hidden behind a button.
- Yes to the refreshed list of peers.
