### ISSUE TITLE
Rename and delete buttons mashed together

### ISSUE THREAD

**Issue by Stebalien** [ipfs-shipyard/ipfs-webui#609]
![2017-12-02-144104_943x378_scrot](https://user-images.githubusercontent.com/310393/33520386-d3967792-d7b1-11e7-92b7-f6bb63964a61.png)

**Comment by hacdias** [comment]
Thanks for noticing this. 😄

**Comment by hacdias** [comment]
The coming version (2.0.0) fixes this 😄
