### ISSUE TITLE
Download button will not download the source file, but download zip file instead

### ISSUE THREAD

**Issue by gogogo237** [ipfs-shipyard/ipfs-webui#621]
I upload a docx file. But when I want to download, it download a zip file instead. I have to manually change .zip to .docx.
![image](https://user-images.githubusercontent.com/6381154/35155977-5af8ba0a-fd6a-11e7-8c24-061b15216156.png)

**Comment by hacdias** [comment]
The coming version (2.0.0) fixes this 😄
