### ISSUE TITLE
hjs-dev-server Error

### ISSUE THREAD

**Issue by Retch** [ipfs-shipyard/ipfs-webui#624]
I've installed node (6.12) and npm (3.10), checked with node -v and npm -v, and then at pm start i get this error:

user@vps:~/webui$ npm start

> ipfs-webui@0.3.0 start /home/user/webui
> hjs-dev-server

sh: 1: hjs-dev-server: not found

npm ERR! Linux 2.6.32-042stab127.2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ipfs-webui@0.3.0 start: `hjs-dev-server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ipfs-webui@0.3.0 start script 'hjs-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs-webui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hjs-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipfs-webui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipfs-webui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/webui/npm-debug.log

**Comment by hacdias** [comment]
Did you run `npm install` before to install the dependencies?

**Comment by Retch** [comment]
Yes of course. I ran now sudo npm install, but errors again. It often says to me this:
> ipfs-webui@0.3.0 start /home/retch/webui
> hjs-dev-server

sh: 1: hjs-dev-server: not found

**Comment by Retch** [comment]
I don't know how anymore, but i got it working. But it's long to remember.
Thanks anyway👍

2018-03-03 19:22 GMT+01:00 Henrique Dias <notifications@github.com>:
