### ISSUE TITLE
ERROR core/serve "no link named"

### ISSUE THREAD

**Issue by Simoneth** [ipfs-shipyard/ipfs-webui#627]
My error:

`11:23:52.590 ERROR core/serve: ipfs resolve -r /ipfs/QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ/locale/webui-it.json: no link named "webui-it.json" under Qmc6bAsXTFFdvV3RoLuf6jjV3jzsRLntfsivWQZ75s8QaL gateway_handler.go:621`

I saw [here ](https://github.com/ipfs-shipyard/ipfs-webui/tree/master/dist/locale) that `webui-it.json` is not whitelisted, so how can I switch it? What's the solution?

**Comment by hacdias** [comment]
@Simoneth I'm not sure if I understood what you said. There is no translation for Italian right now, so you can't change to it. But if you'd like to create one, be welcome 😄
