### ISSUE TITLE
No content in the webui

### ISSUE THREAD

**Issue by djh82uk** [ipfs-shipyard/ipfs-webui#628]
Hi, I have the same issue as here: https://github.com/ipfs-shipyard/ipfs-webui/issues/157

I have added the API settings and listen port as on that post, and I can load the webui, but it contains no info.

It is running on a headless server

```
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/10.0.0.245/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmNpprVJP3beQkmX2VGB5K9hVtsEuDHtZ9YTLK1HUentME
Swarm announcing /ip4/10.0.0.245/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/10.0.0.245/tcp/5001
Gateway (readonly) server listening on /ip4/10.0.0.245/tcp/8080
Daemon is ready
```

**Comment by hacdias** [comment]
Hello @djh82uk! In which address are you accessing Web UI?

**Comment by djh82uk** [comment]
Hi, I am using http://10.0.0.245:5001/webui

**Comment by diasdavid** [comment]
@djh82uk you need to use `localhost:5001`, it is the only address that is whitelisted (127.0.0.1 also doesn't work)

**Comment by djh82uk** [comment]
Hi, I edited the config to allow connections from other than localhost.  It's a headless server so accessing from localhost is not an option.  The API is also set to listen on the network IP

**Comment by djh82uk** [comment]
Anyone got any thoughts on this? I can't be the only one running it on a headless server?

**Comment by kiahmed** [comment]
i have running both  ui and daemon locally, still can't connect

**Comment by lidel** [comment]
Editing config is not enough -- AFAIK it is hardcoded to localhost.

See: 
- https://github.com/ipfs-shipyard/ipfs-webui/issues/591
- https://discuss.ipfs.io/t/how-can-i-enable-remote-connection-to-webui/698

**Comment by olizilla** [comment]
Closing in favour of https://github.com/ipfs-shipyard/ipfs-webui/issues/836
