### ISSUE TITLE
can't connect to daemon

### ISSUE THREAD

**Issue by kiahmed** [ipfs-shipyard/ipfs-webui#634]
configured everything right daemon is  running with api, gateway and swarm .still can't connect from locally get this error always
![capture](https://user-images.githubusercontent.com/28849607/36932768-30ed4066-1e9c-11e8-9fa7-fd01d5287a67.PNG)

**Comment by hacdias** [comment]
Did you set `API.HTTPHeaders` with the correct values on your IPFS repo?

**Comment by kiahmed** [comment]
yup..here it looks like

    "HTTPHeaders": {
      "Access-Control-Allow-Credentials": ["true"],
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range"
      ],
      "Access-Control-Allow-Methods": [
        "GET","PUT","POST"
      ],
      "Access-Control-Allow-Origin": ["*"]      
    },

**Comment by hacdias** [comment]
Are you running the API on the same host and port as you're accessing the WebUI?

**Comment by kiahmed** [comment]
yup, where in webui project I see if its connection to right host/port? assume it tries with default localhost 5001?

**Comment by kiahmed** [comment]
well, i guess its solved by simply clicking http://localhost:5001/webui and it works. why we need to deploy webui separately on port 3000 then?

**Comment by hacdias** [comment]
The port 3000 is only for development purposes or to run the latest version from this repository. If you just want to access the latest published version, you just need to follow the link you mentioned. 😄 

Can we close this?
