### ISSUE TITLE
Update WebUI version on next version of go-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-webui#644]
@Stebalien @whyrusleeping @lgierth can we have the webui version be updated in the next version of go-ipfs? I believe it has been a while :)

**Comment by Stebalien** [comment]
In the next-next version, yes. We've frozen this one (hopefully releasing tomorrow? :crossed_fingers:). However, I'd like to get the next one out within a few weeks (preferably, a week).

**Comment by whyrusleeping** [comment]
Yeah, I'd love to get back into a 2 or 3 week release cycle. We've got a bit more firepower now, let's see if we can pull it off again

**Comment by hacdias** [comment]
Closing in favour of #749
