### ISSUE TITLE
Upload progress bar?

### ISSUE THREAD

**Issue by nsuchy** [ipfs-shipyard/ipfs-webui#650]
Hi. I use a VPS as an IPFS Node and use SSH Port forwarding to access the WebUI, its difficult to know when a file has completed uploading, by any chance could a progress bar be added?

**Comment by hacdias** [comment]
@nsuchy right now, the future of WebUI is being decided and we will probably do a complete revamp. Could you please take a look at https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/9 and leave a comment there with this suggestion? 😄

**Comment by lidel** [comment]
I am quite sure upload progress bar will be added during the revamp :)
(Low level support for reporting upload progress was added to js-ipfs-api lib some time ago)

ps. make sure to check also:
- Design: Pinning Content https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/10
- Design: Add files to IPFS https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/35#issuecomment-373929197
