### ISSUE TITLE
ipfs mount didn't work.

### ISSUE THREAD

**Issue by dalmooria** [ipfs-shipyard/ipfs-webui#652]
Hi, I watched IPFS Alpha Demo.
But ipfs mount shows error.

Joui-MBP:~ jo$ ipfs --version
ipfs version 0.4.14

Joui-MBP:~ jo$ ipfs mount

> Error: unable to check fuse version.
>
>Dear User,
>
>Before mounting, we must check your version of OSXFUSE. We are protecting
>you from a nasty kernel panic we found in OSXFUSE versions <2.7.2.[1]. To
>make matters worse, it's harder than it should be to check whether you have
>the right version installed...[2]. We've automated the process with the
>help of a little tool. We tried to install it, but something went wrong[3].
>Please install it yourself by running:
>
>	go get github.com/jbenet/go-fuse-version/fuse-version
>
>You can also stop ipfs from running these checks and use whatever OSXFUSE
>version you have by running:
>
>	ipfs config DontCheckOSXFUSE true
>
>[1]: https://github.com/ipfs/go-ipfs/issues/177
>[2]: https://github.com/ipfs/go-ipfs/pull/533
>[3]: exit status 2
>#github.com/jbenet/go-fuse-version
>../dev/go/src/github.com/jbenet/go-fuse-version/version_darwin.go:6:11: fatal error: 'fuse/fuse.h' file not found
> #include <fuse/fuse.h>
>          ^~~~~~~~~~~~~
>1 error generated.

So, I install it. But didn't work too.

Joui-MBP:~ jo$ go get github.com/jbenet/go-fuse-version/fuse-version
>#github.com/jbenet/go-fuse-version
>dev/go/src/github.com/jbenet/go-fuse-version/version_darwin.go:6:11: fatal error: 'fuse/fuse.h' file not found
> #include <fuse/fuse.h>
>          ^~~~~~~~~~~~~
>1 error generated.

ipfs config DontCheckOSXFUSE command hangs...

Joui-MBP:~ jo$ ipfs mount

>^C
>Error: Post http://127.0.0.1:5001/api/v0/mount?encoding=json&stream-channels=true: context canceled

**Comment by VictorBjelkholm** [comment]
Have you installed https://osxfuse.github.io/?

**Comment by hacdias** [comment]
This is unrelated to IPFS WebUI. Try opening this on go-ipfs repo and check out what @VictorBjelkholm mentioned, please.
