### ISSUE TITLE
Error writing block to datastore:

### ISSUE THREAD

**Issue by jamie0828** [ipfs-shipyard/ipfs-webui#655]
I have installed ipfs in my system(win 10). Once I access "localhost:8080/ipfs/QmX7M9CiYXjVeFnkfVGf3y5ixTZ2ACeSGyL1vBJY1HvQPp/mdown" ,the ipfs console show "[0;37m16:29:03.360 [31mERROR [0;34m bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:385[0m"
And then the explorer show error:
ipfs resolve -r /ipfs/QmX7M9CiYXjVeFnkfVGf3y5ixTZ2ACeSGyL1vBJY1HvQPp/mdown: Failed to get block for QmdxzgBtiocRhGdJSjwtWhGVZtTB9fE5XvQZmrMaenjzV9: context deadline exceeded
Is it a bug?

**Comment by olizilla** [comment]
Hi @jamie0828 sorry no one was able to answer your question here. It sounds like an issue with you IPFS install, but this is the issue tracker for the Web UI app. You'll have more luck finding the answer on the IPFS discuss forum https://discuss.ipfs.io/
