### ISSUE TITLE
Add support for multiple languages since the beginning

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#675]
We should add a library to support multiple languages right from the beginning to make it easier to expand after this revamp is finished. What do you think?

/cc @olizilla @lidel @alanshaw

**Comment by lidel** [comment]
Keep in mind that setting up a unified crowdsourcing website for all GUI apps should be done at the end of revamp endeavor to decrease noise/breaking changes until we have all screens implemented.

Until then, there are things we should do first:
- [ ] research and pick i18n library that uses **future-proof format**
  - the most popular seems to be [yahoo/react-intl](https://github.com/yahoo/react-intl) and they use ICU format:
     - http://userguide.icu-project.org/formatparse/messages
     - http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html
     - https://blog.crowdin.com/2016/11/09/icu-syntax-in-crowdin
  - are there better alternatives?
- [ ] create English translation by moving existing text from app to locale files
  - from this point forward all new labels will be added to English locale

Digression: The key is to respect time of translators and do not ask from contributions until we are sure locales work as expected and _won't change drastically_. For example, when initial revamp work is done, we could smoke-test translation process by adding Polish and Portuguese locales to iron out all kinks before opening project to accepting external translations via crowdsourcing site.

**Comment by lidel** [comment]
I think we've done it all :sparkles: :rocket:

We now have a fancy crowdsourcing website for translations (context: https://github.com/ipfs/ipfs-gui/issues/50):
- https://www.transifex.com/ipfs/public/
