### ISSUE TITLE
browser memory leak and cpu usage

### ISSUE THREAD

**Issue by ThomasWaldmann** [ipfs-shipyard/ipfs-webui#68]
I am using Firefox (latest release, on Linux) and when using /webui I see the RES memory size in top climbing at about 1MB/s.

Also, the browser eats quite some CPU (even if the globe is not showing, but just a static page).

So, what is causing this?

**Comment by jbenet** [comment]
Not sure, did you visit the logs page?



—

**Comment by ThomasWaldmann** [comment]
No. And logs page doesn't show anything for me anyway.

But I found that it is the "connections" page (the one with the 3D globe + peers list). When visiting that, memory consumption starts climbing. Even if I visit another page (e.g. config), it keeps climbing.

**Comment by jbenet** [comment]
interesting. we should definitely gc the page after navigating away. i guess this is not happening.

**Comment by facastagnini** [comment]
This issue seems to be covered in #213 right?

**Comment by ThomasWaldmann** [comment]
@facastagnini No, it is not.

**Comment by olizilla** [comment]
The Web UI has been rebuilt. The webGL globe is dead. Long live the [d3.geoEquirectangular](https://github.com/d3/d3-geo#geoEquirectangular) projection! 

![ipfs-webui-peers](https://user-images.githubusercontent.com/58871/46155034-513ddd00-c26e-11e8-9f1e-645bc4b04466.png)

We can do more to reduce the amount to system resources it consumes and I need to re-work the way we cache geo-ip look ups for plotting. I'm going to close this issue out, but feel free to open new ones if you find leaks.
