### ISSUE TITLE
ipfs daemon error

### ISSUE THREAD

**Issue by diegoenriquesantos** [ipfs-shipyard/ipfs-webui#724]
When is running "ipfs daemon" after a few minutes the wifi internet connection is broken and the following error appears:
14:00:25.898 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:139
![captura de pantalla de 2018-07-15 18-57-51](https://user-images.githubusercontent.com/10709020/42738835-06a074f2-8861-11e8-88f6-44de84684700.png)

**Comment by hacdias** [comment]
Hello @diegoenriquesantos! That issue should be on [go-ipfs](https://github.com/ipfs/go-ipfs/issues) repository and not here please. It doesn't seem to be related to WebUI

**Comment by diegoenriquesantos** [comment]
Ok @hacdias I close this issue and will open the same in [go-ipfs](https://github.com/ipfs/go-ipfs/issues). Regards.

**Comment by hacdias** [comment]
Thanks!
