### ISSUE TITLE
No files displayed in the browser

### ISSUE THREAD

**Issue by eloudsa** [ipfs-shipyard/ipfs-webui#725]
Hello

I had an older version of IPFS (0.4.11) with a bunch of files.
The Files Explorer was able to display the files stored into my local storage.

![screenshot 2018-07-16 13 12 12](https://user-images.githubusercontent.com/300818/42758205-0942fa3e-8903-11e8-92c8-fb5c234dadc1.png)

After upgrading to 0.4.16, the Files Explorer is not displaying my files anymore.

![screenshot 2018-07-16 13 20 01](https://user-images.githubusercontent.com/300818/42756594-23ab0336-88fd-11e8-986e-0a2a2bcb2a4e.png)

Did I miss something during the update process?

Thanks

Said

**Comment by Stebalien** [comment]
We've changed the `Files` panel to display files stored in MFS (take a look at the `ipfs files` commands). I'm not sure but it looks like that panel *used* to list all recursive pins (everything listed by `ipfs pin ls --type=recursive`). If you'd like, you can *add* those to MFS by running:

```bash
ipfs files mkdir /pins/
for p in $(ipfs pin ls -q --type=recursive); do
    ipfs files cp /ipfs/$p /pins/
done
```

That will add all of your the files/folders you've added to IPFS to the `/pins/` directory in MFS.

**Comment by eloudsa** [comment]
Hi @Stebalien 

It works.

Thanks for your help!

**Comment by hacdias** [comment]
Closing this! Thanks @Stebalien
