### ISSUE TITLE
We lost our CI on revamp

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#727]
Hello!

@VictorBjelkholm recently removed CircleCI from all IPFS projects. Should we start using jenkins on Revamp branch?

/cc @olizilla

**Comment by VictorBjelkholm** [comment]
For sure :) Unless there is a reason why not

**Comment by hacdias** [comment]
What is needed to setup Jenkins for this project and run the equivalent commands we were running on Circle? @VictorBjelkholm

**Comment by hacdias** [comment]
let's continue this on #728

**Comment by olizilla** [comment]
We're using travis & jenkins. 

- Travis gets us bundlesize warnings and supports puppeteer tests without any work. J
- Jenkins lints, tests and builds out the site on PR and adds it to ipfs, and updates the dnslink for webui.ipfs.io when master changes
