### ISSUE TITLE
UI thinks my daemon isn't running

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ipfs-shipyard/ipfs-webui#737]
After running npm install and npm start, the web ui tells me `Failed to get configured IPFS gateway. Is the IPFS daemon running?` and `Failed to determine local IPFS version. Is the IPFS daemon running?`. My daemon is running, and I have the companion on and working. What could be causing this error?

**Comment by olizilla** [comment]
It could be a CORS issue... have you added CORS config as per https://github.com/ipfs-shipyard/ipfs-webui#config-your-ipfs-daemon

Are you running your ipfs daemon with the default config? When you run `ipfs daemon` what is listed out as the API address? Do you see:

```
API server listening on /ip4/127.0.0.1/tcp/5001
```

**Comment by VictorBjelkholm** [comment]
@olizilla slightly offtopic, but could we make the port configurable either via the UI (and saved as a cookie/localstorage) or via env vars? Had to manually edit `src/bundles/ipfs.js` to include the port as I don't run with default ports.

**Comment by hacdias** [comment]
@VictorBjelkholm I think that's on track: https://github.com/ipfs-shipyard/ipfs-webui/pull/715 😄

**Comment by makeworld-the-better-one** [comment]
@olizilla that fixed it,thanks.

**Comment by CallMeLaNN** [comment]
CORS, good point.

I'm trying share.ipfs.io without npm but I got the same error at stock IPFS webiu, localhost:5001. So I add it also into the CORS origin:

    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://localhost:3000", "http://localhost:5001", "https://share.ipfs.io"]'
