### ISSUE TITLE
TOO MUCH PEERS

### ISSUE THREAD

**Issue by aarassen** [ipfs-shipyard/ipfs-webui#745]
connected to 800 peers
how to make it just 100????
and thank's

**Comment by lidel** [comment]
You can limit the number of connections by enabling Connection Manager:
https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#connmgr

For example, to keep between 200 and 400, set your config to include:

```json
"ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 400,
      "LowWater": 200,
      "Type": "basic"
    },
```

**Comment by olizilla** [comment]
Hope that helps. Please start a thread on https://discuss.ipfs.io if you have more questions.
