### ISSUE TITLE
Web UI revamp - User testing plan

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#746]
- [x] Define the tasks that the app should make easy, and those it should make possible. 
- [x] Write a high level user testing plan ([similar to how 18F does it](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-plan.md))
- [ ] Schedule 4 user testing sessions.
- [ ] Document the sessions, and present and discuss feedback with the gui-team.
- [ ] Raise issues for UX issues discovered
- [ ] Fix and Repeat!

**Comment by meiqimichelle** [comment]
🎉🎉🎉 `Fix and Repeat!` 🎉🎉🎉

**Comment by olizilla** [comment]
See #816

**Comment by olizilla** [comment]
The usability test script is ALIVE https://github.com/ipfs-shipyard/ipfs-webui/tree/master/docs/usability
