### ISSUE TITLE
File browser polishing

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#748]
- [x] Ignore common system files when adding directories. Specifically `.DS_Store` files on osx. If you know of an similar windows os metadata files that should generally be ignored, then those too. (56106551425b72e1af05c6f18172c6fc7d0e3469)

- ~~Sort by name should only sort by name. We can sort by kind (folders first then files) by default, but if the user selects sort by name it should do that regardless of their kind. We may need to introduce a "kind" column so that the user can return the sort to "by kind" if they want, but I'd love to find a less redundant way.~~ Skip for now. See https://github.com/ipfs-shipyard/ipfs-webui/issues/748#issuecomment-413955567

- [x] fix breadcrumb position jumping up a few pixels when navigating to a file preview page. (acdd1dd438ab5e1968b5fc7d34b08c4dcc6ad43d)

- [x] Display cumulative sizes for directories (9218fea291359f08066f59a6177fbd96185be6a4)

- [x] focus the first item in the file list and add a focus state. (95ea3c7 - just click arrow up or down when nothing is focused).

- [x] add keyboard navigation for up and down arrow keys to navigate up and down the list, and enter to drill down into a folder or file. Meta key + down should also drill down. (95ea3c7)

- [x] replace "Root" in breadcrumb with a home icon (like https://icon.now.sh/home) (39b5de0)

- [x] Add a quick slide-in from bottom animation to the multi select actions bar when it appears (e95d95fdb81d11f00343f9fa41ef42da4b5b74c8)

- [x] When previewing images and videos, don't show the media larger than it's natural resolution. Use `max-width:100%`. Right now they always take up the full width, which looks neat, but small images get super distorted, and most images and videos end up much taller than the available screen height, on my laptop screen at least. (333eb883567de1e0cebd58ea82abe706cf53dc83)

- [x] match breadcrumb underline color to the dag-pb color. See: https://github.com/ipfs-shipyard/ipld-explorer/issues/27 (81e58024e12fe70902d21d60ea8ec263c128d94c)

**Comment by olizilla** [comment]
@hacdias let me know if any of this isn't doable or you have other ideas.

**Comment by hacdias** [comment]
> Ignore common system files when adding directories. Specifically .DS_Store files on osx. If you know of an similar windows os metadata files that should generally be ignored, then those too.

And what if the user wants to upload them even if it's unusual? This is easy to do though: just have a list and filter by name.

> Sort by name should only sort by name. We can sort by kind (folders first then files) by default, but if the user selects sort by name it should do that regardless of their kind. We may need to introduce a "kind" column so that the user can return the sort to "by kind" if they want, but I'd love to find a less redundant way.

Windows Explorer, Google Drive, Dropbox, all separate folders from files and do it the way we're doing. Windows Explorer and Dropbox put the folders in the bottom when ordering in a descending way. 

I think we should leave that as it is or just put the in the bottom when ordering in a descending way. I think it makes sense to separate folders from files because they're different things and usually the user knows what he's/she's looking for.

**Comment by olizilla** [comment]
I have never wanted to upload a .DS_Store file. I'm happy to make the call that the webui should ignore them. If someone really wants to add the .DS_Store files, then we can direct them to the CLI for now.

Dropbox (on there web ui, for me at least) and OSX finder sort items by name. Google drive and Windows Explorer sorts by kind then by name. I find it confusing when sort by name doesn't sort things by name particularly I have more than a screen height full of directories, so the file I'm looking for is below the fold, and next to things that start with the same letter.

**Comment by hacdias** [comment]
Apparently, as we've seen, Dropbox sorts the mac way on mac and separates files from folders on the other platforms. I suggest we do the same for now, and in the future we can add more sorting options.

**Comment by hacdias** [comment]
@olizilla I think we can *close* this issue and tick the first item on #749!

**Comment by olizilla** [comment]
Done!
