### ISSUE TITLE
Display help when pressing '?'

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#756]
Current shortcuts:

- ESC - Unselect everything.
- F2 - Rename selected.
- Del - Delete selected.
- Enter or Meta+Arrow Right - Open selected.
- Arrow up/down - Focus files.

/cc @lidel

**Comment by olizilla** [comment]
What help are you thinking of here? A list of keyboard commands?

**Comment by lidel** [comment]
Yes, supported keyboard shortcuts. 
My idea was to do something similar to pressing <kbd>?</kbd> in Gmail, but less ugly :sparkles:

**Comment by lidel** [comment]
I wonder if we should support moving to menu navigation via left/right arrows.
Right now if I want to open Files screen I need to use mouse, would be super useful to make it possible to switch between screens via keyboard alone. 

cc @terichadbourne

**Comment by terichadbourne** [comment]
I love the focus on keyboard users here. 

In general, I presume that sticking to the common methods they use (for example, tab to focus on the next thing on the site and enter to select it) will be better than creating new site-specific shortcuts, but I'm not clear on what part of the site interaction you're referring to, so feel free to ignore this comment if it's irrelevant.

**Comment by ericronne** [comment]
Do we have any accessibility gurus? I'm not one, but i know that tabbing is [core](https://webaim.org/techniques/keyboard/) to the way keyboard-based users get around, so that's also a consideration.

**Comment by terichadbourne** [comment]
My accessibility training is minimal, but what I would have expected on a page like this with left-side nav is that when you tabbed from the top of the page you would first cycle through all of the nav options (where then clicking or hitting enter would change the content on the right) and then cycle through all of the clickable content on the right side of the page (main content). I don't think it's necessary to build a special command to tab from left to right. Just think of nav as top in the cycling, and make sure it's in nav tags so people with various accessibility tools can skip it or access it in the ways they're used to.

**Comment by jessicaschilling** [comment]
Closing in favor of accessibility master issue https://github.com/ipfs/ipfs-gui/issues/28 -- this discussion has been linked to from there so we avoid it getting lost to history.
