### ISSUE TITLE
Translation of webui json to spanish

### ISSUE THREAD

**Issue by davidalencia** [ipfs-shipyard/ipfs-webui#768]
Want to translate the webui-LANGUAGE.json
there is no translation file to spanish
I guess file should be something like this " ipfs-webui/dist/locale/webui-es.json"

**Comment by hacdias** [comment]
Hello @davidalencia!

A [new version of WebUI](https://github.com/ipfs-shipyard/ipfs-webui/tree/revamp) is coming soon so I think it would be better to put the new efforts on that branch. Although, we still don't have internationalization working, it is on the roadmap (#675 and #749).

/ping @ipfs-shipyard/gui

**Comment by lidel** [comment]
@davidalencia  we now have a fancy crowdsourcing website for translations:
- https://www.transifex.com/ipfs/public/ 

If you want to contribute to Spanish version of new WebUI, log-in/register with your github account  and join team at https://www.transifex.com/ipfs/ipfs-webui/language/es/ :rocket:  :)
