### ISSUE TITLE
Handle IPFS connection errors gracefully

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#773]
When connecting via the api, the daemon may get shut down, or it may be on another machine. We can't assume it will always be available. If we can't find an IPFS node to connect to on start up, we show a page that informs the user and allows them to change the api address, which is nice. We need to handle the situation where the IPFS node is temporarily unavailable, and show the user that the info in the webui is stale, while we try and reconnect.

Right now, if the api goes away, the UI shows the old data, which is better than failing, but we must indicate that it's getting progressively less accurate, and that they should re-start the node if possible. We need to show that the actions are disabled as well.

There are also errors of not being given permission when accessing ipfs via window.ipfs to handle. To do this well, we are going to need to track info about the ipfs connection provider so we can easily show relevant info based on how you connect (js-ipfs-api, or window.ipfs)

- [x] Inform the user that there is a problem with the connection to IPFS and that the data is stale.
- [ ] Show actions as disabled
- [ ] Tell the user how to fix it. (is it a window.ipfs permission error or an unresponsive remote daemon)?

**Comment by olizilla** [comment]
data points

- run `ipfs daemon`
- open status page
- kill `ipfs daemon`
- click files tab

<img width="1552" alt="screenshot 2018-09-17 15 40 14" src="https://user-images.githubusercontent.com/58871/45630419-8ee17f80-ba90-11e8-81e7-c0048b507a60.png">

**Comment by olizilla** [comment]
**Killing the ipfs daemon during use**

- **Status** - No indication that calls are failing. Last known stats are preserved. Stats resume once the daemon is restarted.
- **Files** - Shows an inline error message that it "failed to fetch" but it is not clear that this is because the api failed to respond. After ~1min it stacks up hundreds of identical error messages
- **Explore** - No indication that calls would fail. The homepage doesn't require ipfs, but any explore link will fail without it. Using and explore suggestion or pasting a CID leaves you with a spinner and no indication that the call may never succeed as ipfs has gone away
- **Peers** - No indication that calls are failing. Shows last known peers count. Picks back up when daemon is restarted.
- **config** - No indication that saving will fail. Attempting to save causes the button to get stuck in the "Saving..." state. The `CONFIG_SAVE_ERRORED` action is triggered, so that's surprising. Bringing the daemon back up doesn't fix it which isn't surprising as it's already error'd

We need a connection status indicator. We must show the user when the ipfs api we're using stops responding, and we should disable actions that cannot be performed while we wait for it to come back.

- [ ] Status should show clearly that the node is not responding, we should zero out the bandwidth stats rather than preserving their last value, as it implies activity which isn't the case. Node info _should_ be preserved, so that's ok.
- [ ] Files shouldn't show multiple identical error messages inline. This feels like a job for a toast style notification popup, and batching and de-duping. We should disable all links when we find that ipfs has stopped responding.
- [ ] Explore should disable the form and the suggestions when the api stops responding. Attempting to explore should show an error rather than spinning forever
- [ ] Peers should show that we don't know how many peers you have as we can't talk to the api. Saying 0 would be ok, but it'd be better to say we don't know.
- [ ] Config should disable the buttons, and show a warning message that changes can't be applied. If there are no user changes in the editor currently we should make it readonly. Double check that errors that occur _during_ saving are caught, and that the updated config is preserved in the UI, and the user is warned that the changes probably weren't saved.

**Comment by lidel** [comment]
> We need a connection status indicator.

Is this related to the planned drop-down "backend picker" somewhere at the top right?.
I don't think we have a good icon, but we could ask Agatha to draw something like:

<img src="https://user-images.githubusercontent.com/157609/45687235-79cb2600-bb4e-11e8-975c-bf83d3aada39.png" width="48"> vs&nbsp; &nbsp;   <img src="https://user-images.githubusercontent.com/157609/45687234-79cb2600-bb4e-11e8-898b-1f7075f688e7.png" width="48"> 

Having that persistent UI element, we could show something extra next to it, like :warning:  when connectivity issue is detected.

( mean, we would still will display warning dialogs/inline messages to user when things break, but there should be a persistent indicator on every screen showing "API health".  It would not only serve as go-to for users, but also saves time when people report bugs. )

**Comment by olizilla** [comment]
@lidel I like it. I'm inclined to only show something when there is a problem, as we can only really tell if there is a problem when we hit an error. There isn't really a good way to know that everything is ok until we ask a question.

Work in progress on nice (localised) error notifications

<img width="1364" alt="screenshot 2018-09-18 15 32 51" src="https://user-images.githubusercontent.com/58871/45695017-7472d900-bb58-11e8-8a5c-ca231d6fdbdc.png">

**Comment by lidel** [comment]
Closing, as I believe this is mostly resolved since 2018, and if future improvement need to be done its easier to start with a new issue.

(Right now, when node is offline instructions are shown and clicking on the orange indicator in top right corner the connection status screen is displayed, enabling more savvy user to manually switch the endpoint)
