### ISSUE TITLE
Opt-in error reporting and anonymous usage reporting

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#774]
Not a blocker for releasing v2, but we're rolling out a new codebase so that means exciting new bugs that we haven't found yet.

It'd be great to get user errors reported automatically, in a way that we can see what's happening with real usage, and have a service we can point users to if they want to find out more / solve the problem / contribute to a fix. The error reporting should be opt-in, respectful of user privacy and give us stack traces and runtime environment info.

More broadly, it'd be great to have some anonymous, opt-in usage stats so we can see what functions are popular and what isn't getting used, so we can focus the user testing to figure out if the feature is superfluous or if it's the UX that is getting in the way.

**Comment by lidel** [comment]
There is a problem with "opt-in usage stats so we can see what functions are popular" because if it is an opt-in you will have unrepresentative sample of people :) If we want to gather meaningful usage data, it needs to be enabled by default (opt-out).  The hard part is to ensure we don't sent any personal data. 

I feel "Telemetry" project in Firefox may be an example how to do it right:

> It's helpful for Mozilla's engineers and decision-makers to be able to measure how Firefox behaves in the real world. The Telemetry feature provides this capability by sending performance and usage info to Mozilla. As you use Firefox, Telemetry measures and collects **non-personal information**, such as performance, hardware, usage and customizations. It then sends this information to Mozilla on a daily basis and we use it to improve Firefox.

- https://telemetry.mozilla.org 
- https://wiki.mozilla.org/Telemetry
- https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox

**Comment by lidel** [comment]
cc https://github.com/ipfs-shipyard/ipfs-desktop/pull/697 (_Opt-in error reporting in ipfs-desktop_)

**Comment by olizilla** [comment]
See also https://github.com/ipfs/ipfs-gui/issues/72

**Comment by olizilla** [comment]
OK, I'm leaning towards
- analytics is anonymous telemetry - no file paths, no CIDs, just which app sections are you viewing, session length, browser version, OS, screen-size etc.
- if you never explicitly opt in or opt out, then it defaults to your global `navigator.doNotTrack` preference.
- on first run, if you have `doNotTrack ==== 1` then analytics is off, and we show an ask on the status page if you would consider enabling analytics for this app. 
  - If you answer yes, then your preference is stored and used in favour your doNotTrack
  - if no we store that, and we continue to not enable analytics even if you later change your doNotTrack setting in your browser.

**Comment by olizilla** [comment]
WIP in #930

**Comment by jessicaschilling** [comment]
Closed (stale). Please re-open if necessary - thanks!
