### ISSUE TITLE
Tweaks on Status page

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#778]
![image](https://user-images.githubusercontent.com/5447088/45084446-3f956980-b0f6-11e8-84bf-99cc71acaff9.png)

The current status page doesn't yet look like the one from Invision. What's missing:

- [x] Banwidth graph:
	- [x] Background
	- [x] Gradient fullfillment
	- [x] Simpler tooltip
	- [x] Simpler axis
- [ ] Peer Graph:
	- [ ] Display percentage on circle - have some feelings about this: what if the slice is small enough the number doesn't even fit?
	- [ ] FLags on tooltip

**Comment by olizilla** [comment]
Need to tweak the layout as the dials always wrap on 1440x900 screen at full width

<img width="1552" alt="screenshot 2018-09-12 11 50 37" src="https://user-images.githubusercontent.com/58871/45420481-29e9ec00-b682-11e8-919d-7ca664a273ba.png">

**Comment by olizilla** [comment]
Completed in multiple PRs
