### ISSUE TITLE
Permalinks with API Address

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#785]
Here's an idea:  support for permalinks  like this:

`http://localhost:3000/#/settings?ipfsApi=http://127.0.0.1:5001`

- `?ipfsApi=` is an optional parameter that overrides regular logic done by [ipfs-redux-bundle](https://github.com/ipfs-shipyard/ipfs-redux-bundle)
- gives us ability to bookmark WebUIs for specific views for specific nodes :)
- permalink could be under  :link: icon on the "backend picker"

**Comment by olizilla** [comment]
I can't tell if this is a harmless cool trick, or too much power to the link author

**Comment by olizilla** [comment]
I left the configurability in the hands of the user via localStorage in ipld-explorer as I didn't feel comfortable adding url based configuration, though it did cross my mind. I can't think of a good malicious use case, but letting the link author choose what IPFS I connect to seems radical.

**Comment by lidel** [comment]
While #837 provides a better solution for js-ipfs and go-ipfs, webui bundled with Companion won't be able to take advantage of it.  

I propose we add support for `?ipfsApi=`  but only when webui itself is loaded from:
-  `chrome-extension://`
- `moz-extension://`

This should be safe for two reasons: 
1. UUID used in `*-extension://` is unique for every user+vendor combo, so its not feasible to guess URL 
2. we would ignore value from `?ipfsApi=` when protocol in `window.location.protocol`  is starting with `http`, so http gateway and  webui.ipfs.io versions will be safe from manipulation

@olizilla  how do you feel about this approach?

**Comment by lidel** [comment]
Update:

-  #837 provides a better solution for js-ipfs and go-ipfs
- Companion will expose API object via webextension APIs, so there is no need for this hack

Due to the above, it is no longer needed, closing.
