### ISSUE TITLE
PeerIDs are force-uppercased

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#790]
http://localhost:3000/#/peers: 
> ![screenshot_30](https://user-images.githubusercontent.com/157609/45440985-22e0cf00-b6be-11e8-898e-c00085e47e63.png)

We probably don't want to change case of PeerID, those are in Base58 (case-sensitive) also multiaddr looks weird in uppercase, but that is not a bug, just ux. 

Update: this seems to be just css transform, if i select and copy one, case is correct (big and small letters). Still, bit confusing.

**Comment by olizilla** [comment]
Fixed in #793
