### ISSUE TITLE
Problem Connecting to Private IPFS Network - swarm.key 

### ISSUE THREAD

**Issue by bigjpr83** [ipfs-shipyard/ipfs-webui#800]
I have a private network running with go-ipfs using a private swarm.key. How do I utilize the same network/swarm.key using js-ipfs?

**Comment by olizilla** [comment]
Hi! This is where we track bugs and features for the IPFS webui. The discuss forum is the best place for getting help, as it's more visible to the rest of the community who may have the same question.

I see you've found it! https://discuss.ipfs.io/t/js-ipfs-swarm-key-for-private-network/3849
