### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by mxdpeep** [ipfs-shipyard/ipfs-webui#803]
please add 16/32px PNG favicon as described on
https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Favicon.html
![image](https://user-images.githubusercontent.com/75358/45865400-aca73100-bd7d-11e8-9bc9-b66fb25a0058.png)

**Comment by lidel** [comment]
Also, we need to remember it needs to be explicit definition using a relative path, otherwise it won't work when loaded from HTTP gateway. (I already fixed that bug for ipld.io: https://github.com/ipld/website/pull/47)

**Comment by hacdias** [comment]
It could be blue when connected and grey when disconnected 😄

**Comment by bleonard252** [comment]
I thought you could use a Data URL? Or maybe via Canvas, like those sites with dynamic icons?

**Comment by hacdias** [comment]
It seems to be working now. Closing this!
