### ISSUE TITLE
Error handling component

### ISSUE THREAD

**Issue by masylum** [ipfs-shipyard/ipfs-webui#81]
There is barely any error handling right now. I think the web ui could benefit from having a centralized error handling component.

**Comment by jbenet** [comment]
Very much agreed. @diasdavid thoughts?

**Comment by diasdavid** [comment]
Sounds good, but right now, I would even love more is some tests, it is scary to touch anything right now.

Doing tests right now might not be resource efficient as @krl is working on a new version only based in Web Components. @krl are you adding browser tests to that?

**Comment by jbenet** [comment]
also, we should merge that soon so development can happen on top

**Comment by masylum** [comment]
yep, I want to start helping but that PR being unfinished it does not feel productive

**Comment by hacdias** [comment]
The coming version (2.0.0) has one 😄
