### ISSUE TITLE
Show file operations and meta info on file preview page

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#813]
When I want to share a file, it feel natural to click on it. This opens up the file preview page, which shows the path and the file, but the actions aren't available.

**file actions**
<img width="1552" alt="screenshot 2018-09-25 15 29 51" src="https://user-images.githubusercontent.com/58871/46021177-efe40580-c0d7-11e8-82c7-66469be2ad09.png">

**file preview**
<img width="1552" alt="screenshot 2018-09-25 15 29 56" src="https://user-images.githubusercontent.com/58871/46021175-efe40580-c0d7-11e8-8bed-f04bb7498398.png">

It'd be great to still have access to:

- Share
- Download
- Delete
- inspect
- Rename

along with info like

- file CID
- file size
- assumed file type / file icon

**Comment by fsdiogo** [comment]
Dropbox does it like this:

<img width="1069" alt="dropbox" src="https://user-images.githubusercontent.com/33324750/51045820-7146a180-15bc-11e9-9199-8e12ff5b8898.png">


I sketched out two proposals:

| 1. I like the cleanliness of this one | 2. Shameless Dropbox copy |
| --- | --- |
| <img width="1257" alt="proposal-1" src="https://user-images.githubusercontent.com/33324750/51050383-7c073380-15c8-11e9-8233-98f544a229f5.png"> | <img width="1257" alt="proposal-2" src="https://user-images.githubusercontent.com/33324750/51050387-80335100-15c8-11e9-8771-78cf3fd823a3.png"> |

What do you guys think? @ipfs-shipyard/gui
