### ISSUE TITLE
How do users discover the Web UI?

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#815]
It's mentioned in the docs

- https://docs.ipfs.io/introduction/usage/#fancy-web-console

as:

> We also have a web console you can use to check the state of your node. On your favorite web browser, go to:
> http://localhost:5001/webui

but if you don't read the docs that far (or at all) then I think the Web UI is basically hidden from you.

What if we added a log line to go-ipfs and js-ipfs start up like:

```console
$ jsipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/192.168.1.244/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
API is listening on: /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9090
Web UI available at http://localhost:5002/webui
Daemon is ready
```

**Comment by meiqimichelle** [comment]
If this is straighforward to add, I don't see any reason not to! That info seems to fit with all the other info listed -- aka, here are all the things you now have available to you at these locations.

While we're there, we should standardize the language for all the sentences (colon versus no-colon). So, it could be:

```console
$ jsipfs daemon
Initializing daemon...
Swarm listening on: /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on: /ip4/127.0.0.1/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on: /ip4/192.168.1.244/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
API is listening on: /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9090
Web UI available at: http://localhost:5002/webui
Daemon is ready
```
or

```console
$ jsipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/192.168.1.244/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
API is listening on /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on /ip4/127.0.0.1/tcp/9090
Web UI available at http://localhost:5002/webui
Daemon is ready
```

**Comment by olizilla** [comment]
Engaging copy editor eyes 👀 ...see also the flip flop between _is listening_ vs _listening_ and the new word `readonly` which could be human'd to `read only`, and there is zero mention of IPFS... a little confirmation that you've started the thing you expected wouldn't hurt... so how about:

```console
$ jsipfs daemon
Initializing IPFS daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm listening on /ip4/192.168.1.244/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
API listening on /ip4/127.0.0.1/tcp/5002
Gateway (read only) listening on /ip4/127.0.0.1/tcp/9090
Web UI available at http://localhost:5002/webui
Daemon is ready
```

- no colons, simply siding with what most of the log lines do currently
- use "listening on" consistently
- "read only" not "readonly"
- Initializing **IPFS** daemon... to confirm to the user they started the thing they expected.

I'd keep the "Daemon is ready" copy the same though as it's the kind of output that people might be scraping from scripts to check that it started without error, and changing it would frustrate.

**Comment by olizilla** [comment]
...what I'd actually like to see in my console.

```console
$ jsipfs daemon
Starting IPFS daemon

Peer ID       QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm address /ip4/127.0.0.1/tcp/4003/ws/ipfs QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm address /ip4/127.0.0.1/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Swarm address /ip4/192.168.1.244/tcp/4002/ipfs/QmNTAZYQ5rtaoFtryAX2h9dycuBjhVgXtjPVZNYuMHMBw8
Gateway       /ip4/127.0.0.1/tcp/9090
API           /ip4/127.0.0.1/tcp/5002

Web UI available at http://localhost:5002/webui

Daemon is ready
```

**Comment by olizilla** [comment]
PR on js-ipfs here https://github.com/ipfs/js-ipfs/pull/1595
If that's acceptable I'll brush up my Go and PR there too.
