### ISSUE TITLE
Show an intro to Web UI and IPFS when file browser is empty

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#818]
I have no files in my MFS, I get presented with this page:

<img width="1440" alt="screen shot 2018-09-26 at 09 10 09" src="https://user-images.githubusercontent.com/152863/46066308-469b1f00-c16c-11e8-862e-d904ee9e302f.png">

Needs a call to action, or at the very least some text saying there's "no files here". At the moment it looks broken.

**Comment by hacdias** [comment]
Are you using it with Companion? If so, that's why. Companion scopes each app to its own directory. We don't have a way yet to tell Companion that we are WebUI and want access to everything

**Comment by olizilla** [comment]
We should use this as an opportunity to introduce IPFS and Web UI to new users who have just installed IPFS for the first time. 

When running in companion we can also add an explanation that the files view is limited to files added via the app. It's not ideal, but we should at least explain the current situation.

There is also a proposal to pull the Files page up to the top of the list and make it the default / home page for the app. It's likely to be a new users first expectation (i use IPFS for files, right?) and if the empty state does a good job of explaining what to do next, it'd make for a good new user experience.

See: #622

**Comment by fsdiogo** [comment]
We have a box with some info about IPFS

**Comment by olizilla** [comment]
Yep, that'd be a start! We should add some info about drag-and-drop support for adding files too.

**Comment by fsdiogo** [comment]
Fixed in https://github.com/ipfs-shipyard/ipfs-webui/pull/847.
