### ISSUE TITLE
Change enlarge on hover?

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#820]
<img width="438" alt="screen shot 2018-09-26 at 09 18 19" src="https://user-images.githubusercontent.com/152863/46066784-320b5680-c16d-11e8-8c15-8b13e35c8bd0.png">

IMHO the enlarge on hover effect looks really out of date and there's no other place in the UI where this happens (as far as I can see). Maybe a colour change instead?

I realise this is personal opinion so feel free to shut me down!

**Comment by olizilla** [comment]
I agree, the hover effect is not right here. I'd be happy with changing the color of the svg fill.
