### ISSUE TITLE
Files - add by path added a folder, but added it again to that folder

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#825]
<img width="930" alt="screen shot 2018-09-26 at 09 51 18" src="https://user-images.githubusercontent.com/152863/46068780-d98a8800-c171-11e8-868a-ea78094a1589.png">

**Comment by olizilla** [comment]
@alanshaw could you explain this one a little more please?

**Comment by alanshaw** [comment]
Ok I can't replicate this so maybe I did a bad
