### ISSUE TITLE
Files - Sorting by size not working

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#826]
<img width="1038" alt="screen shot 2018-09-26 at 09 58 17" src="https://user-images.githubusercontent.com/152863/46069192-e196f780-c172-11e8-8fe4-b05893e08aaa.png">

Not sure what's happening here, looks like the folders are grouped, but they don't appear to be in any particular order...

**Comment by olizilla** [comment]
@hacdias want to take a look at this one?
