### ISSUE TITLE
Show count and percentage in distribution pie chart tooltip

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#827]
<img width="381" alt="screen shot 2018-09-26 at 10 02 13" src="https://user-images.githubusercontent.com/152863/46069379-5833f500-c173-11e8-9d46-d2bcc4661f0b.png">

- [x] Show the count and the percentage value in the toolip like "United States 60% (450 peers)
- [x] Make title a link to the peers page

**Comment by olizilla** [comment]
This is causing confusion, see: https://github.com/ipfs-shipyard/ipfs-webui/issues/846
I am bumping up the priority.

**Comment by olizilla** [comment]
@fsdiogo this one is an easy win
