### ISSUE TITLE
Smart API detection when loaded from non-standard API port in go-ipfs

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#837]
This is something came to me when I was looking at https://github.com/ipfs/js-ipfs/pull/1595  and https://github.com/ipfs-shipyard/ipfs-webui/issues/785. 

If go-ipfs runs API on a different port than `:5001`, then webui will not be able to connect to it, even tho it was loaded from the API port :upside_down_face: 

Instead, it will display [error page  where user needs to manually provide the port](https://user-images.githubusercontent.com/157609/46203682-d088ea80-c31a-11e8-9683-c6c3342c4124.png).  

Its not bad, and may be enough for now, however I feel we could make it work automatically:
- **(A)** by appending parameter with custom API port to the webui URL printed to the console  (see https://github.com/ipfs/js-ipfs/pull/1595 and  discussion in https://github.com/ipfs-shipyard/ipfs-webui/issues/785)
- **(B)** by adding a simple fallback to webui: **if default port fails, check the same hostname but under the port  from `window.location.port`** (`""` means 80/443)

I think (B) makes more sense, it would fix the issue for both go-ipfs and js-ipfs without adding any cruft to URL. 

@olizilla  thoughts?

**Comment by olizilla** [comment]
@lidel oh my yes! B is a very good idea.

**Comment by olizilla** [comment]
First pass of this is in https://github.com/ipfs-shipyard/ipfs-redux-bundle/pull/15
