### ISSUE TITLE
Publish GIT Revision of running build

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#842]
Right now we are unable to tell what build is running, which will make bug reporting a real problem.

It would be extremely useful to:
- At least put it in meta header ([example](https://user-images.githubusercontent.com/157609/46286101-25786b00-c57e-11e8-8807-abecc8993861.png))
- Additionally,  put a faded-out version somewhere in Settings screen, or near 'See source'/'Report a bug', so it is visible on screenshots and/or non-technical user is able to check it and provide it with a bug report

This needs to happen before we ask general public for feedback. 

Eg.
- https://stackoverflow.com/questions/48391897/add-git-information-to-create-react-app
- https://github.com/facebook/create-react-app/issues/2486

**Comment by fsdiogo** [comment]
This is great @lidel 👌

Here's a thought, as we have the running daemon version, why not have the WebUI version there too:

<img width="1271" alt="version" src="https://user-images.githubusercontent.com/33324750/46292349-9d4b9300-c588-11e8-87c3-c62daa421455.png">

**Comment by lidel** [comment]
Hm.. I'd rather not put it there: webui version is not really a part of "node info".

What if we add it above links added in https://github.com/ipfs-shipyard/ipfs-webui/pull/809#issuecomment-425911220 ?
To save space, the git hash  (`git rev-parse --short HEAD`) could double as a link to sources at github eg: 
[See sources: `1e2c58fe`](https://github.com/ipfs-shipyard/ipfs-webui/tree/1e2c58fee899009cf68bc4c903d4eed9dbbe1f0b)

**Comment by fsdiogo** [comment]
> webui version is not really a part of "node info".

Yeah, you're right.

> What if we add it above links added in #809 (comment)?

That could work, although personally I wouldn't want that info showing all the time. I'd prefer as you said somewhere in Settings. Or in the status page maybe?

**Comment by olizilla** [comment]
Very cool! What if we go more subtle and replace "see the code" with the revision number?

**Comment by fsdiogo** [comment]
I have mixed feelings about that 🤔

For one I like it because it would have -1 link. On the other hand, it's not very clear for the average user that the revision number will link to the code, and I think we should always have a direct link to the latest code. 

Do you agree?

**Comment by fsdiogo** [comment]
Cool, I'll open a PR.

What will be the plan to update the git revision?
