### ISSUE TITLE
How to bundle webui with companion and desktop?

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#843]
We want to ship Web UI with both [Companion](https://github.com/ipfs/ipfs-companion) and [Desktop](https://github.com/ipfs-shipyard/ipfs-desktop). 
Goal: speed and ensuring it works in offline environments. 

Some options I see:

- (A) build it from source every time 
  -  Slows down the build of Companion/Desktop
  - Prone to errors (different builds of the same webui revision, harder to debug)
- (B) Use prebuilt artifact and download it during the build of Companion/Desktop.
   - (B1) from npm (requires publishing to npm)
   - (B2) from IPFS (may be easier, could be automated to the point of being transparent, eg. setup Jenkins so it builds every revision and adds it to IPFS)
- (C) Do not bundle any data, open it from IPFS address (like go-ipfs) 
   - The problem is offline mode. It could be solved if we get go-ipfs to ship with specific CIDs being preloaded, which could remove the need of bundling it with Companion and Desktop at a cost of increasing size of go-ipfs. 

#### Related Work
- https://github.com/ipfs-shipyard/ipfs-companion/pull/590

**Comment by hacdias** [comment]
@lidel I'd go preferably for B. Either B1 or B2 would work well, although B1 would be simpler to bundle. For B2, we'd need a way to know the latest revision and download it on build time.

**Comment by hacdias** [comment]
And I wonder how much stable is the public API right now. I just tried to download it multiple times and it always failed: the speed started decreasing to 0 after downloading 1/2 MB.

**Comment by lidel** [comment]
I went with **B2** for now and created some orchestration for fetching prebuilt webui from IPFS + fallback to HTTP: 

- https://github.com/ipfs-shipyard/ipfs-companion/pull/590#issuecomment-426827936

**Comment by hacdias** [comment]
I think this is an ended discussion for now :)
