### ISSUE TITLE
How can I have 39 total peers and also 49 in the USA alone?

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-webui#846]
So this is confusing. The screenshot shows a total of 39 peers, but the peer distribution says I’m connected to 49 peers in the USA. These can’t both be right, so what is going on here?

Is some data cached while the other isn’t? Should probably use and cache the same data source so the UIs match up.

![screenshot_2018-10-03t17 45 29_ipfs_webui](https://user-images.githubusercontent.com/1102886/46423467-de81a580-c736-11e8-8ac6-4783a6eb6ac2.png)

**Comment by lidel** [comment]
(drive-by comment)
My guess is peer info is cached to save resources.
It probably should detect that current live count is smaller than one in cache and force cache to drop/ignore old entries.

**Comment by olizilla** [comment]
The pie chart is showing you the % of total that are in the US. We need to make that clearer. If you have any time to help out there is an issue to fix that here https://github.com/ipfs-shipyard/ipfs-webui/issues/827

Thanks for reporting it. I'm gonna close this out and refer to it as supporting evidence from that issue.
