### ISSUE TITLE
Make CORS config info copy-pasta friendly

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#849]
The CORS config commands are truncating to fit the space available, but they should be `overflow:scroll` so the user can copy/paste the whole line when needed.

<img width="640" alt="screenshot 2018-10-04 15 53 50" src="https://user-images.githubusercontent.com/58871/46482577-c4ef6500-c7ed-11e8-996d-a0f4ff9585d1.png">

**Comment by fsdiogo** [comment]
This has been fixed in https://github.com/ipfs-shipyard/ipfs-webui/pull/847.
