### ISSUE TITLE
IPFS configuration instructions are truncated

### ISSUE THREAD

**Issue by richsilv** [ipfs-shipyard/ipfs-webui#863]
Having not correctly configured my daemon to work with the new web UI, I've been provided with a very helpful message telling me I need to reconfigure it. However, some of the text is truncated via CSS:

![screenshot from 2018-10-19 09-28-06](https://user-images.githubusercontent.com/3180526/47206821-832ff400-d381-11e8-84ce-165f4fdfe286.png)

You can copy-paste the whole lot and get the full command, but it seems like this is something you should be able to see. Happy to PR something to fix this, but I suspect @olizilla will have opinions on the best way!

**Comment by olizilla** [comment]
It fixed! https://github.com/ipfs-shipyard/ipfs-webui/issues/849
