### ISSUE TITLE
Volunteers wanted for usability testing Web UI v2

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#867]
We'd like to gather some structured feedback on the usablility of the Web UI v2 release to help us focus our next round of improvements.

If you're up for participating in on < 1hr video call with @olizilla, please give a thumbs up on this issue and I'll ping you and schedule a call at a time that works for you. 

On the call we'll run through a handful of tasks and see what works well, and what is confusing. There are no wrong answers! I'll take notes and anything that seems needless awkward will get written up as issues for us to fix!

**Comment by pkafei** [comment]
Count me in

**Comment by patrykadas** [comment]
If it's still on, I'd be happy to help
