### ISSUE TITLE
Responsive Layout for Mobile Devices

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#871]
I've been playing with:
- [Sweet IPFS](https://discuss.ipfs.io/t/sweet-ipfs-full-ipfs-node-for-android/3779?u=lidel) (go-ipfs for Android packaged by a community member)
- [Firefox for Android Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) (runs the same webextensions as desktop version)
- ipfs-companion beta [v2.5.1.11870](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.5.1.11870) (bundles new ipfs-webui)

I opened bundled Web UI and it works as expected :1st_place_medal:   \o/ but is missing some low hanging fruits such as collapsing  left menu on narrow viewport:

| Status | Files | Settings |
| ---- | ---- | ---- | 
| ![screenshot_20181026-163859](https://user-images.githubusercontent.com/157609/47574159-434bac80-d93f-11e8-90fc-bec917c1a8be.png) |  ![screenshot_20181026-165424](https://user-images.githubusercontent.com/157609/47574541-18ae2380-d940-11e8-8da3-645d940d964b.png) | ![screenshot_20181026-165435](https://user-images.githubusercontent.com/157609/47574558-219ef500-d940-11e8-99ff-5bb7f9ec1b53.png) |

**Comment by olizilla** [comment]
Rad! That'd be a pretty simple fix.

**Comment by olizilla** [comment]
_Scientists was so preoccupied with if they could, they didn't stop to think if they should_

![webui-responsive-navbar](https://user-images.githubusercontent.com/58871/47913392-d0d55200-de93-11e8-8784-f68a54cba67c.gif)

**Comment by olizilla** [comment]
it was not simple.

**Comment by fsdiogo** [comment]
Fixed in #877.

**Comment by olizilla** [comment]
I'm happy to close this for now, but there is a ton of polishing to do to actually have a good reponsive layout, but that is a low pritority for now.

**Comment by fsdiogo** [comment]
Yes, I jumped the gun closing this one because I thought it was only referring to the navbar responsiveness. 

We can reopen it later when someone starts working on it!
