### ISSUE TITLE
The colours of the bandwidth graph and gauges for in/out are switched

### ISSUE THREAD

**Issue by lanzafame** [ipfs-shipyard/ipfs-webui#876]
![1541153981](https://user-images.githubusercontent.com/5924712/47909791-ad82c500-dedc-11e8-8aa9-2b881e9efe05.png)
![1541153988](https://user-images.githubusercontent.com/5924712/47909792-ae1b5b80-dedc-11e8-92d0-e596fa373d7b.png)
The orange is incoming on the gauge but out on the timeline graph. The look great otherwise :smile:

**Comment by olizilla** [comment]
derp derp derp. Thank you for vigilance @lanzafame

**Comment by lanzafame** [comment]
caveat, i am not sure whether the entire graph is entirely wrong or if just the legend is, so I will leave that to you to figure out :slightly_smiling_face:
