### ISSUE TITLE
Suggestion: Settings/Config UI

### ISSUE THREAD

**Issue by bleonard252** [ipfs-shipyard/ipfs-webui#879]
This may already be on the roadmap, but where could I start in mapping configuration settings in the config.json to a UI?

**Comment by olizilla** [comment]
OOH! This would be great! To check we're on the same page, are you saying you'd like to update the settings page with a more form-like / user-friendly controls for updating the more commonly updated propertied of the ipfs config file? 

The design discussion for the settings page is here https://github.com/ipfs/ipfs-gui/issues/15 and we have some initial design proposals, that'll add there shortly.

**Comment by bleonard252** [comment]
That's exactly what I'm looking for!

**Comment by jessicaschilling** [comment]
Closing this issue in favor of https://github.com/ipfs/ipfs-gui/issues/15 - thanks!
