### ISSUE TITLE
Wavy flag icons are harder to decipher on high-resolution

### ISSUE THREAD

**Issue by lanzafame** [ipfs-shipyard/ipfs-webui#880]
It seems the flag icon library has changed the flags from square rectangles to wavy flag rectangles which on high-res screens are hard to read, see screenshots below:
high-res:
![1541391115](https://user-images.githubusercontent.com/5924712/47977627-df767000-e104-11e8-9651-35fe80b9b830.png)
zoomed-in:
![1541391133](https://user-images.githubusercontent.com/5924712/47977635-e8674180-e104-11e8-95d5-17772d3de66b.png)

**Comment by olizilla** [comment]
@lanzafame you have more resolution than any one person needs. Please share your estate with others. :-p

The significant change is we're using emoji flags where possible to avoid having to download a bunch of flag icons where possible. But if this is harming legibility, then that is a concern. 

It looks like the bigger issue here is the layout is kinda terrible at high resolutions and we could fix that, and potentially use a large font size so the flags are larger and easier to interpret.

Could you add your screen res to the issue, I'll take a look.

**Comment by lanzafame** [comment]
I am happy to share, just come visit @olizilla ;) 

My screen res is 3840x2160.
