### ISSUE TITLE
Upgrade to create-react-app v2

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#888]
CRA v2 is out https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

It has CSS Modules, postcss, import svgs as component, and new babel, webpack and jest, which'll simplify a few things for us.

**Comment by fsdiogo** [comment]
Just finishing this so I can then solve https://github.com/ipfs-shipyard/ipfs-webui/issues/986.
