### ISSUE TITLE
Peers: UI  for swarm connect 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#891]
Here's an idea:  "Add Connection" button

- could be a button similar to "Add to IPFS" from  Files screen
  - benefit from reusing established visual pattern
- opens form that accepts multiaddr, when confirmed executes `ipfs swarm connect`
- open questions:
  - how to indicate success/failure?
    - somehow store and "pin" peerid of manually added connection(s) to the top of Peer list?
    - display error message instead of peerid line if failed?
  - support "pet names" ? could be first step towards [ipfs-friends](https://github.com/tableflip/ipfs-friends)-like feature

**Comment by olizilla** [comment]
Thanks! I thought we had this written up somewhere, but apprently not. Yes, let's build it, I love it.
