### ISSUE TITLE
Shrink the peers map to fit the screen

### ISSUE THREAD

**Issue by anacrolix** [ipfs-shipyard/ipfs-webui#903]
The map in the peers tab doesn't shrink to fit the screen, so on small screens one only sees Europe and West Africa. Even on a typically large screen, Alaska, and East Asia may be missing.

**Comment by olizilla** [comment]
Thanks, this is on my radar. The first implemenation of this was reponsive, but it relied on d3 redrawing the world map from json data bout land boundaries on every update, which was, unsuprisingly, taxing on system resources. 

In optimising it I ended up capturing the rendered world map to a static svg, and then overlaying the points via d3. That was much lighter, but in doing so I've decoupled the positioning of the dots with whe underlying map. The svg will scale nicely, but both the d3 layer and the svg need to scale proportionally to ensure the points remain in the right locations. It'll either be trivial to fix or really fiddly.
