### ISSUE TITLE
Sort peers by address IP octets

### ISSUE THREAD

**Issue by anacrolix** [ipfs-shipyard/ipfs-webui#904]
Peers are sorted alphanumerically in the peers tab. It might be better to use a sort that attempts to sort by numerical groupings (since we don't want to infer any kind of address family). For example the following addresses would be preferred in the reverse order:
```
/ip4/128.199.166.56/tcp/4001
/ip4/13.69.55.93/tcp/4001
```
I don't know if there's sorting provided for multiaddr, but that might be a nice addition to standardize across implementations.

**Comment by olizilla** [comment]
This sounds like a neat feature. Would you be interested helping make it happen? The peers list can be long, so right now we just show it in the order that it comes back from the API. We could add sorting logic to the [peers bundle](https://github.com/ipfs-shipyard/ipfs-webui/blob/master/src/bundles/peers.js). 

If we wanted to let the user customise the sort then we'd need to add [redux-bundler style action creators](https://reduxbundler.com/api/bundle.html#bundledox) and enable sort controls in the react-virtualized table header which is used [over here](https://github.com/ipfs-shipyard/ipfs-webui/blob/c6d563d16c71d8fc3baab212f5a409c1fc82d71c/src/peers/PeersTable/PeersTable.js#L51-L64). 

I think react-virtualized Table gives you UI controls for sorting, but the actual data sorting is left up to the app, the [docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md) link out to this [example](https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Table.example.js)

I'm not sure what you mean when you say
>  we don't want to infer any kind of address family

**Comment by terorie** [comment]
Fixed in #909 :)

**Comment by anacrolix** [comment]
Is that a timeout in the CI?

**Comment by anacrolix** [comment]
I'm not much of a JS guy. I mean by inferring address family, it would seem against the intentions of multiaddr to read into the content of addresses and have special cases. Simple numerical sorting as appears to be implemented would be ideal.
