### ISSUE TITLE
Files: make it easier to create a new folder

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#915]
A lot of "file management" starts with creating a new folder and moving things to it.
Right now "New folder" action is hidden under "Add to IPFS" button and hard to discover and requires 2 clicks instead of one. 

What if we make it a top-level button (in faded out, much less  prominent colors than "Add to IPFS")?

> ![2018-12-20--11-21-43](https://user-images.githubusercontent.com/157609/50279389-d7bb2280-0449-11e9-92e9-368768ead8f5.png)

Thoughts?

**Comment by olizilla** [comment]
Yep, it's confusing to have "new folder" in the same list. I'd like to do some design exploration on what we can do to make the "add to IPFS" process much better. "Add by path" is confusing for new users and it sound like "file system path", so I think we need to re-think this menu entirely.

**Comment by lidel** [comment]
Indeed, "Add by path" suggests something is not on IPFS and needs to be added, while all it does it import of existing IPFS data to MFS.

I guess it could also be moved to top-level, and/or renamed to something like "Import IPFS path".

**Comment by fsdiogo** [comment]
**Dropbox** doesn't use dropdowns, all options are visible:

<img width="625" alt="dropbox" src="https://user-images.githubusercontent.com/33324750/50845297-6abded00-1364-11e9-9bc2-41ab23853de9.png">

I agree we should think about how to improve this menu and the overall experience of dragging and dropping files on the Web UI.
