### ISSUE TITLE
Files: drag&drop target is to small

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#916]
### Problem

Right now, only the file list seems to be the drop target, which makes it not only a chore to aim, but impossible to drag-and-drop into an empty directory, as the file dropped on `..` (the only item in empty directory) gets added to parent directory:

![peek 2018-12-20 11-42](https://user-images.githubusercontent.com/157609/50280400-abed6c00-044c-11e9-9d3b-8a9485235307.gif)

### Solution Ideas

- the whole viewport should be the drop target 
  - Ideally, even if user is not on Files screen
- unless user drops on a specific directory on Files screen, then file is added to currently opened directory or `/` 
- there should be a visual cue "Drop here to add to <MFS path>" to ensure user it is safe to drop at the current target

**Comment by olizilla** [comment]
Strongly agree. I'm not clear on why we didn't make the whole viewport the drop target in the first place. @hacdias I know you had a reason, can you explain? We really need a solution to this. I'd say being able to drop anywhere is more important  than being able to drop on a dir in the filelist if we have to choose, though I think we can have both.
