### ISSUE TITLE
Add by path gladly accepts CID but fails

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/ipfs-webui#921]
At the moment pasting just CID without /ipns/ or /ipfs/ prefix appears as valid input but then fails with **Failed to add files to IPFS. Please try again** message.

It should for the very least provide more helpful error message & better yet have an input field that identifies CID without prefix as invalid and provides some helpful message allowing you to fix the input.

Ideally though it should just figure out what the prefix for CID should be and just do the right thing.

**Comment by fsdiogo** [comment]
The feature of accepting the CID without a prefix was added in https://github.com/ipfs-shipyard/ipfs-webui/pull/838.

Something must've broken it, I'll take a look. Thanks for reporting!
