### ISSUE TITLE
Getting Blocked loading mixed active content on https://webui.ipfs.io

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/ipfs-webui#925]
There must be some invalid assumption about the host in some URL resolution because the following error appears when using webui from https://webui.ipfs.io which does not appear when loading from `http://127.0.0.1:5001/webui/` give the URL blocked I think there is assumption that protocol schema is  `http:` which or maybe expectation that there address contains a port.

<img width="1105" alt="screen shot 2019-01-04 at 4 39 24 pm" src="https://user-images.githubusercontent.com/21236/50717871-88771380-103f-11e9-8808-a2185ae27c5d.png">

**Comment by olizilla** [comment]
Thanks for reporting that. It's a bug in ipfs-redux-bundle where it checks for an IPFS api at the same origin that the site was loaded from, and in uri-to-multiaddr, where it converts the current origin into a mutliaddr. I'll take a look.

**Comment by olizilla** [comment]
Fix for this is in progress.. it's the confluence of a bunch of smaller issues.
- https://github.com/ipfs-shipyard/ipfs-redux-bundle/pull/24
- https://github.com/ipfs/js-ipfs-http-client/pull/934
- https://github.com/ipfs/js-ipfs-http-client/pull/935
- https://github.com/tableflip/uri-to-multiaddr/pull/3
- https://github.com/tableflip/uri-to-multiaddr/pull/2
