### ISSUE TITLE
Failed to add files to IPFS

### ISSUE THREAD

**Issue by maooricio** [ipfs-shipyard/ipfs-webui#928]
I updated the ipfs-webui and follow the instructions in order to install and run the tool.

I had the old version of this module and I could worked with it fine. I decided to update it because I noticed that many things changed both here and in js-ipfs. All works fine but when I try to upload a file, The module shows me an error that I don't understand why because I studied and analyzed all the connections and I think all are set just fine. In fact, the console doesn't throw me any error when I make the upload. What I am missing?

Here is the error:

![screenshot from 2019-01-07 11-20-15](https://user-images.githubusercontent.com/6587647/50779453-61525900-126e-11e9-81b3-450760bdade0.png)

And here is the console log

![screenshot from 2019-01-07 11-20-44](https://user-images.githubusercontent.com/6587647/50779470-6f07de80-126e-11e9-8cb5-65bb2d544586.png)

**Comment by olizilla** [comment]
Yep, that should work. Can you give some more info?

- what commit version is listed in the bottom of the nav bar?
- what browser and version and OS are you using?
- did you drag and drop or did you click the button and choose add files or add folder?
- How many files / folders are you trying to add, and what is the total file size?

**Comment by olizilla** [comment]
i'm seeing an error on master with drag and drop of directories on Firefox, which I'm looking into now

**Comment by maooricio** [comment]
Hi @olizilla, look the answer to your questions:

1. commit/261f4f4
2. Google Chrome Version 68.0.3440.75 (Official Build) (64-bit). OS: Ubuntu 18.04.1 LTS
3. I clicked the button and I chose add files
4. One file with 200kb of total size

**Comment by maooricio** [comment]
I see that the POST error that we can see in the console log image doesn't have a logical URL (http://dnsaddr/localhost/tcp/3000/http:5001/api/v0/get?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn&stream-channels=true). This doesn't have something related with the issue?, maybe

**Comment by lidel** [comment]
Ok, I got the same result with ["Add file"](https://user-images.githubusercontent.com/157609/50865730-41728080-13a7-11e9-94cf-af629b220388.png) under both prebuilt `QmenEBWcAk3tN94fSKpKFtUMwty1qNwSYw3DMDFV6cPBXA` or dev version (`npm start`) tagged as `v2.3.2`:


![2019-01-09--00-34-48](https://user-images.githubusercontent.com/157609/50865677-02dcc600-13a7-11e9-917c-c98ef9e75ba7.png)

As you can see the file is added just fine – the error is bogus and looks.. oddly familiar :)
I suspected we are mixing logic responsible for "Add file" with "Add folder". And indeed: we are off by one in a place where there is a check for existence of a wrapping directory (expected when uploading standalone files). The `+ 1` was changed to `+ 2` in recent PR https://github.com/ipfs-shipyard/ipfs-webui/pull/924.

@olizilla @fsdiogo check this:

Changing: 

https://github.com/ipfs-shipyard/ipfs-webui/blob/22388be396cd84135b923d7c4aaaa4ba70d6cfa7/src/bundles/files.js#L244

back to:

https://github.com/ipfs-shipyard/ipfs-webui/blob/c491557d823f882a2ff10cacebb8976a51103449/src/bundles/files.js#L244

...fixes "Add file" but breaks "Add folder" :upside_down_face: 

So the actual fix requires some refactoring and decoupling "Add file" and "Add folder".

Hope this helps.

**Comment by fsdiogo** [comment]
Sorry, I was so focused on fixing the `Add folder` that I didn't check if `Add file` was breaking after it 🤦‍♂️

I'll fix it ASAP.
