### ISSUE TITLE
Merge file module with dir-index-html

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-webui#94]
It would be nice to consolidate this with https://github.com/ipfs/dir-index-html and have a single source of truth for these. @jbenet what would need to happen from a technical standpoint to make that happen?

**Comment by jbenet** [comment]
what do you mean by the file module?

also note that https://github.com/ipfs/dir-index-html should not contain any js-- it has to be able to return stuff for basic http clients (cli tools)
