### ISSUE TITLE
can't read file from ipfs gateway 

### ISSUE THREAD

**Issue by vioulo** [ipfs-shipyard/ipfs-webui#941]
One of my file hash is QmUVX5y1s11MRQFrYP1SJaMm1gGWUBmNjsA1JkHd3VkHvM
The other day, I can browse it on ipfs.io, but can't now, who know why ??

**Comment by alx696** [comment]
File maybe removed after GC. If not pin hash, file maybe lost. Without pin, any node just cache the file.

**Comment by vioulo** [comment]
@alx696 Could you leave a contact for us to discuss IPFS ? :cactus:
