### ISSUE TITLE
Multiple context menus and hidden menu close to bottom of page

### ISSUE THREAD

**Issue by unode** [ipfs-shipyard/ipfs-webui#944]
On Firefox v64.0 with latest IPFS companion and go-ipfs 0.4.17.

Steps to reproduce:
1. Right-click on one item
2. Right-click on the next item, slightly to the right to avoid clicking on the context menu
3. Repeat for subsequent menus
4. Open the context menu for the last element in the list

The two issues are visible in the following animation.

![screencast](https://user-images.githubusercontent.com/122319/51420882-118d5f00-1b97-11e9-85d3-5d977ee617e3.gif)

**Comment by olizilla** [comment]
I believe this is fixed. Please do re-open if you're still seeing this on the latest release.
