### ISSUE TITLE
UI: bandwith stats have the colors the wrong way around

### ISSUE THREAD

**Issue by nonchip** [ipfs-shipyard/ipfs-webui#953]
I'm on `Revision 1ed2020`, and I just noticed on the Status tab of the webUI the colors for inbound/outbound traffic differ:

* "Network Traffic" shows inbound in orange, outbound in blue
* "Bandwidth over time" shows inbound in blue, outbound in orange

those should probably be swapped so they match up for easier recognition at a glance.

**Comment by fsdiogo** [comment]
Hi @nonchip, this has been fixed in [v2.2.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.2.0)!

**Comment by nonchip** [comment]
@fsdiogo i just realized my distro didn't update the package since 0.4.18, thanks for pointing out :P

**Comment by nonchip** [comment]
guess i'll just wait then (and hope it's gonna become a name instead of a hash, it already seems to be on `TXT _dnslink.webui.ipfs.io.` anyway, so it'll be a bit more future proof).

by the way, note just going to webui.ipfs.io doesn't work ootb if you use the companion plugin, because then it rewrites your url to use the gateway instead of api port.
