### ISSUE TITLE
spurious files listings

### ISSUE THREAD

**Issue by jbshirk** [ipfs-shipyard/ipfs-webui#96]
```
$ ipfs add US-Government-Still-Silent-on-American-Journalist-Murdered-for-Exposing-Turkey’s-ISIS-Ties.pdf
added QmY6sC3NmsCbZiPihyfhDiR2gijdzqN7BaYK2g7PewbYpH US-Government-Still-Silent-on-American-Journalist-Murdered-for-Exposing-Turkey’s-ISIS-Ties.pdf
$ ipfs ls QmY6sC3NmsCbZiPihyfhDiR2gijdzqN7BaYK2g7PewbYpH
QmeUkVZKQwrUdG1BndVNkq6n88yzGnGH5JBrdiVsG7Uc5i 262158 
QmVHBYN1HMasLHBMHWs1hVJFWJ3K7jNkr6f1EWSZJV27ZB 262158 
QmXCb1TaYAx8hW3KJLA3ZMneSg56iTRGewghsMHq53YqEc 262158 
QmZ6D1pzR7MJgXmjAfTJQxVAhYQqn6UYLFFtoUfyYYGDe8 262158 
QmT7FYPgR5wGesFBBDdN3sqXop9HgYaP5pn3zzKtJiQptS 262158 
QmczHBY4xExAQ1AEyoax38fC3Jh9yXTqGkgnqCfGotkrtV 262158 
QmQD1uXBz63RN8RENYBMgfZ1W7cJvZ5wx4TSFLjqFTBKZA 262158 
QmfFFPwwhTWZ6rj1wgsKo17zZ1uVi2mpNCrAz7CQ7FUgd8 143546 
$ 
```

Notice that I did not pin this object.

Yet, it appears in the pinned files list:
http://localhost:5001/ipfs/QmS2HL9v5YeKgQkkWMvs1EMnFtUowTEdFfSSeMT4pos1e6/#/files/pinned

PINNED FILES
Type ID Actions

QmNxYrzU7nLMERzNn8SHnJYxiQQCr5xYFGBPMoDbXX3FCV
QmPQUsvqQH5kEntM99FspUWxMUd8iJy5FCFkd2dAa3eSFv
QmQmJ55Vm9Ct6Vvhpnv2r8JBpcxNeivvcGXvVvRogb8zu2
QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ
QmUFtMrBHqdjTtbebsL6YGebvjShh3Jud1insUv12fEVdA
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
QmVVNSyQkAeW4fA5oB1YY5rSxbz5pmGt3U4Vm1cqeaMrbz
QmX97wck9U7yUJHDjMVDHy2ZNmcHjgAseFaMoWMJtehxXT
QmXu6ouEAraepkgMshQ8C9Wpu6AVdQuSwZ1a7jJsoXQZMK
QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7
**QmY6sC3NmsCbZiPihyfhDiR2gijdzqN7BaYK2g7PewbYpH**
QmY9eMeuK2JYpPwUiFCd5j8UvM5CDroMeu4L8o96nxrrgs
QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y
QmZNe3xvQaxdtVp43NTJ9oURYPBKyVFJ8VDWHPipcGUwNF
QmZdL7uPYYEV3J1uzg3GARv1oAEmPB3ic3SrekgaaP1SZF
Qmbm4DRJd5eCMNeeHrtrJ4vYJGYAkbu2ZXtisb6C5ciWY1
Qmcqtw8FfrVSBaRmbWwHxt3AuySBhJLcvmFYi3Lbc4xnwj
QmdRkpcRWDQp3GDw2sLjdNjsmCAtaNivRex3r2ZkkgBNMC
QmeCd1SFRCxTqxfFDpV7sdj2Yci9ZzAUGCky7SmJkaQGf1
QmeEqpsKrvdhuuuVsguHaVdJcPnnUHHZ5qEWjCHavYbNqU
QmeFod9Whb3sMcXS3FyJrFdLPFad7PfiR8yFWADLTQFPB3
QmegAwrtM29oZqG52KM57SdxmiHveorJEguh1EdD42uYuh
QmfE3nUohq2nEYwieF7YFnJF1VfiL4i3wDxkMq8aGUg8Mt
QmfF48NZGzVq53XqutPmNRrgJQS3uypC73Ypc25qqsgKr5

It also appears in:
ALL LOCAL FILES
Type ID Actions
QmNxYrzU7nLMERzNn8SHnJYxiQQCr5xYFGBPMoDbXX3FCV
QmPQUsvqQH5kEntM99FspUWxMUd8iJy5FCFkd2dAa3eSFv
QmQmJ55Vm9Ct6Vvhpnv2r8JBpcxNeivvcGXvVvRogb8zu2
QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ
QmUFtMrBHqdjTtbebsL6YGebvjShh3Jud1insUv12fEVdA
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
QmVVNSyQkAeW4fA5oB1YY5rSxbz5pmGt3U4Vm1cqeaMrbz
QmX97wck9U7yUJHDjMVDHy2ZNmcHjgAseFaMoWMJtehxXT
QmXu6ouEAraepkgMshQ8C9Wpu6AVdQuSwZ1a7jJsoXQZMK
QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7
**QmY6sC3NmsCbZiPihyfhDiR2gijdzqN7BaYK2g7PewbYpH**
QmY9eMeuK2JYpPwUiFCd5j8UvM5CDroMeu4L8o96nxrrgs
QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y
QmZNe3xvQaxdtVp43NTJ9oURYPBKyVFJ8VDWHPipcGUwNF
QmZdL7uPYYEV3J1uzg3GARv1oAEmPB3ic3SrekgaaP1SZF
Qmbm4DRJd5eCMNeeHrtrJ4vYJGYAkbu2ZXtisb6C5ciWY1
Qmcqtw8FfrVSBaRmbWwHxt3AuySBhJLcvmFYi3Lbc4xnwj
QmdRkpcRWDQp3GDw2sLjdNjsmCAtaNivRex3r2ZkkgBNMC
QmeCd1SFRCxTqxfFDpV7sdj2Yci9ZzAUGCky7SmJkaQGf1
QmeEqpsKrvdhuuuVsguHaVdJcPnnUHHZ5qEWjCHavYbNqU
QmeFod9Whb3sMcXS3FyJrFdLPFad7PfiR8yFWADLTQFPB3
QmegAwrtM29oZqG52KM57SdxmiHveorJEguh1EdD42uYuh
QmfE3nUohq2nEYwieF7YFnJF1VfiL4i3wDxkMq8aGUg8Mt
QmfF48NZGzVq53XqutPmNRrgJQS3uypC73Ypc25qqsgKr5

But it’s NOT in [Files Tab]
Type Name ID Actions
HTM 
You Are Here.htm
QmNxYrzU7nLMERzNn8SHnJYxiQQCr5xYFGBPMoDbXX3FCV
PNG
11080908_822881507801355_5238711632930395669_n.png
QmZNe3xvQaxdtVp43NTJ9oURYPBKyVFJ8VDWHPipcGUwNF
JPG
Terrorism 1966 Definition.jpg
QmXu6ouEAraepkgMshQ8C9Wpu6AVdQuSwZ1a7jJsoXQZMK
JPG
Errico-Malatesta.jpg
QmQmJ55Vm9Ct6Vvhpnv2r8JBpcxNeivvcGXvVvRogb8zu2
JPG
Lucy-Parsons-development-individuals.jpg
QmegAwrtM29oZqG52KM57SdxmiHveorJEguh1EdD42uYuh
JPG
11102920_786874584744137_4665089822529436252_o.jpg
QmY9eMeuK2JYpPwUiFCd5j8UvM5CDroMeu4L8o96nxrrgs
JPG
de19747bcbd79ad457971fa173f4952e_970x.jpg
QmdRkpcRWDQp3GDw2sLjdNjsmCAtaNivRex3r2ZkkgBNMC
PNG
boy 234x234.png
QmPQUsvqQH5kEntM99FspUWxMUd8iJy5FCFkd2dAa3eSFv
PNG
virtual reality 1213x449.png
QmX97wck9U7yUJHDjMVDHy2ZNmcHjgAseFaMoWMJtehxXT
JPG
boy electric socket.jpg
QmQQWN2nV3KgaWtGWMYGPvh1sLDk1Xg8MtCDQN2CCPoiyv

In fact all files in the Files list are only those I added before mid-October; none added since then appear. This begs the question: what is the intended purpose of the files list - only "unpinned" files?

**Comment by jbenet** [comment]
- Adding defaults to --pin=true

- Files tab in webui listing I think is broken.



—

**Comment by Dignifiedquire** [comment]
Thanks for the detailed report, this corresponds with some of my experiences. I think we need to investigate and make sure this works as it's supposed to work.

**Comment by jbshirk** [comment]
A feature that I think would be useful: 
These appear to be listed alphanumerically, which is hardly useful given the randomish hashes; It would be useful to list them sorted by date added and by real filename.

**Comment by hacdias** [comment]
As version 2.0.0 approaches its release, this issue doesn't seem relevant because pinning is not a feature anymore. You can now use MFS to persist your files.

**Comment by jbshirk** [comment]
Sorry, what does MFS stand for? Can you post a link?

**Comment by hacdias** [comment]
@jbshirk MFS is the Mutable File System. You can use through most of `ipfs files [cmd]` commands. If you [look at the spec](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md), there is a section of commands just for MFS. Everything you write to MFS is automatically "pinned", i.e., it isn't garbage collected.

**Comment by jbshirk** [comment]
Thank you!
