### ISSUE TITLE
Failed to get url from Addresses.API TypeError: "t is null"

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#966]
**Describe the bug**
This is showing up in the logs:

```console
Failed to get url from Addresses.API TypeError: "t is null"
```

It's not fatal, but it shouldnt be there.

**To Reproduce**

1. https://ipfs.io/ipfs/QmZTMSPS7Wk1N6yUFgMRdeXxhQc2uAeLPpQZbn7n2B7VBk/#/welcome
2. Check the dev console

<img width="755" alt="screenshot 2019-02-21 at 17 50 55" src="https://user-images.githubusercontent.com/58871/53190370-59256180-3601-11e9-9eb8-01bf51888dd7.png">

**Comment by olizilla** [comment]
@hacdias can you take a look at this pls

**Comment by hacdias** [comment]
I will!

**Comment by hacdias** [comment]
@olizilla that error actually makes sense and the only way not to print it is by not using the API URL on the Welcome Page. We use it to check if we're on the same origin or not.

https://github.com/ipfs-shipyard/ipfs-webui/blob/8b0888662617328fdcfeb3c63a11fdf2d750472c/src/welcome/WelcomePage.js#L143

https://github.com/ipfs-shipyard/ipfs-webui/blob/8b0888662617328fdcfeb3c63a11fdf2d750472c/src/welcome/WelcomePage.js#L11-L16

**Comment by olizilla** [comment]
sure, but can we make the code robust to that error. there is no need to print expected situations as errors to the console.
