### ISSUE TITLE
i held down Crtl - and it zoomed all the way out. Ctrl + is not working

### ISSUE THREAD

**Issue by corviato1** [ipfs-shipyard/ipfs-webui#968]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fsdiogo** [comment]
Hey @corviato1, that seems like a browser issue and not a Web UI related one, can you elaborate a bit more?

I can `CTRL +` and `CTRL -` to zoom in and out. Try `CTRL 0`, that usually rolls back to the default zoom.

**Comment by corviato1** [comment]
![github](https://user-images.githubusercontent.com/44780076/53271068-2e3f1a00-36a2-11e9-91fa-795259886527.png)

**Comment by corviato1** [comment]
OMG!  Ctrl 0 worked! you are the best, thank you :)

**Comment by fsdiogo** [comment]
No problem 👌
