### ISSUE TITLE
Unobtrusive help system to onboard new users

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#979]
> **unobtrusive** | ʌnəbˈtruːsɪv |
> _adjective_
> not conspicuous or attracting attention: _the service was unobtrusive and efficient._

### Is being inconspicuous an important goal?

Perhaps not directly. I think the main point was that help should be easily available for those that want it and shouldn't distract those who dont want it.

Other valuable goals would be
- Maintainble, and always in sync with the current UI
- Localizable, via transifex and https://github.com/ipfs/i18n
- Legible and accessible
- Linked to proto.school work and IPFS documentation endevours
- Crowdsource /  Allow folks to add their own annotations (discussify?)

### What does an unobtrusive help system look like? 

Your thoughts here!

**Comment by olizilla** [comment]
Maybe https://introjs.com/ ?

**Comment by lidel** [comment]
I'm for it, given the educational mission of UIs  maintained by IPFS project, we should aim to provide contextual help using the same visual language across all UIs.

I like the idea of something like [introjs/hint](https://introjs.com/example/hint/index.html) for one-time onboarding coupled with persistent icon next to various values in UI that may need explaining. Both should be using the same visual indicator, perhaps something like: <img src="https://user-images.githubusercontent.com/157609/53423098-04a72b00-39e1-11e9-856e-c326e38ca5e1.png" width="16px" height="16px"/> <img src="https://user-images.githubusercontent.com/157609/53423262-56e84c00-39e1-11e9-9b14-1ca0196942e7.png" width="16px" height="16px"/> <img src="https://user-images.githubusercontent.com/157609/53423263-56e84c00-39e1-11e9-807f-fe362a30ca84.png" width="16px" height="16px"/> 


If we want it to be unobtrusive, the first step would be to come up with convention for linking to relevant docs from UIs. Right now we can link to docs but it will look like any other link. To make it legible and accessible  `cursor: help`  will not be enough, we need a consistent hint on top of that, eg. mentioned indicator icon:

> _Some Vague Technical Term_<sup><img src="https://user-images.githubusercontent.com/157609/53423263-56e84c00-39e1-11e9-807f-fe362a30ca84.png" width="16px" height="16px"/> </sup>

**Comment by olizilla** [comment]
A few folks have expressed a dislike of introjs style "guided" intros as a help system.

@ericronne suggested a similar idea to you @lidel in that we have a visual indication where the user can get more info about a term, and clicking on it brings a **glossary** into view, scrolled to the term in question, but also allowing the user to scroll around to read about other terms that we have more info on.

**Comment by ericronne** [comment]
It might be good to offer a combination of one or two approaches.

I think some folks find guided tours useful, provided the associated panels or whatever are easily dismissed, and never return unless the user seeks them out. Figma's onboarding experience has a few things going for it, which could be instructive.

## Figma onboarding

### Initial web-app launch
Modal panel with brief welcome message appears. Opportunity to see tips or click the X to exit. Ideally the close X would be more prominent, and clicking it would forever close the walkthrough (it returns, unbidden).

![figma-onboarding-01](https://user-images.githubusercontent.com/9259185/53599791-a6f41980-3b6d-11e9-83e4-f18ef0a519a5.png)

### Individual feature explanations
Click Next to advance to a feature description, with a nice animation for each.

![mggj1lk6rm](https://user-images.githubusercontent.com/9259185/53600725-de63c580-3b6f-11e9-9813-78f2cb90b025.gif)

### Learn More links
Each panel has a text link which opens the help site in a new tab.

![learn](https://user-images.githubusercontent.com/9259185/53600790-0ce1a080-3b70-11e9-8935-f5a498c71ece.png)
![learnmore](https://user-images.githubusercontent.com/9259185/53600887-55995980-3b70-11e9-96df-3e1a1bdbe402.png)

### Return to onboarding at any time
After dismissing a panel, the user can re-enter the walkthrough via a sticky (**boo**) question-mark button in the corner of the page.

![reset](https://user-images.githubusercontent.com/9259185/53600914-6cd84700-3b70-11e9-95f1-4970ebd655ba.png)

Regardless of what tack we pursue, i hope to contribute to the design as much as possible  😇 thx!

**Comment by fsdiogo** [comment]
> I like the idea of something like [introjs/hint](https://introjs.com/example/hint/index.html) for one-time onboarding coupled with persistent icon next to various values in UI that may need explaining. Both should be using the same visual indicator, perhaps something like: <img alt="" width="16px" height="16px" src="https://user-images.githubusercontent.com/157609/53423098-04a72b00-39e1-11e9-856e-c326e38ca5e1.png"> <img alt="" width="16px" height="16px" src="https://user-images.githubusercontent.com/157609/53423262-56e84c00-39e1-11e9-9b14-1ca0196942e7.png"> <img alt="" width="16px" height="16px" src="https://user-images.githubusercontent.com/157609/53423263-56e84c00-39e1-11e9-807f-fe362a30ca84.png">

I can see the benefits of having something like that, but honestly I'm not a big fan of this solution. We have many technical terms, I'm afraid the UI would become cluttered and the user would have to play a bit of [Where's Wally](https://en.wikipedia.org/wiki/Where%27s_Wally%3F).

I much prefer a guided tour, I really love the Figma example that @ericronne pointed out. That's really the best of both worlds, as it teaches the user how to use the app and clearly shows the app capabilities. As a bonus, while showing all that we can have links and/or explanations  of the technical terms.

> @ericronne suggested a similar idea to you @lidel in that we have a visual indication where the user can get more info about a term, and clicking on it brings a **glossary** into view, scrolled to the term in question, but also allowing the user to scroll around to read about other terms that we have more info on.

On GitHub, if you press `SHIFT` + `?` a modal with the keyboard shortcuts appears, we could have something similar like that with some terms:

<img width="1111" alt="github" src="https://user-images.githubusercontent.com/33324750/53633770-55e93180-3c10-11e9-9c89-e660ef2f13a9.png">

<hr>

We should focus on what we really want out of this help system:

- **(A)** Show what you can do with the Web UI and teach how to use it
- **(B)** Learn about the more technical concepts about IPFS and its capabilities 
- **(C)** A mix of those above
- **(D)** Other
 
Having this well defined on our heads will help us choose the best solution.

I think **(A)** should be the priority for now, it will eventually bring a bit of **(B)** to.

**Comment by fsdiogo** [comment]
`intro.js` style react libs:

- [react-joyride](https://react-joyride.com)
- [react-user-tour](https://github.com/socialtables/react-user-tour)

This is another style that could work in a simpler page:

![chardin](https://user-images.githubusercontent.com/33324750/53635189-3c49e900-3c14-11e9-9dda-87310ec8f368.gif)

**Comment by ericronne** [comment]
That's ☝️gorgeous. Also TIL a new github trick, thanks @fsdiogo!

A shortcut such as github's `shift-?` could be very handy, provided we let the user know that it's there.

**Comment by lidel** [comment]
cc https://github.com/ipfs-shipyard/ipfs-webui/issues/756 (_Display help when pressing_ <kbd>?</kbd>)

**Comment by olizilla** [comment]
@fsdiogo is working on a demo of [react-joyride](https://github.com/gilbarbara/react-joyride) in webui

![react-joyride demo in webui](https://user-images.githubusercontent.com/58871/53814132-f57f2a80-3f56-11e9-8cec-ffdea194c6d0.gif)

**Comment by fsdiogo** [comment]
Also, taking @lidel's suggestion, we can have a way to trigger helpers in specific places to show info about specific things instead of having to take the tour:

![dot](https://user-images.githubusercontent.com/33324750/53814370-69b9ce00-3f57-11e9-82f7-550dffac9b3e.gif)

**Comment by olizilla** [comment]
@fsdiogo can open a WIP PR for that, so we get a preview build link that we can all try out? Other things that'd be rad

- A chardin.js demo for webui
- A shared doc to define the sections of the web ui, what they do, and what needs explaining. This might work best as a google doc to get us started.

@ericronne are you up for leading the charge on how this should be presented to the user?

**Comment by fsdiogo** [comment]
Just opened a [WIP PR](https://github.com/ipfs-shipyard/ipfs-webui/pull/983) with a guided tour in the `Status` and `Files` page.

**Comment by fsdiogo** [comment]
I've created a [google doc](https://docs.google.com/document/d/1FNqrzjnPcgcyD6OIrkihPbjXkQFIlkCmdd5T1GYqVpI/edit?usp=sharing) so we can share insight about what should be present in each guided tour.

cc @ipfs-shipyard/gui @terichadbourne
