### ISSUE TITLE
Update to Storybook 5

### ISSUE THREAD

**Issue by fsdiogo** [ipfs-shipyard/ipfs-webui#986]
Update to the shiny Storybook 5 🌟 

https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8

**Comment by olizilla** [comment]
Let's make sure we build and publish the storybook somewhere. I could be as simple as `/storybook`

**Comment by cwaring** [comment]
Just a thought; do we want to expose/upgrade storybook in this project if
the priority is to migrate to a consolidated component library?

**Comment by fsdiogo** [comment]
@cwaring I think we do, as we have some whole pages in Storybook to check their state.

The individual components can be extracted to be component library, but I guess that we'll still have some to show in the Web UI storybook.

**Comment by olizilla** [comment]
Let's have both!
