### ISSUE TITLE
Update bundled go-ipfs to 0.4.19 or check path for existing install.

### ISSUE THREAD

**Issue by legowerewolf** [ipfs-shipyard/ipfs-webui#988]
**Is your feature request related to a problem? Please describe.**
The release of go-ipfs 0.4.19 was 10 days ago. Is there a reason it's not the bundled version? Alternately, I have a separate install of go-ipfs 0.4.19 (managed by Chocolatey) that I would like to use. Is there a reason ipfs-desktop doesn't look for an existing install before using/fetching the bundled version?

**Describe the solution you'd like**
At least one of the following: 
* Update the bundled version of go-ipfs to 0.4.19 (and keep on top of updates)
* Prefer the use of preinstalled IPFS binaries.

**Describe alternatives you've considered**
Either of the above would solve my problem: the automatically-starting IPFS daemon being behind the latest release.

**Comment by olizilla** [comment]
IPFS Desktop 0.7.1 is released with go-ipfs 0.4.19
