### ISSUE TITLE
Can't connect to API over HTTPS

### ISSUE THREAD

**Issue by xuhcc** [ipfs-shipyard/ipfs-webui#989]
When I open Web UI (version 2.4.1), it shows the "Failed to connect to the API." page. IPFS API is located at `https://****:5002`. In the browser console I see these messages:

```
Trying IPFS Companion index.js:4
🎛️ Customise your js-ipfs-api options by storing a `ipfsApi` object in localStorage. e.g. localStorage.setItem('ipfsApi', '/ip4/127.0.0.1/tcp/5001') index.js:8
Trying ipfs-api with custom api address /dnsaddr/****/tcp/5002/https index.js:11
Failed to connect to ipfs-api /dnsaddr/****/tcp/5002/https index.js:49
Processing queued call
["add_event",{"key":"IPFS_INIT_FAILED","count":1,"dur":0.012}]
```

If I replace `/dnsaddr/` with `/dns4/` then this error gets printed to console (in addition to the above):

```
Blocked loading mixed active content “http://****:5002/api/v0/stats/bw?stream-channels=true”
```

- OS: Linux
- Browser: Firefox 65.0.2

**Comment by lidel** [comment]
I updated the title to better reflect that is the problem.

**Comment by lidel** [comment]
@xuhcc Did you try to manually tell Web UI what is the multiaddr of your API?
Are you able to check if it helps?

>  ![2019-04-08--17-23-51](https://user-images.githubusercontent.com/157609/55736247-40430500-5a23-11e9-9641-69ef7a0ddc61.png)


> ![2019-04-08--17-24-25](https://user-images.githubusercontent.com/157609/55736260-446f2280-5a23-11e9-9235-fc1baf682750.png)

**Comment by xuhcc** [comment]
@lidel 

Yes. In my case, API address on status page looks like `/dns4/***.net/tcp/5002/https`.
I also tried to remove `ipfsApi` key from local storage and re-open web UI from IPFS companion.

**Comment by lidel** [comment]
Ok, I can confirm there is a bug (`https` is not picked up from multiaddr, `http` is used in API test instead)

> ![1-2019-04-08--17-48-29](https://user-images.githubusercontent.com/157609/55738076-aaa97480-5a26-11e9-8d6c-8a8528e8faae.png)
> ![2-2019-04-08--17-48-54](https://user-images.githubusercontent.com/157609/55738075-aaa97480-5a26-11e9-945d-12a53b943326.png)
