### ISSUE TITLE
Add loading indicator on file preview page

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#991]
A file preview can take a a few seconds to show up, but there is no indication in the UI that anything is a happening.

**Comment by jessicaschilling** [comment]
NOTE: There's a duplicate of this issue for Companion in https://github.com/ipfs-shipyard/ipfs-companion/issues/727. Let's treat that issue as the master, and ensure whatever happens there can be implemented in WebUI.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 - does #1570 close this?

**Comment by rafaelramalho19** [comment]
Yes 😄
