### ISSUE TITLE
Allow IPFS Desktop to pass in the countly key to use

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#992]
Right now we always use the production countly app key when using web ui from IPFS Desktop. This is because the logic in the analytics is checking `process.env.NODE_ENV`, which will always be set to `production` when using a release version of webui.

Instead, we could pass in a countly app key on `window.ipfsDesktop.countlyAppKey`, and have that be either the prod key or the dev key based on the value of `NODE_ENV` from the ipfs desktop process.

**Comment by olizilla** [comment]
See https://github.com/ipfs-shipyard/ipfs-webui/blob/7321a350ddea62837661fbf749bac57ae119dea1/src/bundles/analytics.js#L23-L31

**Comment by hacdias** [comment]
@olizilla please see:

- https://github.com/ipfs-shipyard/ipfs-webui/pull/993
- https://github.com/ipfs-shipyard/ipfs-desktop/pull/872

**Comment by olizilla** [comment]
Done in #993
