### ISSUE TITLE
"Help improve this app by sending anonymous usage data." is not remembered and reappears on CTRL + F5

### ISSUE THREAD

**Issue by Mikaela** [ipfs-shipyard/ipfs-webui#998]
**Describe the bug**

The question "Help improve this app by sending anonymous usage data." appears every time I press CTRL+F5. I am not sure if this is the correct repository (but GitHub suggesting related issue https://github.com/ipfs-shipyard/ipfs-webui/issues/774 hints this is), I am using IPFS Companion.

**To Reproduce**
1. Go to IPFS webui (for me http://[::1]:8082/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/#/ )
2. There is a question "Help improve this app by sending anonymous usage data.", press OK or go to "More info" and give the permission.
3. Return to the index and/or press CTRL + F5
4. See the question return. This also happens by itself at times when revisiting the webui, but CTRL + F5 seems the easiest way to reproduce it.

**Expected behavior**

I see the prompt to share anonymous usage data only once.

**Screenshots**

I think it's N/A, but please feel free to ask.

**Desktop (please complete the following information):**
 - OS: Debian testing (Buster/10)
 - Browser: Firefox 
 - Version: 67.0b6 (20190328152334)

**Additional context**

I have Cookie Autodelete, but [::1] is whitelisted, so I don't think it should affect here. I have moved to [::1] from 127.0.0.1 by myself (see also https://github.com/ipfs/go-ipfs/issues/5905). I am running Syncthing on 8080, so I have changed the IPFS port.

**Comment by olizilla** [comment]
Oh interesting! Web UI is currently using the browers IndexDB to keep a record of the list of consents that the user grants. I took a quick look at Cookie Autodelete but I don't see any references to it cleaning IndexDB records... do you know if anything in your set up might be deleting that? For reference, in Firefox I see the following entry in the inspector > Storage > Index DB > bundle-cache > bundle-cache 

![Screenshot 2019-04-02 at 11 43 30](https://user-images.githubusercontent.com/58871/55397072-40339880-553d-11e9-8628-1727cd48f817.png)

If something is deleting that DB then that would explain why the ask keeps showing up, as we dont track anything if we find no record of user consent.

**Comment by Mikaela** [comment]
I seem to have localstorage cleaning enabled in Cookie Autodelete, but it shouldn't affect as ::1 is in whitelist and I cannot find the analytics key, bundle-cache seems to be empty.

When I go to https://webui.ipfs.io/ and click the OK, I see analytics getting created. My CAD whitelist also has `*.ipfs.io`.

**Comment by bertrandfalguiere** [comment]
Looks fixed?

**Comment by jessicaschilling** [comment]
@Mikaela - closing this issue. Please comment to re-open if you have issues.
