### ISSUE TITLE
CID formatting changes

### ISSUE THREAD

**Issue by achingbrain** [ipfs-shipyard/ipfs-webui#999]
I've tried to explore a `bafy` CID but in the breadcrumb & the CID info it's displayed as `zdj` CID.  It should probably retain the same encoding as the user types in.

![image](https://user-images.githubusercontent.com/665810/55393420-1d9d8180-5535-11e9-98a4-05055a64721d.png)

I mean, I know these are all the same CID, but someone new to IPFS might not.

**Comment by olizilla** [comment]
Derp. Thanks for reporting.

**Comment by olizilla** [comment]
Nice issue number.

**Comment by achingbrain** [comment]
🚓🚒🚑

**Comment by olizilla** [comment]
This should be fixed in the next `cids` release now https://github.com/multiformats/js-cid/pull/77 is merged.

**Comment by olizilla** [comment]
@vmx please may you perform the release dance on js-cid when you get a moment so I can fix this here issue.

**Comment by vmx** [comment]
@olizilla Done.

**Comment by olizilla** [comment]
Thank you sir @vmx
